kind: Service
apiVersion: v1
metadata:
  name: daemon
  namespace: cybericebox
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
    - port: 51820
      name: vpn
      targetPort: 51820