package emaildefaults

func fallbackEN(url string) node {
	return rich(
		para("The button does not open? Copy this link into your browser:"),
		para(link("{{"+url+"}}", variable(url))),
	)
}

func enTemplates() []Template {
	event := fact{"Event", "{{event_name}}"}
	return []Template{
		{
			Type: "continue_registration", Subject: "Finish your Cyber ICE Box registration", Preheader: "One more step and your account is ready",
			Body: blocks(logo(),
				rich(heading("Finish your registration"), para("Hello, ", variable("Name"), "! One more step and you can start using Cyber ICE Box.")),
				button("Finish registration", "{{RegistrationURL}}"),
				fallbackEN("RegistrationURL"),
				rich(para("If you did not sign up, just ignore this email."))),
		},
		{
			Type: "password_reset", Subject: "Reset your Cyber ICE Box password", Preheader: "Get back into your account",
			Body: blocks(logo(),
				rich(heading("Password reset"), para("Hello, ", variable("Name"), "! We received a request to reset the password of your account.")),
				button("Reset password", "{{ResetURL}}"),
				fallbackEN("ResetURL"),
				rich(para("If it was not you, do nothing: your password stays the same."))),
		},
		{
			Type: "email_confirmation", Subject: "Confirm your email", Preheader: "Confirm your new email address",
			Body: blocks(logo(),
				rich(heading("Confirm your email"), para("Hello, ", variable("Name"), "! Confirm this address to link it to your Cyber ICE Box account.")),
				button("Confirm email", "{{ConfirmURL}}"),
				fallbackEN("ConfirmURL"),
				rich(para("If you did not request this, ignore this email."))),
		},
		{
			Type: "user_invitation", Subject: "You are invited to Cyber ICE Box", Preheader: "Finish setting up your account",
			Body: blocks(logo(),
				rich(heading("You are invited to Cyber ICE Box"), para("Accept the invitation and set up your account.")),
				button("Accept invitation", "{{InviteURL}}"),
				fallbackEN("InviteURL")),
		},
		{
			Type: "account_exists", Subject: "Your account already exists", Preheader: "There is already an account for this email",
			Body: blocks(logo(),
				rich(heading("Your account already exists"),
					para("Hello, ", variable("Name"), "! There is already a Cyber ICE Box account for this address. If it was you, just sign in."),
					para("If you did not sign up, no action is needed."))),
		},
		{
			Type: "email_changed", Subject: "The account email was changed", Preheader: "Sign-in with Google is turned off",
			Body: blocks(logo(),
				rich(heading("The email was changed"),
					para("Hello, ", variable("Name"), "! The address of your Cyber ICE Box account was changed to ", variable("NewEmail"), "."),
					para("Sign-in with Google is turned off with it: if it was linked, sign in with your password.")),
				button("Reset password", "{{ResetURL}}"),
				fallbackEN("ResetURL"),
				rich(para("If this was not you, reset your password now with the button above."))),
		},
		{
			Type: "account_inactivity_warning", Subject: "Your Cyber ICE Box account will be deleted", Preheader: "Sign in to keep your account",
			Body: blocks(logo(),
				rich(heading("Your account will be deleted"),
					para("Hello, ", variable("Name"), "! You have not signed in to Cyber ICE Box for a long time. Under the Privacy Policy we will delete the account and its personal data.")),
				facts(fact{"Deletion date", "{{DeletionDate}}"}),
				button("Sign in and keep my account", "{{SignInURL}}"),
				rich(para("Competition results stay in the event history in anonymized form."))),
		},
		{
			Type: "flag_accepted", Subject: "Flag accepted: «{{.Challenge}}»", Preheader: "You earned {{.Points}} points",
			Body: blocks(logo(),
				rich(heading("Flag accepted")),
				facts(fact{"Challenge", "{{Challenge}}"}, fact{"Points", "{{Points}}"})),
		},
		{
			Type: "event.manager.assigned", Subject: "Access to the event «{{.event_name}}»", Preheader: "You have been given a role in the event",
			Body: blocks(logo(),
				rich(heading("You now have access to an event"),
					para("You have been assigned as ", variable("role_name"), " of the event «", variable("event_name"), "»."),
					para("Your access matches your role."))),
		},
		{
			Type: "event.lab.failed", Subject: "Lab is down: team «{{.team_name}}»", Preheader: "The lab of team «{{.team_name}}» is not working",
			Body: blocks(logo(),
				rich(heading("A lab is down")),
				facts(event, fact{"Team", "{{team_name}}"}, fact{"Reason", "{{reason}}"}),
				rich(para("Check the team’s lab on the «Labs» page of the event panel."))),
		},
		{
			Type: "participant.approval_registration.submitted", Participant: true,
			Subject: "Application for «{{.event_name}}» received", Preheader: "Wait for the decision",
			Body: blocks(logo(),
				rich(heading("Application received"), para("We received your application to take part in «", variable("event_name"), "». The organizers will review it and let you know.")),
				facts(event, fact{"Status", "Under review"})),
		},
		{
			Type: "participant.approval_registration.approved", Participant: true,
			Subject: "You are in: «{{.event_name}}»", Preheader: "Your application is approved",
			Body: blocks(logo(),
				rich(heading("Participation approved"), para("Your application to take part in «", variable("event_name"), "» is approved. You can join the event.")),
				facts(event, fact{"Status", "Approved"}),
				button("Go to the event", "{{event_url}}")),
		},
		{
			Type: "participant.approval_registration.rejected", Participant: true,
			Subject: "Application for «{{.event_name}}» declined", Preheader: "The decision on your application",
			Body: blocks(logo(),
				rich(heading("Application declined"),
					para("Unfortunately, your application to take part in «", variable("event_name"), "» was declined."),
					para("If this is a mistake, contact the event organizers."))),
		},
		{
			Type: "participant.open_registration.completed", Participant: true,
			Subject: "Registration for «{{.event_name}}» complete", Preheader: "You are registered",
			Body: blocks(logo(),
				rich(heading("You are registered"), para("You have registered for «", variable("event_name"), "». Participation details will appear in your account.")),
				facts(event),
				button("Go to the event", "{{event_url}}")),
		},
		{
			Type: "participant.invitation.sent", Participant: true,
			Subject: "Invitation to «{{.event_name}}»", Preheader: "You are invited to take part",
			Body: blocks(logo(),
				rich(heading("You are invited to an event"), para("The organizers invite you to take part in «", variable("event_name"), "».")),
				facts(event),
				button("Accept invitation", "{{invite_url}}"),
				fallbackEN("invite_url")),
		},
		{
			Type: "participant.team_invitation.sent", Participant: true,
			Subject: "Invitation to team «{{.team_name}}»", Preheader: "You are invited to a team at an event",
			Body: blocks(logo(),
				rich(heading("Team invitation"), para("You are invited to team «", variable("team_name"), "» at «", variable("event_name"), "».")),
				facts(event, fact{"Team", "{{team_name}}"}),
				button("Accept invitation", "{{invite_url}}"),
				fallbackEN("invite_url"),
				rich(para("After you accept, the team appears on your ", link("{{team_url}}", text("participation page")), "."))),
		},
		{
			Type: "participant.invitation.accepted", Participant: true,
			Subject: "Invitation to «{{.event_name}}» accepted", Preheader: "Your participation is confirmed",
			Body: blocks(logo(),
				rich(heading("Invitation accepted"), para("You accepted the invitation to «", variable("event_name"), "». Your participation is confirmed.")),
				facts(event, fact{"Status", "Participation confirmed"}),
				button("Go to the event", "{{event_url}}")),
		},
		{
			Type: "participant.invitation.revoked", Participant: true,
			Subject: "Invitation to «{{.event_name}}» withdrawn", Preheader: "The invitation is no longer valid",
			Body: blocks(logo(),
				rich(heading("Invitation withdrawn"),
					para("The invitation to «", variable("event_name"), "» was withdrawn."),
					para("If this is a mistake, contact the event organizers."))),
		},
		{
			Type: "participant.invitation.expired", Participant: true,
			Subject: "Invitation to «{{.event_name}}» expired", Preheader: "The invitation is no longer valid",
			Body: blocks(logo(),
				rich(heading("Invitation expired"),
					para("The invitation to «", variable("event_name"), "» is no longer valid."),
					para("If you still want to take part, contact the organizers."))),
		},
		{
			Type: "participant.event.start_reminder", Participant: true,
			Subject: "«{{.event_name}}» starts {{.start_at}}", Preheader: "Start reminder",
			Body: blocks(logo(),
				rich(heading("The event starts soon"), para("A reminder about «", variable("event_name"), "».")),
				facts(event, fact{"Start (Kyiv time)", "{{start_at}}"}),
				button("Go to the event", "{{event_url}}"),
				rich(para("Check in advance that you can sign in to your account."))),
		},
		{
			Type: "participant.event.finished", Participant: true,
			Subject: "«{{.event_name}}» has ended", Preheader: "Thank you for taking part",
			Body: blocks(logo(),
				rich(heading("The event has ended"), para("Thank you for taking part in «", variable("event_name"), "»!")),
				facts(event, fact{"Ended (Kyiv time)", "{{finish_at}}"}),
				rich(para("Results will appear on the event site as soon as the organizers open them.")),
				button("Go to the event site", "{{event_url}}")),
		},
		{
			Type: "participant.event.results_published", Participant: true,
			Subject: "Results of «{{.event_name}}» are open", Preheader: "Results are available",
			Body: blocks(logo(),
				rich(heading("Results are open"), para("The results of «", variable("event_name"), "» are now available on the event site.")),
				button("View results", "{{event_url}}")),
		},
	}
}
