package emaildefaults

// fallbackUK is the «button does not open» line under an action button.
func fallbackUK(url string) node {
	return rich(
		para("Кнопка не відкривається? Скопіюйте це посилання в браузер:"),
		para(link("{{"+url+"}}", variable(url))),
	)
}

func ukTemplates() []Template {
	event := fact{"Захід", "{{event_name}}"}
	return []Template{
		{
			Type: "continue_registration", Subject: "Завершіть реєстрацію в Cyber ICE Box", Preheader: "Ще один крок, і обліковий запис готовий",
			Body: blocks(logo(),
				rich(heading("Завершіть реєстрацію"), para("Вітаємо, ", variable("Name"), "! Ще один крок, і ви зможете користуватися Cyber ICE Box.")),
				button("Завершити реєстрацію", "{{RegistrationURL}}"),
				fallbackUK("RegistrationURL"),
				rich(para("Якщо ви не реєструвалися, просто проігноруйте цей лист."))),
		},
		{
			Type: "password_reset", Subject: "Скидання пароля Cyber ICE Box", Preheader: "Відновіть доступ до облікового запису",
			Body: blocks(logo(),
				rich(heading("Скидання пароля"), para("Вітаємо, ", variable("Name"), "! Ми отримали запит на скидання пароля до вашого облікового запису.")),
				button("Скинути пароль", "{{ResetURL}}"),
				fallbackUK("ResetURL"),
				rich(para("Якщо це були не ви, нічого не робіть: пароль залишиться попереднім."))),
		},
		{
			Type: "email_confirmation", Subject: "Підтвердьте електронну пошту", Preheader: "Підтвердіть нову адресу пошти",
			Body: blocks(logo(),
				rich(heading("Підтвердіть електронну пошту"), para("Вітаємо, ", variable("Name"), "! Підтвердьте цю адресу, щоб пов’язати її з обліковим записом Cyber ICE Box.")),
				button("Підтвердити пошту", "{{ConfirmURL}}"),
				fallbackUK("ConfirmURL"),
				rich(para("Якщо ви цього не робили, проігноруйте лист."))),
		},
		{
			Type: "user_invitation", Subject: "Вас запрошено до Cyber ICE Box", Preheader: "Завершіть налаштування облікового запису",
			Body: blocks(logo(),
				rich(heading("Вас запрошено до Cyber ICE Box"), para("Прийміть запрошення та налаштуйте свій обліковий запис.")),
				button("Прийняти запрошення", "{{InviteURL}}"),
				fallbackUK("InviteURL")),
		},
		{
			Type: "account_exists", Subject: "Обліковий запис уже існує", Preheader: "Для цієї пошти вже є обліковий запис",
			Body: blocks(logo(),
				rich(heading("Обліковий запис уже існує"),
					para("Вітаємо, ", variable("Name"), "! Для цієї адреси вже є обліковий запис Cyber ICE Box. Якщо це були ви, просто увійдіть до нього."),
					para("Якщо ви не реєструвалися, жодних дій не потрібно."))),
		},
		{
			Type: "account_inactivity_warning", Subject: "Ваш обліковий запис Cyber ICE Box буде видалено", Preheader: "Увійдіть, щоб зберегти обліковий запис",
			Body: blocks(logo(),
				rich(heading("Обліковий запис буде видалено"),
					para("Вітаємо, ", variable("Name"), "! Ви давно не входили до Cyber ICE Box. Відповідно до Політики конфіденційності ми видалимо обліковий запис і пов’язані з ним персональні дані.")),
				facts(fact{"Дата видалення", "{{DeletionDate}}"}),
				button("Увійти й зберегти обліковий запис", "{{SignInURL}}"),
				rich(para("Результати змагань залишаться в історії заходів у знеособленому вигляді."))),
		},
		{
			Type: "flag_accepted", Subject: "Прапор завдання «{{.Challenge}}» зараховано", Preheader: "Ви отримали {{.Points}} балів",
			Body: blocks(logo(),
				rich(heading("Прапор зараховано")),
				facts(fact{"Завдання", "{{Challenge}}"}, fact{"Бали", "{{Points}}"})),
		},
		{
			Type: "event.manager.assigned", Subject: "Доступ до заходу «{{.event_name}}»", Preheader: "Вам призначено роль у заході",
			Body: blocks(logo(),
				rich(heading("Вам надано доступ до заходу"),
					para("Вас призначено ", variable("role_name"), " заходу «", variable("event_name"), "»."),
					para("Доступ відповідає вашій ролі."))),
		},
		{
			Type: "event.lab.failed", Subject: "Лабораторія не працює: команда «{{.team_name}}»", Preheader: "Лабораторія команди «{{.team_name}}» не працює",
			Body: blocks(logo(),
				rich(heading("Лабораторія не працює")),
				facts(event, fact{"Команда", "{{team_name}}"}, fact{"Причина", "{{reason}}"}),
				rich(para("Перевірте лабораторію команди на сторінці «Лабораторії» керування заходом."))),
		},
		{
			Type: "participant.approval_registration.submitted", Participant: true,
			Subject: "Заявку на захід «{{.event_name}}» подано", Preheader: "Очікуйте рішення щодо участі",
			Body: blocks(logo(),
				rich(heading("Заявку подано"), para("Ми отримали вашу заявку на участь у заході «", variable("event_name"), "». Організатори розглянуть її та повідомлять про рішення.")),
				facts(event, fact{"Статус", "На розгляді"})),
		},
		{
			Type: "participant.approval_registration.approved", Participant: true,
			Subject: "Участь у заході «{{.event_name}}» схвалено", Preheader: "Вашу заявку схвалено",
			Body: blocks(logo(),
				rich(heading("Участь схвалено"), para("Вашу заявку на участь у заході «", variable("event_name"), "» схвалено. Ви можете долучитися до заходу.")),
				facts(event, fact{"Статус", "Схвалено"}),
				button("Перейти до заходу", "{{event_url}}")),
		},
		{
			Type: "participant.approval_registration.rejected", Participant: true,
			Subject: "Заявку на захід «{{.event_name}}» відхилено", Preheader: "Рішення щодо вашої заявки",
			Body: blocks(logo(),
				rich(heading("Заявку відхилено"),
					para("На жаль, вашу заявку на участь у заході «", variable("event_name"), "» відхилено."),
					para("Якщо це сталося помилково, зверніться до організаторів заходу."))),
		},
		{
			Type: "participant.open_registration.completed", Participant: true,
			Subject: "Реєстрацію на захід «{{.event_name}}» завершено", Preheader: "Ви зареєстровані на захід",
			Body: blocks(logo(),
				rich(heading("Ви зареєстровані"), para("Ви успішно зареєструвалися на захід «", variable("event_name"), "». Інформація про участь з’явиться у вашому обліковому записі.")),
				facts(event),
				button("Перейти до заходу", "{{event_url}}")),
		},
		{
			Type: "participant.invitation.sent", Participant: true,
			Subject: "Запрошення до заходу «{{.event_name}}»", Preheader: "Вас запросили взяти участь",
			Body: blocks(logo(),
				rich(heading("Вас запрошено до заходу"), para("Організатори запрошують вас узяти участь у заході «", variable("event_name"), "».")),
				facts(event),
				button("Прийняти запрошення", "{{invite_url}}"),
				fallbackUK("invite_url")),
		},
		{
			Type: "participant.team_invitation.sent", Participant: true,
			Subject: "Запрошення до команди «{{.team_name}}»", Preheader: "Вас запросили до команди на заході",
			Body: blocks(logo(),
				rich(heading("Запрошення до команди"), para("Вас запрошують до команди «", variable("team_name"), "» на заході «", variable("event_name"), "».")),
				facts(event, fact{"Команда", "{{team_name}}"}),
				button("Прийняти запрошення", "{{invite_url}}"),
				fallbackUK("invite_url"),
				rich(para("Після прийняття запрошення команда з’явиться на ", link("{{team_url}}", text("сторінці участі")), "."))),
		},
		{
			Type: "participant.invitation.accepted", Participant: true,
			Subject: "Запрошення до заходу «{{.event_name}}» прийнято", Preheader: "Вашу участь підтверджено",
			Body: blocks(logo(),
				rich(heading("Запрошення прийнято"), para("Ви прийняли запрошення до заходу «", variable("event_name"), "». Вашу участь підтверджено.")),
				facts(event, fact{"Статус", "Участь підтверджено"}),
				button("Перейти до заходу", "{{event_url}}")),
		},
		{
			Type: "participant.invitation.revoked", Participant: true,
			Subject: "Запрошення до заходу «{{.event_name}}» скасовано", Preheader: "Запрошення більше не чинне",
			Body: blocks(logo(),
				rich(heading("Запрошення скасовано"),
					para("Запрошення до заходу «", variable("event_name"), "» скасовано."),
					para("Якщо це сталося помилково, зверніться до організаторів заходу."))),
		},
		{
			Type: "participant.invitation.expired", Participant: true,
			Subject: "Термін запрошення до заходу «{{.event_name}}» минув", Preheader: "Запрошення більше не чинне",
			Body: blocks(logo(),
				rich(heading("Термін запрошення минув"),
					para("Запрошення до заходу «", variable("event_name"), "» більше не чинне."),
					para("Якщо хочете взяти участь, зверніться до організаторів."))),
		},
		{
			Type: "participant.event.start_reminder", Participant: true,
			Subject: "Захід «{{.event_name}}» починається {{.start_at}}", Preheader: "Нагадування про старт",
			Body: blocks(logo(),
				rich(heading("Захід скоро почнеться"), para("Нагадуємо про захід «", variable("event_name"), "».")),
				facts(event, fact{"Початок (за київським часом)", "{{start_at}}"}),
				button("Перейти до заходу", "{{event_url}}"),
				rich(para("Заздалегідь перевірте, що можете увійти до облікового запису."))),
		},
		{
			Type: "participant.event.finished", Participant: true,
			Subject: "Захід «{{.event_name}}» завершено", Preheader: "Дякуємо за участь",
			Body: blocks(logo(),
				rich(heading("Захід завершено"), para("Дякуємо за участь у заході «", variable("event_name"), "»!")),
				facts(event, fact{"Завершення (за київським часом)", "{{finish_at}}"}),
				rich(para("Результати з’являться на сайті заходу, щойно організатори їх відкриють.")),
				button("Перейти на сайт заходу", "{{event_url}}")),
		},
		{
			Type: "participant.event.results_published", Participant: true,
			Subject: "Підсумки заходу «{{.event_name}}» відкрито", Preheader: "Результати вже доступні",
			Body: blocks(logo(),
				rich(heading("Підсумки відкрито"), para("Результати заходу «", variable("event_name"), "» уже доступні на сайті заходу.")),
				button("Переглянути результати", "{{event_url}}")),
		},
	}
}
