// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_audit_log.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminAuditLog = `-- name: CreateAdminAuditLog :exec
INSERT INTO admin_audit_log (id, actor_id, permission, method, route, response_status, created_at, target)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAdminAuditLogParams struct {
	ID             uuid.UUID `json:"id"`
	ActorID        uuid.UUID `json:"actor_id"`
	Permission     string    `json:"permission"`
	Method         string    `json:"method"`
	Route          string    `json:"route"`
	ResponseStatus int32     `json:"response_status"`
	CreatedAt      time.Time `json:"created_at"`
	Target         string    `json:"target"`
}

func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAdminAuditLog,
		arg.ID,
		arg.ActorID,
		arg.Permission,
		arg.Method,
		arg.Route,
		arg.ResponseStatus,
		arg.CreatedAt,
		arg.Target,
	)
	return err
}

const listAdminAuditLog = `-- name: ListAdminAuditLog :many
SELECT id, actor_id, permission, method, route, response_status, created_at, target
FROM admin_audit_log
WHERE ($1::uuid IS NULL OR actor_id = $1::uuid)
  AND ($2::text IS NULL OR permission = $2::text)
  AND ($3::text IS NULL OR route = $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAdminAuditLogParams struct {
	ActorID    uuid.NullUUID `json:"actor_id"`
	Permission pgtype.Text   `json:"permission"`
	Route      pgtype.Text   `json:"route"`
	LimitVal   int32         `json:"limit_val"`
}

func (q *Queries) ListAdminAuditLog(ctx context.Context, arg ListAdminAuditLogParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminAuditLog,
		arg.ActorID,
		arg.Permission,
		arg.Route,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Permission,
			&i.Method,
			&i.Route,
			&i.ResponseStatus,
			&i.CreatedAt,
			&i.Target,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
