// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveEvent = `-- name: ArchiveEvent :execrows
UPDATE events
SET archive_at        = $1::timestamptz,
    lifecycle_configured = true,
    publish_at        = $2::timestamptz,
    start_at          = $3::timestamptz,
    finish_at         = $4::timestamptz,
    withdraw_at       = $5::timestamptz,
    manual_finished_at = NULL,
    updated_at        = $6,
    updated_by        = $7
WHERE id = $8
  AND updated_at IS NOT DISTINCT FROM $9
`

type ArchiveEventParams struct {
	ArchiveAt         time.Time          `json:"archive_at"`
	PublishAt         time.Time          `json:"publish_at"`
	StartAt           time.Time          `json:"start_at"`
	FinishAt          time.Time          `json:"finish_at"`
	WithdrawAt        time.Time          `json:"withdraw_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         uuid.NullUUID      `json:"updated_by"`
	ID                uuid.UUID          `json:"id"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
}

// Keep the original available_from while closing both the legacy window and
// canonical lifecycle. A pending event has its canonical start moved just
// before the archive instant so the lifecycle constraint remains valid.
func (q *Queries) ArchiveEvent(ctx context.Context, arg ArchiveEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveEvent,
		arg.ArchiveAt,
		arg.PublishAt,
		arg.StartAt,
		arg.FinishAt,
		arg.WithdrawAt,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countEvents = `-- name: CountEvents :one
SELECT count(*)
FROM events
WHERE ($1::text = '' OR tag ILIKE '%' || $1::text || '%'
    OR internal_name ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountEvents(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsPage = `-- name: CountEventsPage :one
SELECT count(*)
FROM events
WHERE ($1::text = '' OR tag ILIKE '%' || $1::text || '%'
    OR internal_name ILIKE '%' || $1::text || '%')
  AND ($2::text = '' OR
    CASE WHEN archive_at IS NOT NULL AND archive_at <= $3::timestamptz THEN 'archived'
         WHEN available_from > $3::timestamptz THEN 'not_available'
         WHEN NOT lifecycle_configured OR publish_at > $3::timestamptz THEN 'not_published'
         WHEN withdraw_at IS NOT NULL AND withdraw_at <= $3::timestamptz THEN 'withdrawn'
         WHEN start_at > $3::timestamptz THEN 'published'
         WHEN (manual_finished_at IS NOT NULL AND manual_finished_at <= $3::timestamptz)
           OR (finish_at IS NOT NULL AND finish_at <= $3::timestamptz) THEN 'finished'
         ELSE 'started' END = $2::text)
`

type CountEventsPageParams struct {
	Search string    `json:"search"`
	Status string    `json:"status"`
	Now    time.Time `json:"now"`
}

func (q *Queries) CountEventsPage(ctx context.Context, arg CountEventsPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsPage, arg.Search, arg.Status, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveEventsWithTag = `-- name: CountLiveEventsWithTag :one
SELECT count(*)
FROM events
WHERE tag = $1
  AND (archive_at IS NULL OR archive_at > available_from)
  AND ($2::timestamptz IS NULL OR available_from < $2::timestamptz)
  AND (archive_at IS NULL OR archive_at > $3::timestamptz)
  AND id != $4::uuid
`

type CountLiveEventsWithTagParams struct {
	Tag           string             `json:"tag"`
	ArchiveAt     pgtype.Timestamptz `json:"archive_at"`
	AvailableFrom time.Time          `json:"available_from"`
	ExcludeID     uuid.UUID          `json:"exclude_id"`
}

// Conflict means overlapping HALF-OPEN platform windows, not merely a reused
// tag. The exclusion constraint closes the race between concurrent writers.
func (q *Queries) CountLiveEventsWithTag(ctx context.Context, arg CountLiveEventsWithTagParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveEventsWithTag,
		arg.Tag,
		arg.ArchiveAt,
		arg.AvailableFrom,
		arg.ExcludeID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, tag, name, internal_name, available_from, archive_at, lifecycle_configured,
                    created_at, created_by, updated_at, updated_by,
                    publish_at, start_at, finish_at, withdraw_at, infrastructure_allowed)
VALUES ($1, $2, $3, $4,
        $5::timestamptz, $6::timestamptz,
        false,
        $7, $8, $9, $10,
        $5::timestamptz, $5::timestamptz,
        NULL, NULL, $11) RETURNING id, tag, name, available_from, archive_at, updated_at, updated_by, created_at, created_by, join_policy, publish_at, start_at, finish_at, withdraw_at, manual_finished_at, scoring_mode, dynamic_algorithm, dynamic_min_points, dynamic_max_points, dynamic_floor_at_percent, force_event_scoring, landing_document, internal_name, lifecycle_configured, live_layout, live_layout_draft, infrastructure_allowed, landing_draft, static_points
`

type CreateEventParams struct {
	ID                    uuid.UUID          `json:"id"`
	Tag                   string             `json:"tag"`
	Name                  string             `json:"name"`
	InternalName          string             `json:"internal_name"`
	AvailableFrom         time.Time          `json:"available_from"`
	ArchiveAt             pgtype.Timestamptz `json:"archive_at"`
	CreatedAt             time.Time          `json:"created_at"`
	CreatedBy             uuid.NullUUID      `json:"created_by"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy             uuid.NullUUID      `json:"updated_by"`
	InfrastructureAllowed bool               `json:"infrastructure_allowed"`
}

// Timestamps come from the domain factory, not DB defaults.
// infrastructure_allowed is set here and by UpdateEventInfrastructure only:
// UpdateEvent never writes it.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.Tag,
		arg.Name,
		arg.InternalName,
		arg.AvailableFrom,
		arg.ArchiveAt,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.InfrastructureAllowed,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.AvailableFrom,
		&i.ArchiveAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.JoinPolicy,
		&i.PublishAt,
		&i.StartAt,
		&i.FinishAt,
		&i.WithdrawAt,
		&i.ManualFinishedAt,
		&i.ScoringMode,
		&i.DynamicAlgorithm,
		&i.DynamicMinPoints,
		&i.DynamicMaxPoints,
		&i.DynamicFloorAtPercent,
		&i.ForceEventScoring,
		&i.LandingDocument,
		&i.InternalName,
		&i.LifecycleConfigured,
		&i.LiveLayout,
		&i.LiveLayoutDraft,
		&i.InfrastructureAllowed,
		&i.LandingDraft,
		&i.StaticPoints,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :execrows
DELETE
FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventTagExists = `-- name: EventTagExists :one
SELECT EXISTS (SELECT 1 FROM events WHERE tag = $1)
`

// Whether any event (archived included) carries the tag. Deleted events are gone
// from the table, so this is "the tag belongs to an event that still exists".
func (q *Queries) EventTagExists(ctx context.Context, tag string) (bool, error) {
	row := q.db.QueryRow(ctx, eventTagExists, tag)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, tag, name, available_from, archive_at, updated_at, updated_by, created_at, created_by, join_policy, publish_at, start_at, finish_at, withdraw_at, manual_finished_at, scoring_mode, dynamic_algorithm, dynamic_min_points, dynamic_max_points, dynamic_floor_at_percent, force_event_scoring, landing_document, internal_name, lifecycle_configured, live_layout, live_layout_draft, infrastructure_allowed, landing_draft, static_points
FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.AvailableFrom,
		&i.ArchiveAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.JoinPolicy,
		&i.PublishAt,
		&i.StartAt,
		&i.FinishAt,
		&i.WithdrawAt,
		&i.ManualFinishedAt,
		&i.ScoringMode,
		&i.DynamicAlgorithm,
		&i.DynamicMinPoints,
		&i.DynamicMaxPoints,
		&i.DynamicFloorAtPercent,
		&i.ForceEventScoring,
		&i.LandingDocument,
		&i.InternalName,
		&i.LifecycleConfigured,
		&i.LiveLayout,
		&i.LiveLayoutDraft,
		&i.InfrastructureAllowed,
		&i.LandingDraft,
		&i.StaticPoints,
	)
	return i, err
}

const getEventScoringPopulation = `-- name: GetEventScoringPopulation :one
SELECT event_id, units_count, captured_at
FROM event_scoring_populations
WHERE event_id = $1
`

func (q *Queries) GetEventScoringPopulation(ctx context.Context, eventID uuid.UUID) (EventScoringPopulation, error) {
	row := q.db.QueryRow(ctx, getEventScoringPopulation, eventID)
	var i EventScoringPopulation
	err := row.Scan(&i.EventID, &i.UnitsCount, &i.CapturedAt)
	return i, err
}

const getLiveEventByTag = `-- name: GetLiveEventByTag :one
SELECT id, tag, name, available_from, archive_at, updated_at, updated_by, created_at, created_by, join_policy, publish_at, start_at, finish_at, withdraw_at, manual_finished_at, scoring_mode, dynamic_algorithm, dynamic_min_points, dynamic_max_points, dynamic_floor_at_percent, force_event_scoring, landing_document, internal_name, lifecycle_configured, live_layout, live_layout_draft, infrastructure_allowed, landing_draft, static_points
FROM events
WHERE tag = $1
  AND available_from <= $2::timestamptz
  AND (archive_at IS NULL OR archive_at > $2::timestamptz)
ORDER BY available_from DESC, created_at DESC
LIMIT 1
`

type GetLiveEventByTagParams struct {
	Tag string    `json:"tag"`
	Now time.Time `json:"now"`
}

// Resolve the tenant event from a subdomain tag: the single non-archived event
// sharing the tag and currently inside its platform availability window.
func (q *Queries) GetLiveEventByTag(ctx context.Context, arg GetLiveEventByTagParams) (Event, error) {
	row := q.db.QueryRow(ctx, getLiveEventByTag, arg.Tag, arg.Now)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.AvailableFrom,
		&i.ArchiveAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.JoinPolicy,
		&i.PublishAt,
		&i.StartAt,
		&i.FinishAt,
		&i.WithdrawAt,
		&i.ManualFinishedAt,
		&i.ScoringMode,
		&i.DynamicAlgorithm,
		&i.DynamicMinPoints,
		&i.DynamicMaxPoints,
		&i.DynamicFloorAtPercent,
		&i.ForceEventScoring,
		&i.LandingDocument,
		&i.InternalName,
		&i.LifecycleConfigured,
		&i.LiveLayout,
		&i.LiveLayoutDraft,
		&i.InfrastructureAllowed,
		&i.LandingDraft,
		&i.StaticPoints,
	)
	return i, err
}

const insertEventScoringPopulation = `-- name: InsertEventScoringPopulation :one
INSERT INTO event_scoring_populations (event_id, units_count, captured_at)
VALUES ($1, $2, $3)
ON CONFLICT (event_id) DO UPDATE
    SET event_id = event_scoring_populations.event_id
RETURNING event_id, units_count, captured_at
`

type InsertEventScoringPopulationParams struct {
	EventID    uuid.UUID `json:"event_id"`
	UnitsCount int32     `json:"units_count"`
	CapturedAt time.Time `json:"captured_at"`
}

// The first lifecycle transition captures the population. A retry must return
// that original immutable snapshot instead of replacing it.
func (q *Queries) InsertEventScoringPopulation(ctx context.Context, arg InsertEventScoringPopulationParams) (EventScoringPopulation, error) {
	row := q.db.QueryRow(ctx, insertEventScoringPopulation, arg.EventID, arg.UnitsCount, arg.CapturedAt)
	var i EventScoringPopulation
	err := row.Scan(&i.EventID, &i.UnitsCount, &i.CapturedAt)
	return i, err
}

const listEventsCursor = `-- name: ListEventsCursor :many
SELECT id, tag, name, available_from, archive_at, updated_at, updated_by, created_at, created_by, join_policy, publish_at, start_at, finish_at, withdraw_at, manual_finished_at, scoring_mode, dynamic_algorithm, dynamic_min_points, dynamic_max_points, dynamic_floor_at_percent, force_event_scoring, landing_document, internal_name, lifecycle_configured, live_layout, live_layout_draft, infrastructure_allowed, landing_draft, static_points
FROM events
WHERE ($1::text = '' OR tag ILIKE '%' || $1::text || '%'
    OR internal_name ILIKE '%' || $1::text || '%')
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListEventsCursorParams struct {
	Search          string    `json:"search"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	LimitVal        int32     `json:"limit_val"`
}

func (q *Queries) ListEventsCursor(ctx context.Context, arg ListEventsCursorParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsCursor,
		arg.Search,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.Name,
			&i.AvailableFrom,
			&i.ArchiveAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.JoinPolicy,
			&i.PublishAt,
			&i.StartAt,
			&i.FinishAt,
			&i.WithdrawAt,
			&i.ManualFinishedAt,
			&i.ScoringMode,
			&i.DynamicAlgorithm,
			&i.DynamicMinPoints,
			&i.DynamicMaxPoints,
			&i.DynamicFloorAtPercent,
			&i.ForceEventScoring,
			&i.LandingDocument,
			&i.InternalName,
			&i.LifecycleConfigured,
			&i.LiveLayout,
			&i.LiveLayoutDraft,
			&i.InfrastructureAllowed,
			&i.LandingDraft,
			&i.StaticPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsDueForScoringPopulation = `-- name: ListEventsDueForScoringPopulation :many
SELECT e.id AS event_id, c.participation
FROM events e
JOIN event_configs c ON c.event_id = e.id
LEFT JOIN event_scoring_populations p ON p.event_id = e.id
WHERE p.event_id IS NULL
  AND e.lifecycle_configured
  AND e.join_policy = 0
  AND e.start_at <= $1
  AND c.participation IS NOT NULL
ORDER BY e.start_at ASC
`

type ListEventsDueForScoringPopulationRow struct {
	EventID       uuid.UUID   `json:"event_id"`
	Participation pgtype.Int2 `json:"participation"`
}

func (q *Queries) ListEventsDueForScoringPopulation(ctx context.Context, now time.Time) ([]ListEventsDueForScoringPopulationRow, error) {
	rows, err := q.db.Query(ctx, listEventsDueForScoringPopulation, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsDueForScoringPopulationRow{}
	for rows.Next() {
		var i ListEventsDueForScoringPopulationRow
		if err := rows.Scan(&i.EventID, &i.Participation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsPage = `-- name: ListEventsPage :many
SELECT id, tag, name, available_from, archive_at, updated_at, updated_by, created_at, created_by, join_policy, publish_at, start_at, finish_at, withdraw_at, manual_finished_at, scoring_mode, dynamic_algorithm, dynamic_min_points, dynamic_max_points, dynamic_floor_at_percent, force_event_scoring, landing_document, internal_name, lifecycle_configured, live_layout, live_layout_draft, infrastructure_allowed, landing_draft, static_points
FROM events
WHERE ($1::text = '' OR tag ILIKE '%' || $1::text || '%'
    OR internal_name ILIKE '%' || $1::text || '%')
  AND ($2::text = '' OR
    CASE WHEN archive_at IS NOT NULL AND archive_at <= $3::timestamptz THEN 'archived'
         WHEN available_from > $3::timestamptz THEN 'not_available'
         WHEN NOT lifecycle_configured OR publish_at > $3::timestamptz THEN 'not_published'
         WHEN withdraw_at IS NOT NULL AND withdraw_at <= $3::timestamptz THEN 'withdrawn'
         WHEN start_at > $3::timestamptz THEN 'published'
         WHEN (manual_finished_at IS NOT NULL AND manual_finished_at <= $3::timestamptz)
           OR (finish_at IS NOT NULL AND finish_at <= $3::timestamptz) THEN 'finished'
         ELSE 'started' END = $2::text)
ORDER BY
  CASE WHEN $4::text = 'tag' AND $5::text = 'asc' THEN lower(tag) END ASC,
  CASE WHEN $4::text = 'tag' AND $5::text = 'desc' THEN lower(tag) END DESC,
  CASE WHEN $4::text = 'name' AND $5::text = 'asc' THEN lower(internal_name) END ASC,
  CASE WHEN $4::text = 'name' AND $5::text = 'desc' THEN lower(internal_name) END DESC,
  CASE WHEN $4::text = 'status' AND $5::text = 'asc' THEN
    CASE WHEN archive_at IS NOT NULL AND archive_at <= $3::timestamptz THEN 6
         WHEN available_from > $3::timestamptz THEN 0
         WHEN NOT lifecycle_configured OR publish_at > $3::timestamptz THEN 1
         WHEN withdraw_at IS NOT NULL AND withdraw_at <= $3::timestamptz THEN 5
         WHEN start_at > $3::timestamptz THEN 2
         WHEN (manual_finished_at IS NOT NULL AND manual_finished_at <= $3::timestamptz)
           OR (finish_at IS NOT NULL AND finish_at <= $3::timestamptz) THEN 4
         ELSE 3 END END ASC,
  CASE WHEN $4::text = 'status' AND $5::text = 'desc' THEN
    CASE WHEN archive_at IS NOT NULL AND archive_at <= $3::timestamptz THEN 6
         WHEN available_from > $3::timestamptz THEN 0
         WHEN NOT lifecycle_configured OR publish_at > $3::timestamptz THEN 1
         WHEN withdraw_at IS NOT NULL AND withdraw_at <= $3::timestamptz THEN 5
         WHEN start_at > $3::timestamptz THEN 2
         WHEN (manual_finished_at IS NOT NULL AND manual_finished_at <= $3::timestamptz)
           OR (finish_at IS NOT NULL AND finish_at <= $3::timestamptz) THEN 4
         ELSE 3 END END DESC,
  CASE WHEN $4::text = 'availableFrom' AND $5::text = 'asc' THEN available_from END ASC,
  CASE WHEN $4::text = 'availableFrom' AND $5::text = 'desc' THEN available_from END DESC,
  CASE WHEN $4::text = 'archiveAt' AND $5::text = 'asc' THEN archive_at END ASC NULLS LAST,
  CASE WHEN $4::text = 'archiveAt' AND $5::text = 'desc' THEN archive_at END DESC NULLS LAST,
  CASE WHEN $4::text = 'updated' AND $5::text = 'asc' THEN updated_at END ASC,
  CASE WHEN $4::text = 'updated' AND $5::text = 'desc' THEN updated_at END DESC,
  created_at DESC, id DESC
LIMIT $7 OFFSET $6
`

type ListEventsPageParams struct {
	Search    string    `json:"search"`
	Status    string    `json:"status"`
	Now       time.Time `json:"now"`
	SortBy    string    `json:"sort_by"`
	SortDir   string    `json:"sort_dir"`
	OffsetVal int32     `json:"offset_val"`
	LimitVal  int32     `json:"limit_val"`
}

func (q *Queries) ListEventsPage(ctx context.Context, arg ListEventsPageParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsPage,
		arg.Search,
		arg.Status,
		arg.Now,
		arg.SortBy,
		arg.SortDir,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.Name,
			&i.AvailableFrom,
			&i.ArchiveAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.JoinPolicy,
			&i.PublishAt,
			&i.StartAt,
			&i.FinishAt,
			&i.WithdrawAt,
			&i.ManualFinishedAt,
			&i.ScoringMode,
			&i.DynamicAlgorithm,
			&i.DynamicMinPoints,
			&i.DynamicMaxPoints,
			&i.DynamicFloorAtPercent,
			&i.ForceEventScoring,
			&i.LandingDocument,
			&i.InternalName,
			&i.LifecycleConfigured,
			&i.LiveLayout,
			&i.LiveLayoutDraft,
			&i.InfrastructureAllowed,
			&i.LandingDraft,
			&i.StaticPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventForTeamChange = `-- name: LockEventForTeamChange :one
SELECT id
FROM events
WHERE id = $1
FOR UPDATE
`

// Serializes team creation inside one event while the surrounding UoW is open.
func (q *Queries) LockEventForTeamChange(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockEventForTeamChange, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const updateEvent = `-- name: UpdateEvent :execrows
UPDATE events
SET tag            = $1,
    internal_name  = $2,
    available_from = $3::timestamptz,
    archive_at     = $4::timestamptz,
    updated_at     = $5,
    updated_by     = $6,
    -- Until moderators configure the lifecycle, keep internal placeholders
    -- aligned with the platform window. They are never public dates.
    publish_at     = CASE WHEN NOT lifecycle_configured
                          THEN $3::timestamptz ELSE publish_at END,
    start_at       = CASE WHEN NOT lifecycle_configured
                          THEN $3::timestamptz ELSE start_at END
WHERE id = $7
  -- Optimistic lock: 0 rows means "modified since read" (or gone).
  AND updated_at IS NOT DISTINCT FROM $8
`

type UpdateEventParams struct {
	Tag               string             `json:"tag"`
	InternalName      string             `json:"internal_name"`
	AvailableFrom     time.Time          `json:"available_from"`
	ArchiveAt         pgtype.Timestamptz `json:"archive_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         uuid.NullUUID      `json:"updated_by"`
	ID                uuid.UUID          `json:"id"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
}

// Whole-aggregate write; excludes created_at/created_by (immutable).
func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEvent,
		arg.Tag,
		arg.InternalName,
		arg.AvailableFrom,
		arg.ArchiveAt,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEventInfrastructure = `-- name: UpdateEventInfrastructure :execrows
UPDATE events
SET infrastructure_allowed = $1,
    updated_at             = $2,
    updated_by             = $3
WHERE id = $4
  AND updated_at IS NOT DISTINCT FROM $5
`

type UpdateEventInfrastructureParams struct {
	InfrastructureAllowed bool               `json:"infrastructure_allowed"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy             uuid.NullUUID      `json:"updated_by"`
	ID                    uuid.UUID          `json:"id"`
	ExpectedUpdatedAt     pgtype.Timestamptz `json:"expected_updated_at"`
}

// The platform administrator's flag; the use case refuses it after publication.
func (q *Queries) UpdateEventInfrastructure(ctx context.Context, arg UpdateEventInfrastructureParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventInfrastructure,
		arg.InfrastructureAllowed,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEventLifecycle = `-- name: UpdateEventLifecycle :execrows
UPDATE events
SET join_policy        = $1,
    lifecycle_configured = true,
    publish_at         = $2,
    start_at           = $3,
    finish_at          = $4,
    withdraw_at        = $5,
    manual_finished_at = $6,
    updated_at         = $7,
    updated_by         = $8
WHERE id = $9
  AND updated_at IS NOT DISTINCT FROM $10
`

type UpdateEventLifecycleParams struct {
	JoinPolicy        int16              `json:"join_policy"`
	PublishAt         time.Time          `json:"publish_at"`
	StartAt           time.Time          `json:"start_at"`
	FinishAt          pgtype.Timestamptz `json:"finish_at"`
	WithdrawAt        pgtype.Timestamptz `json:"withdraw_at"`
	ManualFinishedAt  pgtype.Timestamptz `json:"manual_finished_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         uuid.NullUUID      `json:"updated_by"`
	ID                uuid.UUID          `json:"id"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
}

// Canonical event-local runtime update. It deliberately does not rewrite the
// legacy availability window; that compatibility contract is retired only
// after its central-admin consumers move to this lifecycle endpoint.
func (q *Queries) UpdateEventLifecycle(ctx context.Context, arg UpdateEventLifecycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventLifecycle,
		arg.JoinPolicy,
		arg.PublishAt,
		arg.StartAt,
		arg.FinishAt,
		arg.WithdrawAt,
		arg.ManualFinishedAt,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEventPublicName = `-- name: UpdateEventPublicName :execrows
UPDATE events
SET name = $1,
    updated_at = $2,
    updated_by = $3
WHERE id = $4
  AND updated_at IS NOT DISTINCT FROM $5
`

type UpdateEventPublicNameParams struct {
	Name              string             `json:"name"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         uuid.NullUUID      `json:"updated_by"`
	ID                uuid.UUID          `json:"id"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
}

// Event managers may change only the participant-visible name.
func (q *Queries) UpdateEventPublicName(ctx context.Context, arg UpdateEventPublicNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventPublicName,
		arg.Name,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEventScoringProfile = `-- name: UpdateEventScoringProfile :execrows
UPDATE events
SET scoring_mode             = $1,
    dynamic_algorithm        = $2,
    dynamic_min_points       = $3,
    dynamic_max_points       = $4,
    dynamic_floor_at_percent = $5,
    force_event_scoring      = $6,
    static_points            = $7,
    updated_at               = $8,
    updated_by               = $9
WHERE id = $10
  AND updated_at IS NOT DISTINCT FROM $11
`

type UpdateEventScoringProfileParams struct {
	ScoringMode           int16              `json:"scoring_mode"`
	DynamicAlgorithm      int16              `json:"dynamic_algorithm"`
	DynamicMinPoints      int32              `json:"dynamic_min_points"`
	DynamicMaxPoints      int32              `json:"dynamic_max_points"`
	DynamicFloorAtPercent int32              `json:"dynamic_floor_at_percent"`
	ForceEventScoring     bool               `json:"force_event_scoring"`
	StaticPoints          pgtype.Int4        `json:"static_points"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy             uuid.NullUUID      `json:"updated_by"`
	ID                    uuid.UUID          `json:"id"`
	ExpectedUpdatedAt     pgtype.Timestamptz `json:"expected_updated_at"`
}

func (q *Queries) UpdateEventScoringProfile(ctx context.Context, arg UpdateEventScoringProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventScoringProfile,
		arg.ScoringMode,
		arg.DynamicAlgorithm,
		arg.DynamicMinPoints,
		arg.DynamicMaxPoints,
		arg.DynamicFloorAtPercent,
		arg.ForceEventScoring,
		arg.StaticPoints,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
