// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_lab_access_syncs.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const getCurrentEventLabAccessMonitoring = `-- name: GetCurrentEventLabAccessMonitoring :one
SELECT m.event_id, m.event_team_id, m.lab_group_name, m.agent_id, m.sequence, m.observed_at, m.updated_at, m.payload FROM lab_monitoring_current m JOIN event_teams t ON t.id=m.event_team_id AND t.event_id=m.event_id
WHERE m.event_team_id=$1 ORDER BY m.observed_at DESC,m.lab_group_name LIMIT 1
`

func (q *Queries) GetCurrentEventLabAccessMonitoring(ctx context.Context, eventTeamID uuid.UUID) (LabMonitoringCurrent, error) {
	row := q.db.QueryRow(ctx, getCurrentEventLabAccessMonitoring, eventTeamID)
	var i LabMonitoringCurrent
	err := row.Scan(
		&i.EventID,
		&i.EventTeamID,
		&i.LabGroupName,
		&i.AgentID,
		&i.Sequence,
		&i.ObservedAt,
		&i.UpdatedAt,
		&i.Payload,
	)
	return i, err
}

const listDirtyEventLabAccessSyncs = `-- name: ListDirtyEventLabAccessSyncs :many
WITH access_state AS (
    SELECT sync.event_team_id,
           team.event_id,
           sync.desired_revision,
           sync.applied_revision, sync.operation_id, sync.policy_fingerprint, sync.expected_group_uid, sync.access_fence_vpn_boot_id,
           sync.updated_at,
           sync.runtime_open AS applied_runtime_open,
           sync.vpn_enabled AS applied_vpn_enabled,
           sync.applied_stage_epoch,
           -- Boundaries of the event's stages that have passed: the sync wakes at each one.
           event_stage_epoch(team.event_id, now()) AS stage_epoch,
           -- After the final stand teardown no team VPN group is recreated.
           COALESCE(event.infrastructure_allowed AND rollout.torn_down_at IS NULL, false)::boolean AS vpn_enabled,
           CASE WHEN event.lifecycle_configured
               AND event.available_from <= now()
               AND (event.archive_at IS NULL OR now() < event.archive_at)
               AND event.start_at <= now()
               AND (event.finish_at IS NULL OR now() < event.finish_at)
               AND (event.manual_finished_at IS NULL OR now() < event.manual_finished_at)
               AND (event.withdraw_at IS NULL OR now() < event.withdraw_at)
               THEN true ELSE false END AS runtime_open
    FROM event_lab_access_syncs sync
    JOIN event_teams team ON team.id = sync.event_team_id
    JOIN events event ON event.id = team.event_id
    LEFT JOIN event_stand_rollouts rollout ON rollout.event_id = event.id
)
SELECT event_team_id, event_id, desired_revision, applied_revision, operation_id, policy_fingerprint, expected_group_uid, updated_at, runtime_open, vpn_enabled, stage_epoch
FROM access_state
WHERE desired_revision > applied_revision
   OR applied_runtime_open IS DISTINCT FROM runtime_open
   OR applied_vpn_enabled IS DISTINCT FROM vpn_enabled
   OR applied_stage_epoch IS DISTINCT FROM stage_epoch
   OR EXISTS (SELECT 1 FROM lab_monitoring_current m,
      jsonb_array_elements(COALESCE(m.payload->'groups','[]'::jsonb)) witness
      WHERE m.event_team_id=access_state.event_team_id AND witness->>'name'=m.lab_group_name
        AND (COALESCE(witness->'status'->>'currentVpnBootAvailable','false')<>'true'
          OR COALESCE(witness->'status'->>'currentVpnBootId','')<>access_state.access_fence_vpn_boot_id))
ORDER BY updated_at, event_team_id
LIMIT $1
`

type ListDirtyEventLabAccessSyncsRow struct {
	EventTeamID       uuid.UUID     `json:"event_team_id"`
	EventID           uuid.UUID     `json:"event_id"`
	DesiredRevision   int64         `json:"desired_revision"`
	AppliedRevision   int64         `json:"applied_revision"`
	OperationID       uuid.NullUUID `json:"operation_id"`
	PolicyFingerprint string        `json:"policy_fingerprint"`
	ExpectedGroupUid  string        `json:"expected_group_uid"`
	UpdatedAt         time.Time     `json:"updated_at"`
	RuntimeOpen       bool          `json:"runtime_open"`
	VpnEnabled        bool          `json:"vpn_enabled"`
	StageEpoch        int32         `json:"stage_epoch"`
}

func (q *Queries) ListDirtyEventLabAccessSyncs(ctx context.Context, limitVal int32) ([]ListDirtyEventLabAccessSyncsRow, error) {
	rows, err := q.db.Query(ctx, listDirtyEventLabAccessSyncs, limitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirtyEventLabAccessSyncsRow{}
	for rows.Next() {
		var i ListDirtyEventLabAccessSyncsRow
		if err := rows.Scan(
			&i.EventTeamID,
			&i.EventID,
			&i.DesiredRevision,
			&i.AppliedRevision,
			&i.OperationID,
			&i.PolicyFingerprint,
			&i.ExpectedGroupUid,
			&i.UpdatedAt,
			&i.RuntimeOpen,
			&i.VpnEnabled,
			&i.StageEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventLabAccessClients = `-- name: ListEventLabAccessClients :many
SELECT participant.user_id
FROM event_participants participant
WHERE participant.team_id = $1::uuid
  AND participant.status = 2
UNION
SELECT manager.user_id
FROM event_managers manager
JOIN event_teams team ON team.event_id = manager.event_id
WHERE team.id = $1::uuid
  AND team.moderators
  AND manager.role IN (0, 1)
ORDER BY user_id
`

// The hidden moderators team has no participant rows: its VPN clients are the
// event owner and moderators (observers are read-only and get no client).
func (q *Queries) ListEventLabAccessClients(ctx context.Context, eventTeamID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEventLabAccessClients, eventTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventLabAccessLabs = `-- name: ListEventLabAccessLabs :many
SELECT lb.lab_group_name,
       lb.lab_name,
       CASE WHEN lb.readiness = 1 AND tc.readiness = 2
 AND (lb.lab_id IS NULL OR (canonical.desired_state='Running' AND canonical.logical_closed_at IS NULL))
                AND (team.moderators
                    OR (ec.published
                        AND ee.status <> 2
                        -- A staged set is reachable only while its stage is open, or ended but returnable.
                        AND event_stage_phase(stage.opens_at, stage.closes_at, stage.returnable, now()) IN (1, 2)
                        AND NOT EXISTS (SELECT 1
                                        FROM event_challenge_prerequisites prerequisite
                                        WHERE prerequisite.challenge_id = tc.event_challenge_id
                                          AND NOT EXISTS (SELECT 1
                                                          FROM team_challenges own
                                                          JOIN team_challenge_solves solved ON solved.team_challenge_id = own.id
                                                          WHERE own.event_team_id = tc.event_team_id
                                                            AND own.event_challenge_id = prerequisite.prerequisite_challenge_id))))
           THEN true ELSE false END AS available
FROM lab_bindings lb
LEFT JOIN event_team_labs canonical ON canonical.id=lb.lab_id
JOIN team_challenges tc ON tc.event_team_id = lb.event_team_id
                       AND tc.event_challenge_id = lb.event_challenge_id
JOIN event_teams team ON team.id = lb.event_team_id
JOIN event_challenges ec ON ec.id = tc.event_challenge_id
JOIN event_exercises ee ON ee.id = ec.event_exercise_id
LEFT JOIN event_stages stage ON stage.id = ee.stage_id
WHERE lb.event_team_id = $1
  AND lb.readiness <> 3
ORDER BY lb.lab_name
`

type ListEventLabAccessLabsRow struct {
	LabGroupName string `json:"lab_group_name"`
	LabName      string `json:"lab_name"`
	Available    bool   `json:"available"`
}

// A lab is open to a team's members only when the same locks as the lab link hold: the task is published, its
// set is not detached and every prerequisite is solved by the team. The hidden moderators team tests tasks
// before they are shown, so it keeps the readiness rule alone.
func (q *Queries) ListEventLabAccessLabs(ctx context.Context, eventTeamID uuid.UUID) ([]ListEventLabAccessLabsRow, error) {
	rows, err := q.db.Query(ctx, listEventLabAccessLabs, eventTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventLabAccessLabsRow{}
	for rows.Next() {
		var i ListEventLabAccessLabsRow
		if err := rows.Scan(&i.LabGroupName, &i.LabName, &i.Available); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventLabAccessSyncApplied = `-- name: MarkEventLabAccessSyncApplied :execrows
UPDATE event_lab_access_syncs AS sync
SET applied_revision = $1,
    access_fence_vpn_boot_id=$2,
    runtime_open = $3,
    vpn_enabled = $4,
    applied_stage_epoch = $5,
    updated_at = $6
WHERE sync.event_team_id = $7
  AND sync.desired_revision = $1
  AND sync.operation_id=$8::uuid
  AND sync.policy_fingerprint=$9
  AND sync.expected_group_uid=$10
  -- Recheck the current Monitoring tuple in the acknowledgement statement.
  -- A VPN restart after the worker read must not acknowledge the old boot.
  AND EXISTS (SELECT 1 FROM lab_monitoring_current m,
      jsonb_array_elements(COALESCE(m.payload->'groups','[]'::jsonb)) g,
      jsonb_array_elements(COALESCE(m.payload->'policies','[]'::jsonb)) p
    WHERE m.event_team_id=$7 AND m.lab_group_name=$11
      AND m.observed_at BETWEEN $6::timestamptz-interval '30 seconds' AND $6::timestamptz
      AND g->>'name'=m.lab_group_name AND g->>'uid'=$10
      AND g->'status'->>'currentVpnBootAvailable'='true'
      AND g->'status'->>'currentVpnBootId'=$2
      AND CASE WHEN g->'status'->>'currentVpnBootObservedUnixMs' ~ '^[0-9]{1,16}$' THEN (g->'status'->>'currentVpnBootObservedUnixMs')::bigint ELSE 0 END
          BETWEEN (extract(epoch FROM $6::timestamptz)*1000)::bigint-30000 AND (extract(epoch FROM $6::timestamptz)*1000)::bigint
      AND p->>'labGroupName'=m.lab_group_name AND p->>'expectedGroupUid'=$10
      AND COALESCE(p->>'policyUid','')<>'' AND p->>'operationId'=$8::uuid::text
      AND p->>'desiredRevision'=$1::bigint::text
      AND p->'status'->>'operationId'=$8::uuid::text
      AND p->'status'->>'appliedRevision'=$1::bigint::text
      AND p->'status'->>'state'='Applied' AND COALESCE(p->'status'->>'lastError','')=''
      AND COALESCE(p->>'generation','0')<>'0' AND p->>'generation'=p->'status'->>'observedGeneration'
      AND p->'status'->>'vpnBootId'=$2)
  AND (sync.applied_revision < $1
       OR sync.runtime_open IS DISTINCT FROM $3
       OR sync.vpn_enabled IS DISTINCT FROM $4
       OR sync.applied_stage_epoch IS DISTINCT FROM $5
       OR sync.access_fence_vpn_boot_id IS DISTINCT FROM $2)
`

type MarkEventLabAccessSyncAppliedParams struct {
	DesiredRevision      int64     `json:"desired_revision"`
	AccessFenceVpnBootID string    `json:"access_fence_vpn_boot_id"`
	RuntimeOpen          bool      `json:"runtime_open"`
	VpnEnabled           bool      `json:"vpn_enabled"`
	StageEpoch           int32     `json:"stage_epoch"`
	UpdatedAt            time.Time `json:"updated_at"`
	EventTeamID          uuid.UUID `json:"event_team_id"`
	OperationID          uuid.UUID `json:"operation_id"`
	PolicyFingerprint    string    `json:"policy_fingerprint"`
	ExpectedGroupUid     string    `json:"expected_group_uid"`
	LabGroupName         string    `json:"lab_group_name"`
}

func (q *Queries) MarkEventLabAccessSyncApplied(ctx context.Context, arg MarkEventLabAccessSyncAppliedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEventLabAccessSyncApplied,
		arg.DesiredRevision,
		arg.AccessFenceVpnBootID,
		arg.RuntimeOpen,
		arg.VpnEnabled,
		arg.StageEpoch,
		arg.UpdatedAt,
		arg.EventTeamID,
		arg.OperationID,
		arg.PolicyFingerprint,
		arg.ExpectedGroupUid,
		arg.LabGroupName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const materializeEventLabAccessPolicy = `-- name: MaterializeEventLabAccessPolicy :one
UPDATE event_lab_access_syncs
SET desired_revision=desired_revision + CASE WHEN policy_fingerprint='' THEN 0 ELSE 1 END,
 operation_id=$1,policy_fingerprint=$2,
 expected_group_uid=$3,updated_at=$4
WHERE event_team_id=$5
 AND desired_revision=$6
 AND (policy_fingerprint<>$2 OR expected_group_uid<>$3 OR operation_id IS NULL)
RETURNING event_team_id, desired_revision, applied_revision, updated_at, runtime_open, vpn_enabled, applied_stage_epoch, operation_id, policy_fingerprint, expected_group_uid, access_fence_vpn_boot_id
`

type MaterializeEventLabAccessPolicyParams struct {
	OperationID       uuid.NullUUID `json:"operation_id"`
	PolicyFingerprint string        `json:"policy_fingerprint"`
	ExpectedGroupUid  string        `json:"expected_group_uid"`
	UpdatedAt         time.Time     `json:"updated_at"`
	EventTeamID       uuid.UUID     `json:"event_team_id"`
	ExpectedRevision  int64         `json:"expected_revision"`
}

// A Request already allocated a new revision and reset its fingerprint. A
// boundary-derived policy change allocates exactly one more revision before RPC.
func (q *Queries) MaterializeEventLabAccessPolicy(ctx context.Context, arg MaterializeEventLabAccessPolicyParams) (EventLabAccessSync, error) {
	row := q.db.QueryRow(ctx, materializeEventLabAccessPolicy,
		arg.OperationID,
		arg.PolicyFingerprint,
		arg.ExpectedGroupUid,
		arg.UpdatedAt,
		arg.EventTeamID,
		arg.ExpectedRevision,
	)
	var i EventLabAccessSync
	err := row.Scan(
		&i.EventTeamID,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.UpdatedAt,
		&i.RuntimeOpen,
		&i.VpnEnabled,
		&i.AppliedStageEpoch,
		&i.OperationID,
		&i.PolicyFingerprint,
		&i.ExpectedGroupUid,
		&i.AccessFenceVpnBootID,
	)
	return i, err
}

const requestEventLabAccessSync = `-- name: RequestEventLabAccessSync :one
INSERT INTO event_lab_access_syncs (event_team_id, desired_revision, applied_revision, updated_at)
VALUES ($1, 1, 0, $2)
ON CONFLICT (event_team_id) DO UPDATE
SET desired_revision = event_lab_access_syncs.desired_revision + 1,
    operation_id=NULL, policy_fingerprint='', expected_group_uid='',
    updated_at = EXCLUDED.updated_at
RETURNING event_team_id, desired_revision, applied_revision, updated_at, runtime_open, vpn_enabled, applied_stage_epoch, operation_id, policy_fingerprint, expected_group_uid, access_fence_vpn_boot_id
`

type RequestEventLabAccessSyncParams struct {
	EventTeamID uuid.UUID `json:"event_team_id"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) RequestEventLabAccessSync(ctx context.Context, arg RequestEventLabAccessSyncParams) (EventLabAccessSync, error) {
	row := q.db.QueryRow(ctx, requestEventLabAccessSync, arg.EventTeamID, arg.UpdatedAt)
	var i EventLabAccessSync
	err := row.Scan(
		&i.EventTeamID,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.UpdatedAt,
		&i.RuntimeOpen,
		&i.VpnEnabled,
		&i.AppliedStageEpoch,
		&i.OperationID,
		&i.PolicyFingerprint,
		&i.ExpectedGroupUid,
		&i.AccessFenceVpnBootID,
	)
	return i, err
}

const requestEventLabAccessSyncsForEvent = `-- name: RequestEventLabAccessSyncsForEvent :exec
INSERT INTO event_lab_access_syncs (event_team_id, desired_revision, applied_revision, updated_at)
SELECT id, 1, 0, $1
FROM event_teams team
WHERE team.event_id = $2
  -- The moderators team of an event without infrastructure has no VPN or
  -- Labs: it exists only for the moderators board and never syncs.
  AND (NOT team.moderators
    OR EXISTS (SELECT 1 FROM events event WHERE event.id = team.event_id AND event.infrastructure_allowed))
ON CONFLICT (event_team_id) DO UPDATE
SET desired_revision = event_lab_access_syncs.desired_revision + 1,
    operation_id=NULL, policy_fingerprint='', expected_group_uid='',
    updated_at = EXCLUDED.updated_at
`

type RequestEventLabAccessSyncsForEventParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	EventID   uuid.UUID `json:"event_id"`
}

func (q *Queries) RequestEventLabAccessSyncsForEvent(ctx context.Context, arg RequestEventLabAccessSyncsForEventParams) error {
	_, err := q.db.Exec(ctx, requestEventLabAccessSyncsForEvent, arg.UpdatedAt, arg.EventID)
	return err
}

const requestModeratorsTeamLabAccessSync = `-- name: RequestModeratorsTeamLabAccessSync :exec
INSERT INTO event_lab_access_syncs (event_team_id, desired_revision, applied_revision, updated_at)
SELECT id, 1, 0, $1
FROM event_teams team
WHERE team.event_id = $2
  AND team.moderators
  AND EXISTS (SELECT 1 FROM events event WHERE event.id = team.event_id AND event.infrastructure_allowed)
ON CONFLICT (event_team_id) DO UPDATE
SET desired_revision = event_lab_access_syncs.desired_revision + 1,
    operation_id=NULL, policy_fingerprint='', expected_group_uid='',
    updated_at = EXCLUDED.updated_at
`

type RequestModeratorsTeamLabAccessSyncParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	EventID   uuid.UUID `json:"event_id"`
}

// Manager changes alter the moderators team's VPN client set.
func (q *Queries) RequestModeratorsTeamLabAccessSync(ctx context.Context, arg RequestModeratorsTeamLabAccessSyncParams) error {
	_, err := q.db.Exec(ctx, requestModeratorsTeamLabAccessSync, arg.UpdatedAt, arg.EventID)
	return err
}
