// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_answer_files.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const attachEventAnswerFiles = `-- name: AttachEventAnswerFiles :execrows
WITH released AS (
    DELETE FROM event_answer_files f
    WHERE f.event_id = $3
      AND f.scope = $4
      AND f.owner_id = $1
      AND NOT (f.file_id = ANY($5::uuid[]))
    RETURNING f.file_id),
     unreferenced AS (
         DELETE FROM file_references r
         WHERE r.ref_type = 'event_answer_file'
           AND r.ref_id IN (SELECT file_id FROM released))
UPDATE event_answer_files f
SET owner_id    = $1,
    attached_at = COALESCE(f.attached_at, $2::timestamptz)
WHERE f.event_id = $3
  AND f.scope = $4
  AND f.file_id = ANY($5::uuid[])
`

type AttachEventAnswerFilesParams struct {
	OwnerID    uuid.NullUUID `json:"owner_id"`
	AttachedAt time.Time     `json:"attached_at"`
	EventID    uuid.UUID     `json:"event_id"`
	Scope      string        `json:"scope"`
	FileIds    []uuid.UUID   `json:"file_ids"`
}

// Gives the answer's files to their owner and releases the files the owner's
// previous answers held but the saved answer no longer references.
func (q *Queries) AttachEventAnswerFiles(ctx context.Context, arg AttachEventAnswerFilesParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachEventAnswerFiles,
		arg.OwnerID,
		arg.AttachedAt,
		arg.EventID,
		arg.Scope,
		arg.FileIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEventAnswerFile = `-- name: CreateEventAnswerFile :exec
WITH answer_file AS (
    INSERT INTO event_answer_files (file_id, event_id, scope, field_key, name, size_bytes, content_type, uploaded_by, created_at)
    VALUES ($1, $2, $3, $4, $5,
            $6, $7, $8, $9)
    RETURNING file_id)
INSERT INTO file_references (ref_type, ref_id, file_id)
SELECT 'event_answer_file', file_id, file_id FROM answer_file
`

type CreateEventAnswerFileParams struct {
	FileID      uuid.UUID `json:"file_id"`
	EventID     uuid.UUID `json:"event_id"`
	Scope       string    `json:"scope"`
	FieldKey    string    `json:"field_key"`
	Name        string    `json:"name"`
	SizeBytes   int64     `json:"size_bytes"`
	ContentType string    `json:"content_type"`
	UploadedBy  uuid.UUID `json:"uploaded_by"`
	CreatedAt   time.Time `json:"created_at"`
}

// One statement for the row and the reference that keeps the blob alive, so
// retention never sees one without the other.
func (q *Queries) CreateEventAnswerFile(ctx context.Context, arg CreateEventAnswerFileParams) error {
	_, err := q.db.Exec(ctx, createEventAnswerFile,
		arg.FileID,
		arg.EventID,
		arg.Scope,
		arg.FieldKey,
		arg.Name,
		arg.SizeBytes,
		arg.ContentType,
		arg.UploadedBy,
		arg.CreatedAt,
	)
	return err
}

const getEventAnswerFile = `-- name: GetEventAnswerFile :one
SELECT file_id, event_id, scope, field_key, name, size_bytes, content_type, uploaded_by, owner_id, attached_at, created_at FROM event_answer_files WHERE file_id = $1
`

func (q *Queries) GetEventAnswerFile(ctx context.Context, fileID uuid.UUID) (EventAnswerFile, error) {
	row := q.db.QueryRow(ctx, getEventAnswerFile, fileID)
	var i EventAnswerFile
	err := row.Scan(
		&i.FileID,
		&i.EventID,
		&i.Scope,
		&i.FieldKey,
		&i.Name,
		&i.SizeBytes,
		&i.ContentType,
		&i.UploadedBy,
		&i.OwnerID,
		&i.AttachedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEventAnswerFiles = `-- name: ListEventAnswerFiles :many
SELECT file_id, event_id, scope, field_key, name, size_bytes, content_type, uploaded_by, owner_id, attached_at, created_at FROM event_answer_files WHERE file_id = ANY($1::uuid[])
`

func (q *Queries) ListEventAnswerFiles(ctx context.Context, fileIds []uuid.UUID) ([]EventAnswerFile, error) {
	rows, err := q.db.Query(ctx, listEventAnswerFiles, fileIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventAnswerFile{}
	for rows.Next() {
		var i EventAnswerFile
		if err := rows.Scan(
			&i.FileID,
			&i.EventID,
			&i.Scope,
			&i.FieldKey,
			&i.Name,
			&i.SizeBytes,
			&i.ContentType,
			&i.UploadedBy,
			&i.OwnerID,
			&i.AttachedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
