// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_stages.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const countEventStageSets = `-- name: CountEventStageSets :one
SELECT count(*)::integer
FROM event_exercises
WHERE stage_id = $1
`

// Every set that still points at the stage (detached ones too: the foreign key would refuse the delete).
func (q *Queries) CountEventStageSets(ctx context.Context, stageID uuid.NullUUID) (int32, error) {
	row := q.db.QueryRow(ctx, countEventStageSets, stageID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createEventStage = `-- name: CreateEventStage :one
INSERT INTO event_stages (id, event_id, name, opens_at, closes_at, returnable, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8)
RETURNING id, event_id, name, opens_at, closes_at, returnable, created_at, updated_at
`

type CreateEventStageParams struct {
	ID         uuid.UUID `json:"id"`
	EventID    uuid.UUID `json:"event_id"`
	Name       string    `json:"name"`
	OpensAt    time.Time `json:"opens_at"`
	ClosesAt   time.Time `json:"closes_at"`
	Returnable bool      `json:"returnable"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) CreateEventStage(ctx context.Context, arg CreateEventStageParams) (EventStage, error) {
	row := q.db.QueryRow(ctx, createEventStage,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.OpensAt,
		arg.ClosesAt,
		arg.Returnable,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EventStage
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.OpensAt,
		&i.ClosesAt,
		&i.Returnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEventStage = `-- name: DeleteEventStage :execrows
DELETE FROM event_stages
WHERE id = $1
  AND event_id = $2
`

type DeleteEventStageParams struct {
	ID      uuid.UUID `json:"id"`
	EventID uuid.UUID `json:"event_id"`
}

func (q *Queries) DeleteEventStage(ctx context.Context, arg DeleteEventStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventStage, arg.ID, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventStage = `-- name: GetEventStage :one
SELECT id, event_id, name, opens_at, closes_at, returnable, created_at, updated_at
FROM event_stages
WHERE id = $1
  AND event_id = $2
`

type GetEventStageParams struct {
	ID      uuid.UUID `json:"id"`
	EventID uuid.UUID `json:"event_id"`
}

func (q *Queries) GetEventStage(ctx context.Context, arg GetEventStageParams) (EventStage, error) {
	row := q.db.QueryRow(ctx, getEventStage, arg.ID, arg.EventID)
	var i EventStage
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.OpensAt,
		&i.ClosesAt,
		&i.Returnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventStages = `-- name: ListEventStages :many
SELECT id, event_id, name, opens_at, closes_at, returnable, created_at, updated_at
FROM event_stages
WHERE event_id = $1
ORDER BY opens_at ASC, id ASC
`

// Order is time: stages never overlap.
func (q *Queries) ListEventStages(ctx context.Context, eventID uuid.UUID) ([]EventStage, error) {
	rows, err := q.db.Query(ctx, listEventStages, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventStage{}
	for rows.Next() {
		var i EventStage
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.OpensAt,
			&i.ClosesAt,
			&i.Returnable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventExerciseStage = `-- name: SetEventExerciseStage :one
UPDATE event_exercises
SET stage_id = $1
WHERE id = $2
  AND event_id = $3
  AND status = 0
RETURNING id, event_id, exercise_id, exercise_version_id, variant_mode, fixed_variant_index, created_at, created_by, revision, status, replaces_event_exercise_id, superseded_at, detached_at, detached_by, stage_id
`

type SetEventExerciseStageParams struct {
	StageID uuid.NullUUID `json:"stage_id"`
	ID      uuid.UUID     `json:"id"`
	EventID uuid.UUID     `json:"event_id"`
}

func (q *Queries) SetEventExerciseStage(ctx context.Context, arg SetEventExerciseStageParams) (EventExercise, error) {
	row := q.db.QueryRow(ctx, setEventExerciseStage, arg.StageID, arg.ID, arg.EventID)
	var i EventExercise
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ExerciseID,
		&i.ExerciseVersionID,
		&i.VariantMode,
		&i.FixedVariantIndex,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Revision,
		&i.Status,
		&i.ReplacesEventExerciseID,
		&i.SupersededAt,
		&i.DetachedAt,
		&i.DetachedBy,
		&i.StageID,
	)
	return i, err
}

const updateEventStage = `-- name: UpdateEventStage :one
UPDATE event_stages
SET name       = $1,
    opens_at   = $2,
    closes_at  = $3,
    returnable = $4,
    updated_at = $5
WHERE id = $6
  AND event_id = $7
RETURNING id, event_id, name, opens_at, closes_at, returnable, created_at, updated_at
`

type UpdateEventStageParams struct {
	Name       string    `json:"name"`
	OpensAt    time.Time `json:"opens_at"`
	ClosesAt   time.Time `json:"closes_at"`
	Returnable bool      `json:"returnable"`
	UpdatedAt  time.Time `json:"updated_at"`
	ID         uuid.UUID `json:"id"`
	EventID    uuid.UUID `json:"event_id"`
}

func (q *Queries) UpdateEventStage(ctx context.Context, arg UpdateEventStageParams) (EventStage, error) {
	row := q.db.QueryRow(ctx, updateEventStage,
		arg.Name,
		arg.OpensAt,
		arg.ClosesAt,
		arg.Returnable,
		arg.UpdatedAt,
		arg.ID,
		arg.EventID,
	)
	var i EventStage
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.OpensAt,
		&i.ClosesAt,
		&i.Returnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
