// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_lab_reveal.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const freezeEventLabRevealBarrier = `-- name: FreezeEventLabRevealBarrier :one
WITH candidate AS (
 SELECT ee.event_id,ee.id AS event_exercise_id,ee.revision,ec.task_reveal_mode AS mode,
 COALESCE((SELECT array_agg(team.id ORDER BY team.id) FROM event_teams team WHERE team.event_id=ee.event_id
  AND NOT team.moderators AND event_team_admitted(team.event_id,team.individual,team.admitted_manually,team.admission_locked,team.member_count) AND event_team_stand_wanted(team.event_id,team.formed_at)), '{}'::uuid[]) AS eligible_team_ids
 FROM event_exercises ee JOIN event_configs ec ON ec.event_id=ee.event_id
 WHERE ee.id=$1 AND ee.event_id=$2 AND ee.status=0
), frozen AS (
 INSERT INTO event_lab_reveal_barriers(event_id,event_exercise_id,revision,mode,eligible_team_ids,created_at)
 SELECT event_id,event_exercise_id,revision,mode,eligible_team_ids,$3 FROM candidate
 WHERE cardinality(eligible_team_ids)>0
 ON CONFLICT(event_exercise_id) DO UPDATE SET
 revision=EXCLUDED.revision,mode=EXCLUDED.mode,
 eligible_team_ids=CASE WHEN event_lab_reveal_barriers.revision<>EXCLUDED.revision OR event_lab_reveal_barriers.mode<>EXCLUDED.mode OR (event_lab_reveal_barriers.opened_at IS NULL AND cardinality(event_lab_reveal_barriers.eligible_team_ids)=0) THEN EXCLUDED.eligible_team_ids ELSE event_lab_reveal_barriers.eligible_team_ids END,
 opened_at=CASE WHEN event_lab_reveal_barriers.revision<>EXCLUDED.revision OR event_lab_reveal_barriers.mode<>EXCLUDED.mode THEN NULL ELSE event_lab_reveal_barriers.opened_at END,
 created_at=CASE WHEN event_lab_reveal_barriers.revision<>EXCLUDED.revision OR event_lab_reveal_barriers.mode<>EXCLUDED.mode OR (event_lab_reveal_barriers.opened_at IS NULL AND cardinality(event_lab_reveal_barriers.eligible_team_ids)=0) THEN EXCLUDED.created_at ELSE event_lab_reveal_barriers.created_at END
 RETURNING eligible_team_ids
)
SELECT eligible_team_ids FROM frozen
UNION ALL
SELECT b.eligible_team_ids FROM candidate c JOIN event_lab_reveal_barriers b ON b.event_exercise_id=c.event_exercise_id
 WHERE cardinality(c.eligible_team_ids)=0 AND b.revision=c.revision AND b.mode=c.mode
UNION ALL
SELECT eligible_team_ids FROM candidate WHERE cardinality(eligible_team_ids)=0
 AND NOT EXISTS(SELECT 1 FROM event_lab_reveal_barriers b WHERE b.event_exercise_id=candidate.event_exercise_id)
`

type FreezeEventLabRevealBarrierParams struct {
	EventExerciseID uuid.UUID `json:"event_exercise_id"`
	EventID         uuid.UUID `json:"event_id"`
	Now             time.Time `json:"now"`
}

// An empty eligible roster is deferred, not an immutable prepared cohort.
func (q *Queries) FreezeEventLabRevealBarrier(ctx context.Context, arg FreezeEventLabRevealBarrierParams) ([]uuid.UUID, error) {
	row := q.db.QueryRow(ctx, freezeEventLabRevealBarrier, arg.EventExerciseID, arg.EventID, arg.Now)
	var eligible_team_ids []uuid.UUID
	err := row.Scan(&eligible_team_ids)
	return eligible_team_ids, err
}

const getEventLabRevealBarrier = `-- name: GetEventLabRevealBarrier :one
SELECT event_id, event_exercise_id, revision, mode, eligible_team_ids, opened_at, created_at FROM event_lab_reveal_barriers WHERE event_id=$1 AND event_exercise_id=$2
`

type GetEventLabRevealBarrierParams struct {
	EventID         uuid.UUID `json:"event_id"`
	EventExerciseID uuid.UUID `json:"event_exercise_id"`
}

func (q *Queries) GetEventLabRevealBarrier(ctx context.Context, arg GetEventLabRevealBarrierParams) (EventLabRevealBarrier, error) {
	row := q.db.QueryRow(ctx, getEventLabRevealBarrier, arg.EventID, arg.EventExerciseID)
	var i EventLabRevealBarrier
	err := row.Scan(
		&i.EventID,
		&i.EventExerciseID,
		&i.Revision,
		&i.Mode,
		&i.EligibleTeamIds,
		&i.OpenedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateEventLabRevealBarrier = `-- name: InvalidateEventLabRevealBarrier :exec
DELETE FROM event_lab_reveal_barriers b
USING event_exercises ee,event_configs cfg
WHERE b.event_exercise_id=ee.id AND cfg.event_id=ee.event_id
 AND ee.event_id=$1 AND ee.id=$2
 AND (b.revision<>ee.revision OR b.mode<>cfg.task_reveal_mode)
`

type InvalidateEventLabRevealBarrierParams struct {
	EventID         uuid.UUID `json:"event_id"`
	EventExerciseID uuid.UUID `json:"event_exercise_id"`
}

// Authorized edits invalidate a different preparation tuple atomically. They
// never insert/freeze a cohort before the assignment preparation boundary.
func (q *Queries) InvalidateEventLabRevealBarrier(ctx context.Context, arg InvalidateEventLabRevealBarrierParams) error {
	_, err := q.db.Exec(ctx, invalidateEventLabRevealBarrier, arg.EventID, arg.EventExerciseID)
	return err
}

const isEventLabManualReachable = `-- name: IsEventLabManualReachable :one
SELECT EXISTS(SELECT 1 FROM event_lab_objectives o
 JOIN event_team_labs l ON l.id=o.lab_id
 JOIN team_challenges tc ON tc.event_team_id=l.event_team_id AND tc.event_challenge_id=o.event_challenge_id
 JOIN event_challenges ec ON ec.id=o.event_challenge_id AND ec.published
 JOIN event_exercises ee ON ee.id=ec.event_exercise_id AND ee.status<>2
 LEFT JOIN event_stages stage ON stage.id=ee.stage_id
 WHERE l.id=$1 AND tc.readiness=2 AND tc.variant_index=l.variant_index
 AND EXISTS(SELECT 1 FROM lab_bindings b WHERE b.lab_id=l.id AND b.event_team_id=l.event_team_id AND b.event_challenge_id=o.event_challenge_id AND b.generation=l.generation AND b.lab_group_name=l.lab_group_name AND b.lab_name=l.lab_name)
 AND event_stage_phase(stage.opens_at,stage.closes_at,stage.returnable,$2::timestamptz) IN (1,2)
 AND NOT EXISTS(SELECT 1 FROM event_challenge_prerequisites prerequisite WHERE prerequisite.challenge_id=tc.event_challenge_id
  AND NOT EXISTS(SELECT 1 FROM team_challenges own JOIN team_challenge_solves solved ON solved.team_challenge_id=own.id
   WHERE own.event_team_id=l.event_team_id AND own.event_challenge_id=prerequisite.prerequisite_challenge_id))) AS reachable
`

type IsEventLabManualReachableParams struct {
	LabID uuid.UUID `json:"lab_id"`
	Now   time.Time `json:"now"`
}

func (q *Queries) IsEventLabManualReachable(ctx context.Context, arg IsEventLabManualReachableParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEventLabManualReachable, arg.LabID, arg.Now)
	var reachable bool
	err := row.Scan(&reachable)
	return reachable, err
}

const listRetryableEmptyEventLabRevealBarriers = `-- name: ListRetryableEmptyEventLabRevealBarriers :many
SELECT b.event_exercise_id FROM event_lab_reveal_barriers b
JOIN event_exercises ee ON ee.id=b.event_exercise_id AND ee.event_id=b.event_id
JOIN event_configs cfg ON cfg.event_id=b.event_id
WHERE b.event_id=$1 AND b.opened_at IS NULL AND cardinality(b.eligible_team_ids)=0
 AND ee.status=0 AND b.revision=ee.revision AND b.mode=cfg.task_reveal_mode
ORDER BY b.event_exercise_id
`

func (q *Queries) ListRetryableEmptyEventLabRevealBarriers(ctx context.Context, eventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRetryableEmptyEventLabRevealBarriers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var event_exercise_id uuid.UUID
		if err := rows.Scan(&event_exercise_id); err != nil {
			return nil, err
		}
		items = append(items, event_exercise_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevealSetLabs = `-- name: ListRevealSetLabs :many
SELECT l.id, l.event_id, l.event_team_id, l.event_exercise_id, l.variant_index, l.generation, l.lab_group_name, l.lab_name, l.agent_uid, l.agent_generation, l.desired_revision, l.observed_revision, l.operation_id, l.desired_state, l.actual_state, l.runtime_ready, l.close_reason, l.logical_closed_at, l.snapshot_mode, l.snapshot_state, l.retention_until, l.protected_until, l.actual_stopped_at, l.observed_at, l.objective_count, l.materialized, l.allocation, l.failure_code, l.failure_message, l.access_fenced, l.access_fenced_at, l.access_fence_vpn_boot_id, l.next_attempt_at, l.created_at, l.updated_at, l.definition_version_id, l.definition_hash, l.retention_minutes, l.retirement_stop_target, l.retirement_state, l.retirement_observed_at, l.retirement_error, l.create_evidence, l.runtime_stage_id, l.runtime_stage_known FROM event_team_labs l
WHERE l.event_id=$1 AND l.event_exercise_id=$2
 AND l.event_team_id=ANY($3::uuid[])
 AND EXISTS(SELECT 1 FROM lab_bindings b WHERE b.lab_id=l.id AND b.generation=l.generation)
ORDER BY l.event_team_id,l.id
`

type ListRevealSetLabsParams struct {
	EventID         uuid.UUID   `json:"event_id"`
	EventExerciseID uuid.UUID   `json:"event_exercise_id"`
	TeamIds         []uuid.UUID `json:"team_ids"`
}

func (q *Queries) ListRevealSetLabs(ctx context.Context, arg ListRevealSetLabsParams) ([]EventTeamLab, error) {
	rows, err := q.db.Query(ctx, listRevealSetLabs, arg.EventID, arg.EventExerciseID, arg.TeamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventTeamLab{}
	for rows.Next() {
		var i EventTeamLab
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventTeamID,
			&i.EventExerciseID,
			&i.VariantIndex,
			&i.Generation,
			&i.LabGroupName,
			&i.LabName,
			&i.AgentUid,
			&i.AgentGeneration,
			&i.DesiredRevision,
			&i.ObservedRevision,
			&i.OperationID,
			&i.DesiredState,
			&i.ActualState,
			&i.RuntimeReady,
			&i.CloseReason,
			&i.LogicalClosedAt,
			&i.SnapshotMode,
			&i.SnapshotState,
			&i.RetentionUntil,
			&i.ProtectedUntil,
			&i.ActualStoppedAt,
			&i.ObservedAt,
			&i.ObjectiveCount,
			&i.Materialized,
			&i.Allocation,
			&i.FailureCode,
			&i.FailureMessage,
			&i.AccessFenced,
			&i.AccessFencedAt,
			&i.AccessFenceVpnBootID,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefinitionVersionID,
			&i.DefinitionHash,
			&i.RetentionMinutes,
			&i.RetirementStopTarget,
			&i.RetirementState,
			&i.RetirementObservedAt,
			&i.RetirementError,
			&i.CreateEvidence,
			&i.RuntimeStageID,
			&i.RuntimeStageKnown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openReadyEventLabRevealBarriers = `-- name: OpenReadyEventLabRevealBarriers :execrows
UPDATE event_lab_reveal_barriers barrier SET opened_at=$1
WHERE barrier.event_id=$2 AND barrier.opened_at IS NULL
AND cardinality(barrier.eligible_team_ids)>0
AND EXISTS(SELECT 1 FROM event_exercises ee JOIN event_configs cfg ON cfg.event_id=ee.event_id WHERE ee.id=barrier.event_exercise_id AND ee.revision=barrier.revision AND ee.status=0 AND cfg.task_reveal_mode=barrier.mode)
AND NOT EXISTS (
 SELECT 1 FROM unnest(barrier.eligible_team_ids) team(id)
 WHERE NOT EXISTS(SELECT 1 FROM event_team_labs l WHERE l.event_team_id=team.id AND l.event_exercise_id=barrier.event_exercise_id
  AND l.materialized AND l.agent_uid<>'' AND l.agent_generation>0 AND l.desired_state='Running' AND l.logical_closed_at IS NULL
  AND l.actual_state='Running' AND l.runtime_ready
  AND l.definition_version_id=(SELECT ee.exercise_version_id FROM event_exercises ee WHERE ee.id=barrier.event_exercise_id)
  AND EXISTS(SELECT 1 FROM lab_bindings b WHERE b.lab_id=l.id AND b.generation=l.generation AND b.lab_group_name=l.lab_group_name AND b.lab_name=l.lab_name)
  AND l.observed_revision=l.desired_revision
  AND NOT EXISTS(SELECT 1 FROM lab_bindings b WHERE b.lab_id=l.id AND b.readiness<>1))
)
`

type OpenReadyEventLabRevealBarriersParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	EventID uuid.UUID          `json:"event_id"`
}

func (q *Queries) OpenReadyEventLabRevealBarriers(ctx context.Context, arg OpenReadyEventLabRevealBarriersParams) (int64, error) {
	result, err := q.db.Exec(ctx, openReadyEventLabRevealBarriers, arg.Now, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
