// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_team_fields.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEventTeamExtraFields = `-- name: GetEventTeamExtraFields :one
SELECT extra_fields FROM event_teams
WHERE event_id = $1 AND id = $2
`

type GetEventTeamExtraFieldsParams struct {
	EventID uuid.UUID `json:"event_id"`
	TeamID  uuid.UUID `json:"team_id"`
}

func (q *Queries) GetEventTeamExtraFields(ctx context.Context, arg GetEventTeamExtraFieldsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getEventTeamExtraFields, arg.EventID, arg.TeamID)
	var extra_fields []byte
	err := row.Scan(&extra_fields)
	return extra_fields, err
}

const getEventTeamFieldConfig = `-- name: GetEventTeamFieldConfig :one
SELECT event_id, version, enabled, required, document, updated_at, require_existing, block_submissions FROM event_team_field_configs WHERE event_id = $1
`

func (q *Queries) GetEventTeamFieldConfig(ctx context.Context, eventID uuid.UUID) (EventTeamFieldConfig, error) {
	row := q.db.QueryRow(ctx, getEventTeamFieldConfig, eventID)
	var i EventTeamFieldConfig
	err := row.Scan(
		&i.EventID,
		&i.Version,
		&i.Enabled,
		&i.Required,
		&i.Document,
		&i.UpdatedAt,
		&i.RequireExisting,
		&i.BlockSubmissions,
	)
	return i, err
}

const updateEventTeamExtraFields = `-- name: UpdateEventTeamExtraFields :execrows
UPDATE event_teams SET extra_fields = $1,
    fields_missing = COALESCE($2::int, fields_missing)
WHERE event_id = $3 AND id = $4
`

type UpdateEventTeamExtraFieldsParams struct {
	ExtraFields   []byte      `json:"extra_fields"`
	FieldsMissing pgtype.Int4 `json:"fields_missing"`
	EventID       uuid.UUID   `json:"event_id"`
	TeamID        uuid.UUID   `json:"team_id"`
}

// fields_missing is written together with the answers when known (NULL keeps it).
func (q *Queries) UpdateEventTeamExtraFields(ctx context.Context, arg UpdateEventTeamExtraFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventTeamExtraFields,
		arg.ExtraFields,
		arg.FieldsMissing,
		arg.EventID,
		arg.TeamID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertEventTeamFieldConfig = `-- name: UpsertEventTeamFieldConfig :one
INSERT INTO event_team_field_configs (event_id, version, enabled, required, document, updated_at, require_existing, block_submissions)
VALUES ($1, 1, $2, $3, $4, $5,
        $6, $7)
ON CONFLICT (event_id) DO UPDATE SET
    version = event_team_field_configs.version + 1,
    enabled = EXCLUDED.enabled,
    required = EXCLUDED.required,
    document = EXCLUDED.document,
    updated_at = EXCLUDED.updated_at,
    require_existing = EXCLUDED.require_existing,
    block_submissions = EXCLUDED.block_submissions
RETURNING event_id, version, enabled, required, document, updated_at, require_existing, block_submissions
`

type UpsertEventTeamFieldConfigParams struct {
	EventID          uuid.UUID `json:"event_id"`
	Enabled          bool      `json:"enabled"`
	Required         bool      `json:"required"`
	Document         []byte    `json:"document"`
	UpdatedAt        time.Time `json:"updated_at"`
	RequireExisting  bool      `json:"require_existing"`
	BlockSubmissions bool      `json:"block_submissions"`
}

func (q *Queries) UpsertEventTeamFieldConfig(ctx context.Context, arg UpsertEventTeamFieldConfigParams) (EventTeamFieldConfig, error) {
	row := q.db.QueryRow(ctx, upsertEventTeamFieldConfig,
		arg.EventID,
		arg.Enabled,
		arg.Required,
		arg.Document,
		arg.UpdatedAt,
		arg.RequireExisting,
		arg.BlockSubmissions,
	)
	var i EventTeamFieldConfig
	err := row.Scan(
		&i.EventID,
		&i.Version,
		&i.Enabled,
		&i.Required,
		&i.Document,
		&i.UpdatedAt,
		&i.RequireExisting,
		&i.BlockSubmissions,
	)
	return i, err
}
