// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_participant_detail.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEventParticipantDetail = `-- name: GetEventParticipantDetail :one
SELECT participant.event_id, participant.user_id, participant.status, participant.created_at, participant.decided_at, participant.decided_by, participant.team_id, participant.team_role, participant.invited_by, participant.invited, participant.invited_team_id, participant.invited_to_team, participant.pseudonym, participant.invitation_sent_at, participant.invitation_expired_notified_at, participant.fields_missing,
       person.first_name,
       person.last_name,
       person.email,
       event_participant_public_name(participant.event_id, participant.user_id)::text AS display_name,
       COALESCE(team.hidden, false)::boolean                                            AS team_hidden,
       COALESCE(event_team_public_name(team.individual, team.event_id, team.captain_id, team.name), '')::text AS team_name,
       COALESCE(invited_team.name, '')::text                                            AS invited_team_name,
       presence.last_seen_at                                                            AS last_seen_at,
       COALESCE(lab.at, 'epoch'::timestamptz)::timestamptz AS last_lab_at,
       (SELECT count(*) FROM effective_challenge_attempts a
        WHERE a.event_id = participant.event_id AND a.user_id = participant.user_id)::bigint AS attempts,
       (SELECT count(DISTINCT a.team_challenge_id) FROM effective_challenge_attempts a
        WHERE a.event_id = participant.event_id AND a.user_id = participant.user_id AND a.effective_correct)::bigint AS solves
FROM event_participants participant
         JOIN users person ON person.id = participant.user_id
         LEFT JOIN event_teams team ON team.id = participant.team_id
         LEFT JOIN event_teams invited_team ON invited_team.id = participant.invited_team_id
         LEFT JOIN event_participant_presence presence ON presence.event_id = participant.event_id AND presence.user_id = participant.user_id
         CROSS JOIN LATERAL (SELECT event_user_last_lab_at(participant.event_id, participant.user_id) AS at) lab
WHERE participant.event_id = $1::uuid
  AND participant.user_id = $2::uuid
`

type GetEventParticipantDetailParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type GetEventParticipantDetailRow struct {
	EventID                     uuid.UUID          `json:"event_id"`
	UserID                      uuid.UUID          `json:"user_id"`
	Status                      int16              `json:"status"`
	CreatedAt                   time.Time          `json:"created_at"`
	DecidedAt                   pgtype.Timestamptz `json:"decided_at"`
	DecidedBy                   uuid.NullUUID      `json:"decided_by"`
	TeamID                      uuid.NullUUID      `json:"team_id"`
	TeamRole                    pgtype.Int2        `json:"team_role"`
	InvitedBy                   uuid.NullUUID      `json:"invited_by"`
	Invited                     bool               `json:"invited"`
	InvitedTeamID               uuid.NullUUID      `json:"invited_team_id"`
	InvitedToTeam               bool               `json:"invited_to_team"`
	Pseudonym                   pgtype.Text        `json:"pseudonym"`
	InvitationSentAt            pgtype.Timestamptz `json:"invitation_sent_at"`
	InvitationExpiredNotifiedAt pgtype.Timestamptz `json:"invitation_expired_notified_at"`
	FieldsMissing               int32              `json:"fields_missing"`
	FirstName                   string             `json:"first_name"`
	LastName                    string             `json:"last_name"`
	Email                       string             `json:"email"`
	DisplayName                 string             `json:"display_name"`
	TeamHidden                  bool               `json:"team_hidden"`
	TeamName                    string             `json:"team_name"`
	InvitedTeamName             string             `json:"invited_team_name"`
	LastSeenAt                  pgtype.Timestamptz `json:"last_seen_at"`
	LastLabAt                   time.Time          `json:"last_lab_at"`
	Attempts                    int64              `json:"attempts"`
	Solves                      int64              `json:"solves"`
}

// One participant for the manager's detail view: the same joined columns as
// the moderation list, the role in the team, and their own attempt figures
// (attempts submitted, distinct tasks solved). A participant of the moderators
// team is a member like any other here.
func (q *Queries) GetEventParticipantDetail(ctx context.Context, arg GetEventParticipantDetailParams) (GetEventParticipantDetailRow, error) {
	row := q.db.QueryRow(ctx, getEventParticipantDetail, arg.EventID, arg.UserID)
	var i GetEventParticipantDetailRow
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.TeamID,
		&i.TeamRole,
		&i.InvitedBy,
		&i.Invited,
		&i.InvitedTeamID,
		&i.InvitedToTeam,
		&i.Pseudonym,
		&i.InvitationSentAt,
		&i.InvitationExpiredNotifiedAt,
		&i.FieldsMissing,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DisplayName,
		&i.TeamHidden,
		&i.TeamName,
		&i.InvitedTeamName,
		&i.LastSeenAt,
		&i.LastLabAt,
		&i.Attempts,
		&i.Solves,
	)
	return i, err
}
