// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_activity.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const createEventActivity = `-- name: CreateEventActivity :exec

INSERT INTO event_activity (event_id, user_id, team_id, kind, subject_id, at, data)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateEventActivityParams struct {
	EventID   uuid.UUID     `json:"event_id"`
	UserID    uuid.NullUUID `json:"user_id"`
	TeamID    uuid.NullUUID `json:"team_id"`
	Kind      string        `json:"kind"`
	SubjectID uuid.NullUUID `json:"subject_id"`
	At        time.Time     `json:"at"`
	Data      []byte        `json:"data"`
}

// Event activity log (docs/EVENT-ANALYTICS.md §3). Append-only: rows are
// written, never updated, except the retention anonymization.
func (q *Queries) CreateEventActivity(ctx context.Context, arg CreateEventActivityParams) error {
	_, err := q.db.Exec(ctx, createEventActivity,
		arg.EventID,
		arg.UserID,
		arg.TeamID,
		arg.Kind,
		arg.SubjectID,
		arg.At,
		arg.Data,
	)
	return err
}

const createEventActivityOnce = `-- name: CreateEventActivityOnce :execrows
INSERT INTO event_activity (event_id, user_id, team_id, kind, subject_id, at, data)
SELECT $1::uuid, $2::uuid, $3::uuid, $4::text,
       $5::uuid, $6::timestamptz, $7::jsonb
WHERE NOT EXISTS (SELECT 1
                  FROM event_activity a
                  WHERE a.event_id = $1::uuid
                    AND a.subject_id = $5::uuid
                    AND a.kind = $4::text
                    AND a.user_id = $2::uuid
                    AND a.at >= $8::timestamptz)
`

type CreateEventActivityOnceParams struct {
	EventID   uuid.UUID     `json:"event_id"`
	UserID    uuid.UUID     `json:"user_id"`
	TeamID    uuid.NullUUID `json:"team_id"`
	Kind      string        `json:"kind"`
	SubjectID uuid.UUID     `json:"subject_id"`
	At        time.Time     `json:"at"`
	Data      []byte        `json:"data"`
	Since     time.Time     `json:"since"`
}

// Writes the row unless the user already has one of the same kind for the
// same subject at or after since (the dedupe window of task opens).
func (q *Queries) CreateEventActivityOnce(ctx context.Context, arg CreateEventActivityOnceParams) (int64, error) {
	result, err := q.db.Exec(ctx, createEventActivityOnce,
		arg.EventID,
		arg.UserID,
		arg.TeamID,
		arg.Kind,
		arg.SubjectID,
		arg.At,
		arg.Data,
		arg.Since,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
