// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_configs.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEventConfig = `-- name: CreateEventConfig :one
INSERT INTO event_configs (event_id, participation, registration, scoreboard_visibility,
                           participants_visibility, preview_description,
                           preview_picture, created_at, updated_at, updated_by,
                           max_team_size, min_team_size, max_teams,
                           brand_color, accent_color, accent_light, accent_dark,
                           accent_live, theme_version, allow_pseudonyms,
                           stand_deploy_lead_minutes, stand_teardown_delay_minutes,
                           show_difficulty, hints_disabled,
                           results_freeze_enabled, results_freeze_minutes, results_opened_at,
                           results_live_freeze, results_chart_enabled, results_chart_teams,
                           results_rows_limit, hint_charge_mode,
                           show_start_countdown, show_finish_countdown, finish_countdown_minutes,
                           task_reveal_mode, max_flag_attempts)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
        $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24,
        $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37) RETURNING event_id, participation, registration, scoreboard_visibility, participants_visibility, preview_description, preview_picture, created_at, updated_at, updated_by, max_team_size, min_team_size, max_teams, brand_color, accent_color, accent_light, accent_dark, accent_live, theme_version, allow_pseudonyms, stand_deploy_lead_minutes, stand_teardown_delay_minutes, show_difficulty, results_freeze_enabled, results_freeze_minutes, results_opened_at, results_live_freeze, results_chart_enabled, results_chart_teams, results_rows_limit, hint_charge_mode, hints_disabled, show_start_countdown, show_finish_countdown, finish_countdown_minutes, capacity_expected_dynamic_tasks, capacity_avg_task_cpu_millicores, capacity_avg_task_memory_bytes, task_reveal_mode, max_flag_attempts
`

type CreateEventConfigParams struct {
	EventID                   uuid.UUID          `json:"event_id"`
	Participation             pgtype.Int2        `json:"participation"`
	Registration              int16              `json:"registration"`
	ScoreboardVisibility      int16              `json:"scoreboard_visibility"`
	ParticipantsVisibility    int16              `json:"participants_visibility"`
	PreviewDescription        string             `json:"preview_description"`
	PreviewPicture            string             `json:"preview_picture"`
	CreatedAt                 time.Time          `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy                 uuid.NullUUID      `json:"updated_by"`
	MaxTeamSize               int32              `json:"max_team_size"`
	MinTeamSize               pgtype.Int4        `json:"min_team_size"`
	MaxTeams                  pgtype.Int4        `json:"max_teams"`
	BrandColor                string             `json:"brand_color"`
	AccentColor               string             `json:"accent_color"`
	AccentLight               string             `json:"accent_light"`
	AccentDark                string             `json:"accent_dark"`
	AccentLive                string             `json:"accent_live"`
	ThemeVersion              int64              `json:"theme_version"`
	AllowPseudonyms           bool               `json:"allow_pseudonyms"`
	StandDeployLeadMinutes    int32              `json:"stand_deploy_lead_minutes"`
	StandTeardownDelayMinutes int32              `json:"stand_teardown_delay_minutes"`
	ShowDifficulty            bool               `json:"show_difficulty"`
	HintsDisabled             bool               `json:"hints_disabled"`
	ResultsFreezeEnabled      bool               `json:"results_freeze_enabled"`
	ResultsFreezeMinutes      int32              `json:"results_freeze_minutes"`
	ResultsOpenedAt           pgtype.Timestamptz `json:"results_opened_at"`
	ResultsLiveFreeze         bool               `json:"results_live_freeze"`
	ResultsChartEnabled       bool               `json:"results_chart_enabled"`
	ResultsChartTeams         int32              `json:"results_chart_teams"`
	ResultsRowsLimit          pgtype.Int4        `json:"results_rows_limit"`
	HintChargeMode            int16              `json:"hint_charge_mode"`
	ShowStartCountdown        bool               `json:"show_start_countdown"`
	ShowFinishCountdown       bool               `json:"show_finish_countdown"`
	FinishCountdownMinutes    int32              `json:"finish_countdown_minutes"`
	TaskRevealMode            string             `json:"task_reveal_mode"`
	MaxFlagAttempts           pgtype.Int4        `json:"max_flag_attempts"`
}

// Timestamps come from the domain factory. participation is null at creation.
func (q *Queries) CreateEventConfig(ctx context.Context, arg CreateEventConfigParams) (EventConfig, error) {
	row := q.db.QueryRow(ctx, createEventConfig,
		arg.EventID,
		arg.Participation,
		arg.Registration,
		arg.ScoreboardVisibility,
		arg.ParticipantsVisibility,
		arg.PreviewDescription,
		arg.PreviewPicture,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.MaxTeamSize,
		arg.MinTeamSize,
		arg.MaxTeams,
		arg.BrandColor,
		arg.AccentColor,
		arg.AccentLight,
		arg.AccentDark,
		arg.AccentLive,
		arg.ThemeVersion,
		arg.AllowPseudonyms,
		arg.StandDeployLeadMinutes,
		arg.StandTeardownDelayMinutes,
		arg.ShowDifficulty,
		arg.HintsDisabled,
		arg.ResultsFreezeEnabled,
		arg.ResultsFreezeMinutes,
		arg.ResultsOpenedAt,
		arg.ResultsLiveFreeze,
		arg.ResultsChartEnabled,
		arg.ResultsChartTeams,
		arg.ResultsRowsLimit,
		arg.HintChargeMode,
		arg.ShowStartCountdown,
		arg.ShowFinishCountdown,
		arg.FinishCountdownMinutes,
		arg.TaskRevealMode,
		arg.MaxFlagAttempts,
	)
	var i EventConfig
	err := row.Scan(
		&i.EventID,
		&i.Participation,
		&i.Registration,
		&i.ScoreboardVisibility,
		&i.ParticipantsVisibility,
		&i.PreviewDescription,
		&i.PreviewPicture,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.MaxTeamSize,
		&i.MinTeamSize,
		&i.MaxTeams,
		&i.BrandColor,
		&i.AccentColor,
		&i.AccentLight,
		&i.AccentDark,
		&i.AccentLive,
		&i.ThemeVersion,
		&i.AllowPseudonyms,
		&i.StandDeployLeadMinutes,
		&i.StandTeardownDelayMinutes,
		&i.ShowDifficulty,
		&i.ResultsFreezeEnabled,
		&i.ResultsFreezeMinutes,
		&i.ResultsOpenedAt,
		&i.ResultsLiveFreeze,
		&i.ResultsChartEnabled,
		&i.ResultsChartTeams,
		&i.ResultsRowsLimit,
		&i.HintChargeMode,
		&i.HintsDisabled,
		&i.ShowStartCountdown,
		&i.ShowFinishCountdown,
		&i.FinishCountdownMinutes,
		&i.CapacityExpectedDynamicTasks,
		&i.CapacityAvgTaskCpuMillicores,
		&i.CapacityAvgTaskMemoryBytes,
		&i.TaskRevealMode,
		&i.MaxFlagAttempts,
	)
	return i, err
}

const getEventCapacityEstimate = `-- name: GetEventCapacityEstimate :one
SELECT capacity_expected_dynamic_tasks, capacity_avg_task_cpu_millicores, capacity_avg_task_memory_bytes
FROM event_configs
WHERE event_id = $1
`

type GetEventCapacityEstimateRow struct {
	CapacityExpectedDynamicTasks int32 `json:"capacity_expected_dynamic_tasks"`
	CapacityAvgTaskCpuMillicores int32 `json:"capacity_avg_task_cpu_millicores"`
	CapacityAvgTaskMemoryBytes   int64 `json:"capacity_avg_task_memory_bytes"`
}

// The organizer's estimate of tasks that are not final yet. A narrow pair of queries: the
// whole-aggregate write above never touches these columns.
func (q *Queries) GetEventCapacityEstimate(ctx context.Context, eventID uuid.UUID) (GetEventCapacityEstimateRow, error) {
	row := q.db.QueryRow(ctx, getEventCapacityEstimate, eventID)
	var i GetEventCapacityEstimateRow
	err := row.Scan(&i.CapacityExpectedDynamicTasks, &i.CapacityAvgTaskCpuMillicores, &i.CapacityAvgTaskMemoryBytes)
	return i, err
}

const getEventConfig = `-- name: GetEventConfig :one
SELECT event_id, participation, registration, scoreboard_visibility, participants_visibility, preview_description, preview_picture, created_at, updated_at, updated_by, max_team_size, min_team_size, max_teams, brand_color, accent_color, accent_light, accent_dark, accent_live, theme_version, allow_pseudonyms, stand_deploy_lead_minutes, stand_teardown_delay_minutes, show_difficulty, results_freeze_enabled, results_freeze_minutes, results_opened_at, results_live_freeze, results_chart_enabled, results_chart_teams, results_rows_limit, hint_charge_mode, hints_disabled, show_start_countdown, show_finish_countdown, finish_countdown_minutes, capacity_expected_dynamic_tasks, capacity_avg_task_cpu_millicores, capacity_avg_task_memory_bytes, task_reveal_mode, max_flag_attempts
FROM event_configs
WHERE event_id = $1
`

func (q *Queries) GetEventConfig(ctx context.Context, eventID uuid.UUID) (EventConfig, error) {
	row := q.db.QueryRow(ctx, getEventConfig, eventID)
	var i EventConfig
	err := row.Scan(
		&i.EventID,
		&i.Participation,
		&i.Registration,
		&i.ScoreboardVisibility,
		&i.ParticipantsVisibility,
		&i.PreviewDescription,
		&i.PreviewPicture,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.MaxTeamSize,
		&i.MinTeamSize,
		&i.MaxTeams,
		&i.BrandColor,
		&i.AccentColor,
		&i.AccentLight,
		&i.AccentDark,
		&i.AccentLive,
		&i.ThemeVersion,
		&i.AllowPseudonyms,
		&i.StandDeployLeadMinutes,
		&i.StandTeardownDelayMinutes,
		&i.ShowDifficulty,
		&i.ResultsFreezeEnabled,
		&i.ResultsFreezeMinutes,
		&i.ResultsOpenedAt,
		&i.ResultsLiveFreeze,
		&i.ResultsChartEnabled,
		&i.ResultsChartTeams,
		&i.ResultsRowsLimit,
		&i.HintChargeMode,
		&i.HintsDisabled,
		&i.ShowStartCountdown,
		&i.ShowFinishCountdown,
		&i.FinishCountdownMinutes,
		&i.CapacityExpectedDynamicTasks,
		&i.CapacityAvgTaskCpuMillicores,
		&i.CapacityAvgTaskMemoryBytes,
		&i.TaskRevealMode,
		&i.MaxFlagAttempts,
	)
	return i, err
}

const setEventCapacityEstimate = `-- name: SetEventCapacityEstimate :execrows
UPDATE event_configs
SET capacity_expected_dynamic_tasks  = $1,
    capacity_avg_task_cpu_millicores = $2,
    capacity_avg_task_memory_bytes   = $3
WHERE event_id = $4
`

type SetEventCapacityEstimateParams struct {
	ExpectedDynamicTasks int32     `json:"expected_dynamic_tasks"`
	AvgTaskCpuMillicores int32     `json:"avg_task_cpu_millicores"`
	AvgTaskMemoryBytes   int64     `json:"avg_task_memory_bytes"`
	EventID              uuid.UUID `json:"event_id"`
}

func (q *Queries) SetEventCapacityEstimate(ctx context.Context, arg SetEventCapacityEstimateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEventCapacityEstimate,
		arg.ExpectedDynamicTasks,
		arg.AvgTaskCpuMillicores,
		arg.AvgTaskMemoryBytes,
		arg.EventID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEventConfig = `-- name: UpdateEventConfig :execrows
UPDATE event_configs
SET participation            = $2,
    registration             = $3,
    scoreboard_visibility    = $4,
    participants_visibility  = $5,
    preview_description      = $6,
    preview_picture          = $7,
    updated_at               = $8,
    updated_by               = $9,
    max_team_size            = $10,
    min_team_size            = $11,
    max_teams                = $12,
    brand_color             = $13,
    accent_color            = $14,
    accent_light            = $15,
    accent_dark             = $16,
    accent_live             = $17,
    theme_version           = $18,
    allow_pseudonyms        = $19,
    stand_deploy_lead_minutes    = $20,
    stand_teardown_delay_minutes = $21,
    show_difficulty              = $22,
    hints_disabled                   = $23,
    results_freeze_enabled       = $24,
    results_freeze_minutes       = $25,
    results_opened_at            = $26,
    results_live_freeze          = $27,
    results_chart_enabled        = $28,
    results_chart_teams          = $29,
    results_rows_limit           = $30,
    hint_charge_mode             = $31,
    show_start_countdown         = $32,
    show_finish_countdown        = $33,
    finish_countdown_minutes     = $34,
    task_reveal_mode             = $35,
    max_flag_attempts            = $36
WHERE event_id = $1
  AND updated_at IS NOT DISTINCT FROM $37
`

type UpdateEventConfigParams struct {
	EventID                   uuid.UUID          `json:"event_id"`
	Participation             pgtype.Int2        `json:"participation"`
	Registration              int16              `json:"registration"`
	ScoreboardVisibility      int16              `json:"scoreboard_visibility"`
	ParticipantsVisibility    int16              `json:"participants_visibility"`
	PreviewDescription        string             `json:"preview_description"`
	PreviewPicture            string             `json:"preview_picture"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy                 uuid.NullUUID      `json:"updated_by"`
	MaxTeamSize               int32              `json:"max_team_size"`
	MinTeamSize               pgtype.Int4        `json:"min_team_size"`
	MaxTeams                  pgtype.Int4        `json:"max_teams"`
	BrandColor                string             `json:"brand_color"`
	AccentColor               string             `json:"accent_color"`
	AccentLight               string             `json:"accent_light"`
	AccentDark                string             `json:"accent_dark"`
	AccentLive                string             `json:"accent_live"`
	ThemeVersion              int64              `json:"theme_version"`
	AllowPseudonyms           bool               `json:"allow_pseudonyms"`
	StandDeployLeadMinutes    int32              `json:"stand_deploy_lead_minutes"`
	StandTeardownDelayMinutes int32              `json:"stand_teardown_delay_minutes"`
	ShowDifficulty            bool               `json:"show_difficulty"`
	HintsDisabled             bool               `json:"hints_disabled"`
	ResultsFreezeEnabled      bool               `json:"results_freeze_enabled"`
	ResultsFreezeMinutes      int32              `json:"results_freeze_minutes"`
	ResultsOpenedAt           pgtype.Timestamptz `json:"results_opened_at"`
	ResultsLiveFreeze         bool               `json:"results_live_freeze"`
	ResultsChartEnabled       bool               `json:"results_chart_enabled"`
	ResultsChartTeams         int32              `json:"results_chart_teams"`
	ResultsRowsLimit          pgtype.Int4        `json:"results_rows_limit"`
	HintChargeMode            int16              `json:"hint_charge_mode"`
	ShowStartCountdown        bool               `json:"show_start_countdown"`
	ShowFinishCountdown       bool               `json:"show_finish_countdown"`
	FinishCountdownMinutes    int32              `json:"finish_countdown_minutes"`
	TaskRevealMode            string             `json:"task_reveal_mode"`
	MaxFlagAttempts           pgtype.Int4        `json:"max_flag_attempts"`
	ExpectedUpdatedAt         pgtype.Timestamptz `json:"expected_updated_at"`
}

// Whole-aggregate write; excludes event_id/created_at (immutable). Optimistic
// lock on updated_at (a fresh config from CreateEventConfig has updated_at set
// to created_at, so the lock has a non-null baseline from the first write).
func (q *Queries) UpdateEventConfig(ctx context.Context, arg UpdateEventConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventConfig,
		arg.EventID,
		arg.Participation,
		arg.Registration,
		arg.ScoreboardVisibility,
		arg.ParticipantsVisibility,
		arg.PreviewDescription,
		arg.PreviewPicture,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.MaxTeamSize,
		arg.MinTeamSize,
		arg.MaxTeams,
		arg.BrandColor,
		arg.AccentColor,
		arg.AccentLight,
		arg.AccentDark,
		arg.AccentLive,
		arg.ThemeVersion,
		arg.AllowPseudonyms,
		arg.StandDeployLeadMinutes,
		arg.StandTeardownDelayMinutes,
		arg.ShowDifficulty,
		arg.HintsDisabled,
		arg.ResultsFreezeEnabled,
		arg.ResultsFreezeMinutes,
		arg.ResultsOpenedAt,
		arg.ResultsLiveFreeze,
		arg.ResultsChartEnabled,
		arg.ResultsChartTeams,
		arg.ResultsRowsLimit,
		arg.HintChargeMode,
		arg.ShowStartCountdown,
		arg.ShowFinishCountdown,
		arg.FinishCountdownMinutes,
		arg.TaskRevealMode,
		arg.MaxFlagAttempts,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
