// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_challenge_prerequisites.sql

package postgres

import (
	"context"

	"github.com/gofrs/uuid"
)

const createEventChallengePrerequisite = `-- name: CreateEventChallengePrerequisite :exec
INSERT INTO event_challenge_prerequisites (challenge_id, prerequisite_challenge_id)
VALUES ($1, $2)
`

type CreateEventChallengePrerequisiteParams struct {
	ChallengeID             uuid.UUID `json:"challenge_id"`
	PrerequisiteChallengeID uuid.UUID `json:"prerequisite_challenge_id"`
}

func (q *Queries) CreateEventChallengePrerequisite(ctx context.Context, arg CreateEventChallengePrerequisiteParams) error {
	_, err := q.db.Exec(ctx, createEventChallengePrerequisite, arg.ChallengeID, arg.PrerequisiteChallengeID)
	return err
}

const deleteEventChallengePrerequisites = `-- name: DeleteEventChallengePrerequisites :exec
DELETE FROM event_challenge_prerequisites
WHERE challenge_id = $1
`

func (q *Queries) DeleteEventChallengePrerequisites(ctx context.Context, challengeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventChallengePrerequisites, challengeID)
	return err
}

const listEventChallengePrerequisites = `-- name: ListEventChallengePrerequisites :many
SELECT prerequisite_challenge_id
FROM event_challenge_prerequisites
WHERE challenge_id = $1
ORDER BY prerequisite_challenge_id ASC
`

func (q *Queries) ListEventChallengePrerequisites(ctx context.Context, challengeID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEventChallengePrerequisites, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var prerequisite_challenge_id uuid.UUID
		if err := rows.Scan(&prerequisite_challenge_id); err != nil {
			return nil, err
		}
		items = append(items, prerequisite_challenge_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
