// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_analytics_usage.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listEventUsageLiveHandshakes = `-- name: ListEventUsageLiveHandshakes :many
SELECT m.event_team_id                                                                   AS team_id,
       COALESCE(c ->> 'name', '')::text                                                   AS client_name,
       COALESCE((c -> 'status' -> 'statistics' ->> 'lastHandshakeUnix')::bigint, 0)::bigint AS handshake_unix,
       m.updated_at
FROM lab_monitoring_current m
CROSS JOIN LATERAL jsonb_array_elements(
        CASE WHEN jsonb_typeof(m.payload -> 'clients') = 'array' THEN m.payload -> 'clients' ELSE '[]'::jsonb END) c
WHERE m.event_id = $1
`

type ListEventUsageLiveHandshakesRow struct {
	TeamID        uuid.UUID `json:"team_id"`
	ClientName    string    `json:"client_name"`
	HandshakeUnix int64     `json:"handshake_unix"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// The current last handshake of every peer of the event, from the merged live
// state (not from the rolled-up sessions, which lag by up to a minute).
func (q *Queries) ListEventUsageLiveHandshakes(ctx context.Context, eventID uuid.UUID) ([]ListEventUsageLiveHandshakesRow, error) {
	rows, err := q.db.Query(ctx, listEventUsageLiveHandshakes, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventUsageLiveHandshakesRow{}
	for rows.Next() {
		var i ListEventUsageLiveHandshakesRow
		if err := rows.Scan(
			&i.TeamID,
			&i.ClientName,
			&i.HandshakeUnix,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventUsageSessions = `-- name: ListEventUsageSessions :many
SELECT x.user_id, x.started_at, x.ended_at, x.rx_bytes, x.tx_bytes
FROM (
    SELECT s.user_id::uuid AS user_id, s.started_at, s.ended_at,
           (s.rx_max - s.rx_min)::bigint AS rx_bytes,
           (s.tx_max - s.tx_min)::bigint AS tx_bytes,
           row_number() OVER (PARTITION BY s.user_id ORDER BY s.started_at DESC) AS n
    FROM event_vpn_sessions s
    WHERE s.event_id = $1
      AND s.user_id IS NOT NULL
      AND s.ended_at >= $2::timestamptz
      AND s.started_at < $3::timestamptz
) x
WHERE x.n <= $4::int
ORDER BY x.user_id, x.started_at DESC
`

type ListEventUsageSessionsParams struct {
	EventID      uuid.UUID `json:"event_id"`
	FromAt       time.Time `json:"from_at"`
	ToAt         time.Time `json:"to_at"`
	SessionLimit int32     `json:"session_limit"`
}

type ListEventUsageSessionsRow struct {
	UserID    uuid.UUID `json:"user_id"`
	StartedAt time.Time `json:"started_at"`
	EndedAt   time.Time `json:"ended_at"`
	RxBytes   int64     `json:"rx_bytes"`
	TxBytes   int64     `json:"tx_bytes"`
}

// The latest sessions of every participant over the period, newest first, at
// most session_limit per participant.
func (q *Queries) ListEventUsageSessions(ctx context.Context, arg ListEventUsageSessionsParams) ([]ListEventUsageSessionsRow, error) {
	rows, err := q.db.Query(ctx, listEventUsageSessions,
		arg.EventID,
		arg.FromAt,
		arg.ToAt,
		arg.SessionLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventUsageSessionsRow{}
	for rows.Next() {
		var i ListEventUsageSessionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.RxBytes,
			&i.TxBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventUsageTouches = `-- name: ListEventUsageTouches :many
SELECT t.user_id::uuid                                   AS user_id,
       t.event_challenge_id,
       COALESCE(ec.snapshot ->> 'name', '')::text        AS challenge_name,
       t.surface::text                                   AS surface,
       t.attempts_count,
       t.lab_initiated_attempts_count,
       t.bytes_in,
       t.bytes_out,
       t.first_seen_at,
       t.last_seen_at
FROM event_lab_touches t
LEFT JOIN event_challenges ec ON ec.id = t.event_challenge_id
WHERE t.event_id = $1
  AND t.user_id IS NOT NULL
ORDER BY t.user_id, challenge_name, t.surface
`

type ListEventUsageTouchesRow struct {
	UserID                    uuid.UUID          `json:"user_id"`
	EventChallengeID          uuid.UUID          `json:"event_challenge_id"`
	ChallengeName             string             `json:"challenge_name"`
	Surface                   string             `json:"surface"`
	AttemptsCount             int64              `json:"attempts_count"`
	LabInitiatedAttemptsCount int64              `json:"lab_initiated_attempts_count"`
	BytesIn                   int64              `json:"bytes_in"`
	BytesOut                  int64              `json:"bytes_out"`
	FirstSeenAt               pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt                pgtype.Timestamptz `json:"last_seen_at"`
}

// Lab access per participant, task and access type (vpn or proxy): the
// collector's cumulative counters. They carry no time series, so they cover
// the whole event, not the period.
func (q *Queries) ListEventUsageTouches(ctx context.Context, eventID uuid.UUID) ([]ListEventUsageTouchesRow, error) {
	rows, err := q.db.Query(ctx, listEventUsageTouches, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventUsageTouchesRow{}
	for rows.Next() {
		var i ListEventUsageTouchesRow
		if err := rows.Scan(
			&i.UserID,
			&i.EventChallengeID,
			&i.ChallengeName,
			&i.Surface,
			&i.AttemptsCount,
			&i.LabInitiatedAttemptsCount,
			&i.BytesIn,
			&i.BytesOut,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventUsageUsers = `-- name: ListEventUsageUsers :many

SELECT p.user_id,
       t.id                                                                         AS team_id,
       event_team_public_name(t.individual, t.event_id, t.captain_id, t.name)::text AS team_name,
       COALESCE(NULLIF(btrim(concat_ws(' ', u.first_name, u.last_name)), ''), p.pseudonym, '')::text AS user_name,
       presence.last_seen_at                                                        AS last_seen_at,
       COALESCE(lab.at, 'epoch'::timestamptz)::timestamptz                          AS last_lab_at
FROM event_participants p
JOIN event_teams t ON t.id = p.team_id AND NOT t.moderators
LEFT JOIN users u ON u.id = p.user_id
LEFT JOIN event_participant_presence presence ON presence.event_id = p.event_id AND presence.user_id = p.user_id
CROSS JOIN LATERAL (SELECT event_user_last_lab_at(p.event_id, p.user_id) AS at) lab
WHERE p.event_id = $1
  AND p.status = 2
  AND ($2::uuid IS NULL OR t.id = $2::uuid)
ORDER BY t.id, p.user_id
`

type ListEventUsageUsersParams struct {
	EventID uuid.UUID     `json:"event_id"`
	TeamID  uuid.NullUUID `json:"team_id"`
}

type ListEventUsageUsersRow struct {
	UserID     uuid.UUID          `json:"user_id"`
	TeamID     uuid.UUID          `json:"team_id"`
	TeamName   string             `json:"team_name"`
	UserName   string             `json:"user_name"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	LastLabAt  time.Time          `json:"last_lab_at"`
}

// Event analytics, «Використання»: per participant VPN connection state and
// lab access over the VPN and the web proxy. Counts and times only, never an
// address. The moderators team is never counted.
// Every participant of a team (outside the moderators team) with the name an
// organizer sees. A deleted or purged account keeps an empty name.
func (q *Queries) ListEventUsageUsers(ctx context.Context, arg ListEventUsageUsersParams) ([]ListEventUsageUsersRow, error) {
	rows, err := q.db.Query(ctx, listEventUsageUsers, arg.EventID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventUsageUsersRow{}
	for rows.Next() {
		var i ListEventUsageUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.TeamID,
			&i.TeamName,
			&i.UserName,
			&i.LastSeenAt,
			&i.LastLabAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventUsageVPN = `-- name: ListEventUsageVPN :many
SELECT s.user_id::uuid                                                        AS user_id,
       count(*)::bigint                                                       AS sessions,
       COALESCE(sum(extract(epoch FROM s.ended_at - s.started_at)), 0)::bigint AS seconds,
       COALESCE(sum(s.rx_max - s.rx_min), 0)::bigint                          AS rx_bytes,
       COALESCE(sum(s.tx_max - s.tx_min), 0)::bigint                          AS tx_bytes,
       min(s.started_at)::timestamptz                                         AS first_at,
       max(s.ended_at)::timestamptz                                           AS last_at
FROM event_vpn_sessions s
WHERE s.event_id = $1
  AND s.user_id IS NOT NULL
  AND s.ended_at >= $2::timestamptz
  AND s.started_at < $3::timestamptz
GROUP BY s.user_id
`

type ListEventUsageVPNParams struct {
	EventID uuid.UUID `json:"event_id"`
	FromAt  time.Time `json:"from_at"`
	ToAt    time.Time `json:"to_at"`
}

type ListEventUsageVPNRow struct {
	UserID   uuid.UUID `json:"user_id"`
	Sessions int64     `json:"sessions"`
	Seconds  int64     `json:"seconds"`
	RxBytes  int64     `json:"rx_bytes"`
	TxBytes  int64     `json:"tx_bytes"`
	FirstAt  time.Time `json:"first_at"`
	LastAt   time.Time `json:"last_at"`
}

// VPN sessions per participant over the sessions overlapping the period.
func (q *Queries) ListEventUsageVPN(ctx context.Context, arg ListEventUsageVPNParams) ([]ListEventUsageVPNRow, error) {
	rows, err := q.db.Query(ctx, listEventUsageVPN, arg.EventID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventUsageVPNRow{}
	for rows.Next() {
		var i ListEventUsageVPNRow
		if err := rows.Scan(
			&i.UserID,
			&i.Sessions,
			&i.Seconds,
			&i.RxBytes,
			&i.TxBytes,
			&i.FirstAt,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
