// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_stands.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEventTeamStand = `-- name: CreateEventTeamStand :execrows
INSERT INTO event_team_stands (event_team_id, event_id, status, reason, generation, created_at, updated_at, status_changed_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $6, $6)
ON CONFLICT (event_team_id) DO NOTHING
`

type CreateEventTeamStandParams struct {
	EventTeamID uuid.UUID   `json:"event_team_id"`
	EventID     uuid.UUID   `json:"event_id"`
	Status      int16       `json:"status"`
	Reason      pgtype.Text `json:"reason"`
	Generation  int32       `json:"generation"`
	Now         time.Time   `json:"now"`
}

func (q *Queries) CreateEventTeamStand(ctx context.Context, arg CreateEventTeamStandParams) (int64, error) {
	result, err := q.db.Exec(ctx, createEventTeamStand,
		arg.EventTeamID,
		arg.EventID,
		arg.Status,
		arg.Reason,
		arg.Generation,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createModeratorsTeam = `-- name: CreateModeratorsTeam :exec
INSERT INTO event_teams (id, event_id, name, join_code, captain_id, hidden, member_count, created_at, updated_at,
                         individual, admitted_manually, admission_locked, moderators, formed_at)
SELECT $1, manager.event_id, $2, $3, manager.user_id, true, 1,
       $4, $4, false, true, true, true, $4
FROM event_managers manager
WHERE manager.event_id = $5
  AND manager.role = 0
ORDER BY manager.created_at, manager.user_id
LIMIT 1
ON CONFLICT DO NOTHING
`

type CreateModeratorsTeamParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	JoinCode string    `json:"join_code"`
	Now      time.Time `json:"now"`
	EventID  uuid.UUID `json:"event_id"`
}

// The hidden moderators team: captained by the event owner, admitted and
// locked, excluded from every participant, scoring and team-management read.
func (q *Queries) CreateModeratorsTeam(ctx context.Context, arg CreateModeratorsTeamParams) error {
	_, err := q.db.Exec(ctx, createModeratorsTeam,
		arg.ID,
		arg.Name,
		arg.JoinCode,
		arg.Now,
		arg.EventID,
	)
	return err
}

const getEventStandRollout = `-- name: GetEventStandRollout :one
SELECT event_id, opened_at, torn_down_at, updated_at
FROM event_stand_rollouts
WHERE event_id = $1
`

func (q *Queries) GetEventStandRollout(ctx context.Context, eventID uuid.UUID) (EventStandRollout, error) {
	row := q.db.QueryRow(ctx, getEventStandRollout, eventID)
	var i EventStandRollout
	err := row.Scan(
		&i.EventID,
		&i.OpenedAt,
		&i.TornDownAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventTeamStand = `-- name: GetEventTeamStand :one
SELECT event_team_id, event_id, status, reason, generation, created_at, updated_at, status_changed_at
FROM event_team_stands
WHERE event_team_id = $1
`

func (q *Queries) GetEventTeamStand(ctx context.Context, eventTeamID uuid.UUID) (EventTeamStand, error) {
	row := q.db.QueryRow(ctx, getEventTeamStand, eventTeamID)
	var i EventTeamStand
	err := row.Scan(
		&i.EventTeamID,
		&i.EventID,
		&i.Status,
		&i.Reason,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusChangedAt,
	)
	return i, err
}

const getModeratorsTeam = `-- name: GetModeratorsTeam :one
SELECT id, event_id, name, join_code, captain_id, hidden, member_count, created_at, updated_at, extra_fields, individual, admitted_manually, admission_locked, moderators, join_code_expires_at, fields_missing, formed_at, formed_by
FROM event_teams
WHERE event_id = $1
  AND moderators
`

func (q *Queries) GetModeratorsTeam(ctx context.Context, eventID uuid.UUID) (EventTeam, error) {
	row := q.db.QueryRow(ctx, getModeratorsTeam, eventID)
	var i EventTeam
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.JoinCode,
		&i.CaptainID,
		&i.Hidden,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExtraFields,
		&i.Individual,
		&i.AdmittedManually,
		&i.AdmissionLocked,
		&i.Moderators,
		&i.JoinCodeExpiresAt,
		&i.FieldsMissing,
		&i.FormedAt,
		&i.FormedBy,
	)
	return i, err
}

const getStandTeam = `-- name: GetStandTeam :one
SELECT id, event_id, name, join_code, captain_id, hidden, member_count, created_at, updated_at, extra_fields, individual, admitted_manually, admission_locked, moderators, join_code_expires_at, fields_missing, formed_at, formed_by
FROM event_teams
WHERE id = $1
  AND event_id = $2
`

type GetStandTeamParams struct {
	ID      uuid.UUID `json:"id"`
	EventID uuid.UUID `json:"event_id"`
}

// Any team of the event, including the moderators team.
func (q *Queries) GetStandTeam(ctx context.Context, arg GetStandTeamParams) (EventTeam, error) {
	row := q.db.QueryRow(ctx, getStandTeam, arg.ID, arg.EventID)
	var i EventTeam
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.JoinCode,
		&i.CaptainID,
		&i.Hidden,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExtraFields,
		&i.Individual,
		&i.AdmittedManually,
		&i.AdmissionLocked,
		&i.Moderators,
		&i.JoinCodeExpiresAt,
		&i.FieldsMissing,
		&i.FormedAt,
		&i.FormedBy,
	)
	return i, err
}

const listEventStandLabs = `-- name: ListEventStandLabs :many
SELECT lb.event_team_id, lb.event_challenge_id, lb.readiness, lb.failure_reason,
       COALESCE(challenge.snapshot->>'name', '')::text AS challenge_name
FROM lab_bindings lb
JOIN event_challenges challenge ON challenge.id = lb.event_challenge_id
WHERE lb.event_id = $1
ORDER BY lb.event_team_id, challenge.order_index, lb.event_challenge_id
`

type ListEventStandLabsRow struct {
	EventTeamID      uuid.UUID   `json:"event_team_id"`
	EventChallengeID uuid.UUID   `json:"event_challenge_id"`
	Readiness        int16       `json:"readiness"`
	FailureReason    pgtype.Text `json:"failure_reason"`
	ChallengeName    string      `json:"challenge_name"`
}

func (q *Queries) ListEventStandLabs(ctx context.Context, eventID uuid.UUID) ([]ListEventStandLabsRow, error) {
	rows, err := q.db.Query(ctx, listEventStandLabs, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventStandLabsRow{}
	for rows.Next() {
		var i ListEventStandLabsRow
		if err := rows.Scan(
			&i.EventTeamID,
			&i.EventChallengeID,
			&i.Readiness,
			&i.FailureReason,
			&i.ChallengeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventStandRecipients = `-- name: ListEventStandRecipients :many
SELECT DISTINCT recipient.user_id::uuid AS user_id
FROM (
    SELECT m.user_id
    FROM event_managers m
    WHERE m.event_id = $1
    UNION
    SELECT u.id
    FROM users u
    WHERE u.role IN ('super_admin', 'admin')
      AND u.status = 'active'
      AND u.deleted_at IS NULL
) recipient
ORDER BY 1
`

// Every event manager (read or write access) and every active platform
// administrator receives stand failures, once each.
func (q *Queries) ListEventStandRecipients(ctx context.Context, eventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEventStandRecipients, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTeamLabGroups = `-- name: ListEventTeamLabGroups :many
SELECT (lab_group_name(team.event_id, team.id))::text AS lab_group_name
FROM event_teams team
WHERE team.event_id = $1
ORDER BY team.id
`

// Every team LabGroup the event may own (VPN-only groups included).
func (q *Queries) ListEventTeamLabGroups(ctx context.Context, eventID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listEventTeamLabGroups, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var lab_group_name string
		if err := rows.Scan(&lab_group_name); err != nil {
			return nil, err
		}
		items = append(items, lab_group_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissingTeamAssignments = `-- name: ListMissingTeamAssignments :many
SELECT DISTINCT team.id AS event_team_id, exercise.id AS event_exercise_id
FROM event_teams team
JOIN event_exercises exercise ON exercise.event_id = team.event_id AND exercise.status = 0
JOIN event_challenges challenge ON challenge.event_exercise_id = exercise.id
LEFT JOIN team_challenges assignment ON assignment.event_team_id = team.id
                                    AND assignment.event_challenge_id = challenge.id
WHERE team.event_id = $1
  AND (team.moderators OR event_team_admitted(team.event_id, team.individual, team.admitted_manually,
                                              team.admission_locked, team.member_count))
  AND (team.moderators OR event_team_stand_wanted(team.event_id, team.formed_at))
  AND (assignment.id IS NULL
    OR ($2::boolean
        AND assignment.readiness = 0
        AND NOT EXISTS (SELECT 1
                        FROM lab_bindings lb
                        WHERE lb.event_team_id = team.id
                          AND lb.event_challenge_id = challenge.id)))
ORDER BY event_team_id, event_exercise_id
`

type ListMissingTeamAssignmentsParams struct {
	EventID               uuid.UUID `json:"event_id"`
	InfrastructureAllowed bool      `json:"infrastructure_allowed"`
}

type ListMissingTeamAssignmentsRow struct {
	EventTeamID     uuid.UUID `json:"event_team_id"`
	EventExerciseID uuid.UUID `json:"event_exercise_id"`
}

// (team, active exercise) pairs the engine still has to prepare: an admitted
// team (or the moderators team) lacks a team challenge, or has a preparing
// one without its Lab binding while infrastructure is allowed.
func (q *Queries) ListMissingTeamAssignments(ctx context.Context, arg ListMissingTeamAssignmentsParams) ([]ListMissingTeamAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listMissingTeamAssignments, arg.EventID, arg.InfrastructureAllowed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMissingTeamAssignmentsRow{}
	for rows.Next() {
		var i ListMissingTeamAssignmentsRow
		if err := rows.Scan(&i.EventTeamID, &i.EventExerciseID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModeratorsTeamChallenges = `-- name: ListModeratorsTeamChallenges :many
SELECT assignment.event_challenge_id, assignment.readiness,
       COALESCE(challenge.snapshot->>'name', '')::text AS challenge_name,
       lb.readiness AS lab_readiness
FROM team_challenges assignment
JOIN event_teams team ON team.id = assignment.event_team_id
JOIN event_challenges challenge ON challenge.id = assignment.event_challenge_id
JOIN event_exercises exercise ON exercise.id = challenge.event_exercise_id
LEFT JOIN lab_bindings lb ON lb.event_team_id = assignment.event_team_id
                         AND lb.event_challenge_id = assignment.event_challenge_id
WHERE team.event_id = $1
  AND team.moderators
  AND exercise.status = 0
ORDER BY challenge.order_index, assignment.event_challenge_id
`

type ListModeratorsTeamChallengesRow struct {
	EventChallengeID uuid.UUID   `json:"event_challenge_id"`
	Readiness        int16       `json:"readiness"`
	ChallengeName    string      `json:"challenge_name"`
	LabReadiness     pgtype.Int2 `json:"lab_readiness"`
}

func (q *Queries) ListModeratorsTeamChallenges(ctx context.Context, eventID uuid.UUID) ([]ListModeratorsTeamChallengesRow, error) {
	rows, err := q.db.Query(ctx, listModeratorsTeamChallenges, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModeratorsTeamChallengesRow{}
	for rows.Next() {
		var i ListModeratorsTeamChallengesRow
		if err := rows.Scan(
			&i.EventChallengeID,
			&i.Readiness,
			&i.ChallengeName,
			&i.LabReadiness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandEvents = `-- name: ListStandEvents :many
SELECT event.id
FROM events event
JOIN event_configs config ON config.event_id = event.id
LEFT JOIN event_stand_rollouts rollout ON rollout.event_id = event.id
WHERE event.lifecycle_configured
  AND (event.archive_at IS NULL OR $1::timestamptz < event.archive_at)
  AND (event.withdraw_at IS NULL OR $1::timestamptz < event.withdraw_at)
  AND event.start_at - make_interval(mins => config.stand_deploy_lead_minutes) <= $1::timestamptz
  AND rollout.torn_down_at IS NULL
ORDER BY event.start_at, event.id
`

// Events inside the stand window: configured, live, past start minus the
// deploy lead, and not yet torn down. The schedule is re-derived every tick,
// so lifecycle and setting changes need no rescheduling.
func (q *Queries) ListStandEvents(ctx context.Context, now time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStandEvents, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandTeams = `-- name: ListStandTeams :many
SELECT team.id, team.name, team.individual, team.moderators, team.captain_id,
       event_team_public_name(team.individual, team.event_id, team.captain_id, team.name)::text AS public_name,
       (team.moderators OR event_team_admitted(team.event_id, team.individual, team.admitted_manually,
                                               team.admission_locked, team.member_count))::boolean AS admitted,
       stand.status AS stand_status, stand.reason AS stand_reason, stand.generation AS stand_generation,
       stand.updated_at AS stand_updated_at,
       (SELECT count(*) FROM lab_bindings lb WHERE lb.event_team_id = team.id AND lb.readiness = 0)::bigint AS pending_labs,
       (SELECT count(*) FROM lab_bindings lb WHERE lb.event_team_id = team.id AND lb.readiness = 2)::bigint AS failed_labs,
       COALESCE((SELECT min(lb.failure_reason) FROM lab_bindings lb
                 WHERE lb.event_team_id = team.id AND lb.readiness = 2), '')::text AS failure_reason,
       (SELECT COALESCE(max(lb.generation), 0) FROM lab_bindings lb WHERE lb.event_team_id = team.id)::integer AS lab_generation,
       (SELECT count(*)
        FROM event_exercises exercise
        JOIN event_challenges challenge ON challenge.event_exercise_id = exercise.id
        WHERE exercise.event_id = team.event_id
          AND exercise.status = 0
          AND NOT EXISTS (SELECT 1 FROM team_challenges assignment
                          WHERE assignment.event_team_id = team.id
                            AND assignment.event_challenge_id = challenge.id))::bigint AS missing_assignments
FROM event_teams team
LEFT JOIN event_team_stands stand ON stand.event_team_id = team.id
WHERE team.event_id = $1
  AND (team.moderators OR stand.event_team_id IS NOT NULL
    OR (event_team_admitted(team.event_id, team.individual, team.admitted_manually,
                            team.admission_locked, team.member_count)
        AND event_team_stand_wanted(team.event_id, team.formed_at)))
ORDER BY team.moderators DESC, public_name, team.id
`

type ListStandTeamsRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Individual         bool               `json:"individual"`
	Moderators         bool               `json:"moderators"`
	CaptainID          uuid.UUID          `json:"captain_id"`
	PublicName         string             `json:"public_name"`
	Admitted           bool               `json:"admitted"`
	StandStatus        pgtype.Int2        `json:"stand_status"`
	StandReason        pgtype.Text        `json:"stand_reason"`
	StandGeneration    pgtype.Int4        `json:"stand_generation"`
	StandUpdatedAt     pgtype.Timestamptz `json:"stand_updated_at"`
	PendingLabs        int64              `json:"pending_labs"`
	FailedLabs         int64              `json:"failed_labs"`
	FailureReason      string             `json:"failure_reason"`
	LabGeneration      int32              `json:"lab_generation"`
	MissingAssignments int64              `json:"missing_assignments"`
}

// Stand candidates (admitted teams, the moderators team and any team that
// already has a stand) with their persisted stand and Lab counters.
func (q *Queries) ListStandTeams(ctx context.Context, eventID uuid.UUID) ([]ListStandTeamsRow, error) {
	rows, err := q.db.Query(ctx, listStandTeams, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStandTeamsRow{}
	for rows.Next() {
		var i ListStandTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Individual,
			&i.Moderators,
			&i.CaptainID,
			&i.PublicName,
			&i.Admitted,
			&i.StandStatus,
			&i.StandReason,
			&i.StandGeneration,
			&i.StandUpdatedAt,
			&i.PendingLabs,
			&i.FailedLabs,
			&i.FailureReason,
			&i.LabGeneration,
			&i.MissingAssignments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openEventStandRollout = `-- name: OpenEventStandRollout :exec
INSERT INTO event_stand_rollouts (event_id, opened_at, updated_at)
VALUES ($1, $2::timestamptz, $2::timestamptz)
ON CONFLICT (event_id) DO UPDATE
SET opened_at = COALESCE(event_stand_rollouts.opened_at, EXCLUDED.opened_at),
    updated_at = EXCLUDED.updated_at
`

type OpenEventStandRolloutParams struct {
	EventID uuid.UUID `json:"event_id"`
	Now     time.Time `json:"now"`
}

func (q *Queries) OpenEventStandRollout(ctx context.Context, arg OpenEventStandRolloutParams) error {
	_, err := q.db.Exec(ctx, openEventStandRollout, arg.EventID, arg.Now)
	return err
}

const removeEventTeamStands = `-- name: RemoveEventTeamStands :exec
UPDATE event_team_stands
SET status = 4,
    reason = NULL,
    updated_at = $1,
    status_changed_at = $1
WHERE event_id = $2
  AND status <> 4
`

type RemoveEventTeamStandsParams struct {
	Now     time.Time `json:"now"`
	EventID uuid.UUID `json:"event_id"`
}

func (q *Queries) RemoveEventTeamStands(ctx context.Context, arg RemoveEventTeamStandsParams) error {
	_, err := q.db.Exec(ctx, removeEventTeamStands, arg.Now, arg.EventID)
	return err
}

const tearDownEventStandRollout = `-- name: TearDownEventStandRollout :exec
INSERT INTO event_stand_rollouts (event_id, torn_down_at, updated_at)
VALUES ($1, $2::timestamptz, $2::timestamptz)
ON CONFLICT (event_id) DO UPDATE
SET torn_down_at = COALESCE(event_stand_rollouts.torn_down_at, EXCLUDED.torn_down_at),
    updated_at = EXCLUDED.updated_at
`

type TearDownEventStandRolloutParams struct {
	EventID uuid.UUID `json:"event_id"`
	Now     time.Time `json:"now"`
}

func (q *Queries) TearDownEventStandRollout(ctx context.Context, arg TearDownEventStandRolloutParams) error {
	_, err := q.db.Exec(ctx, tearDownEventStandRollout, arg.EventID, arg.Now)
	return err
}

const updateEventTeamStand = `-- name: UpdateEventTeamStand :execrows
UPDATE event_team_stands
SET status = $1,
    reason = $2,
    generation = $3,
    updated_at = $4,
    status_changed_at = CASE WHEN status <> $1 THEN $4 ELSE status_changed_at END
WHERE event_team_id = $5
  AND status = $6
  AND status <> 4
`

type UpdateEventTeamStandParams struct {
	Status         int16       `json:"status"`
	Reason         pgtype.Text `json:"reason"`
	Generation     int32       `json:"generation"`
	Now            time.Time   `json:"now"`
	EventTeamID    uuid.UUID   `json:"event_team_id"`
	ExpectedStatus int16       `json:"expected_status"`
}

// Conditional on the previously read status, so a concurrent engine pass or a
// recreate cannot be overwritten and a failure transition fires only once.
// A removed stand is terminal.
func (q *Queries) UpdateEventTeamStand(ctx context.Context, arg UpdateEventTeamStandParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventTeamStand,
		arg.Status,
		arg.Reason,
		arg.Generation,
		arg.Now,
		arg.EventTeamID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
