// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: event_participants.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEventParticipant = `-- name: CreateEventParticipant :exec
insert into event_participants (event_id, user_id, approval_status)
values ($1, $2, $3)
`

type CreateEventParticipantParams struct {
	EventID        uuid.UUID `json:"event_id"`
	UserID         uuid.UUID `json:"user_id"`
	ApprovalStatus int32     `json:"approval_status"`
}

func (q *Queries) CreateEventParticipant(ctx context.Context, arg CreateEventParticipantParams) error {
	_, err := q.db.Exec(ctx, createEventParticipant, arg.EventID, arg.UserID, arg.ApprovalStatus)
	return err
}

const deleteEventParticipant = `-- name: DeleteEventParticipant :execrows
delete
from event_participants
where event_id = $1
  and user_id = $2
`

type DeleteEventParticipantParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteEventParticipant(ctx context.Context, arg DeleteEventParticipantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventParticipant, arg.EventID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventParticipantStatus = `-- name: GetEventParticipantStatus :one
select approval_status
from event_participants
where event_id = $1
  and user_id = $2
`

type GetEventParticipantStatusParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetEventParticipantStatus(ctx context.Context, arg GetEventParticipantStatusParams) (int32, error) {
	row := q.db.QueryRow(ctx, getEventParticipantStatus, arg.EventID, arg.UserID)
	var approval_status int32
	err := row.Scan(&approval_status)
	return approval_status, err
}

const getEventParticipants = `-- name: GetEventParticipants :many
select event_participants.user_id, event_participants.event_id, event_participants.team_id, event_participants.approval_status, event_participants.updated_at, event_participants.updated_by, event_participants.created_at, u.name as name, u.email as email
from event_participants
inner join users u on event_participants.user_id = u.id
where event_id = $1
order by event_participants.created_at desc
`

type GetEventParticipantsRow struct {
	UserID         uuid.UUID          `json:"user_id"`
	EventID        uuid.UUID          `json:"event_id"`
	TeamID         uuid.NullUUID      `json:"team_id"`
	ApprovalStatus int32              `json:"approval_status"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy      uuid.NullUUID      `json:"updated_by"`
	CreatedAt      time.Time          `json:"created_at"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
}

func (q *Queries) GetEventParticipants(ctx context.Context, eventID uuid.UUID) ([]GetEventParticipantsRow, error) {
	rows, err := q.db.Query(ctx, getEventParticipants, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventParticipantsRow{}
	for rows.Next() {
		var i GetEventParticipantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.EventID,
			&i.TeamID,
			&i.ApprovalStatus,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventParticipantStatus = `-- name: UpdateEventParticipantStatus :execrows
update event_participants
set approval_status = $3,
    updated_at      = now(),
    updated_by      = $4
where event_id = $1
  and user_id = $2
`

type UpdateEventParticipantStatusParams struct {
	EventID        uuid.UUID     `json:"event_id"`
	UserID         uuid.UUID     `json:"user_id"`
	ApprovalStatus int32         `json:"approval_status"`
	UpdatedBy      uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) UpdateEventParticipantStatus(ctx context.Context, arg UpdateEventParticipantStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventParticipantStatus,
		arg.EventID,
		arg.UserID,
		arg.ApprovalStatus,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEventParticipantTeam = `-- name: UpdateEventParticipantTeam :execrows
update event_participants
set team_id    = $3,
    updated_at = now(),
    updated_by = $4
where event_id = $1
  and user_id = $2
`

type UpdateEventParticipantTeamParams struct {
	EventID   uuid.UUID     `json:"event_id"`
	UserID    uuid.UUID     `json:"user_id"`
	TeamID    uuid.NullUUID `json:"team_id"`
	UpdatedBy uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) UpdateEventParticipantTeam(ctx context.Context, arg UpdateEventParticipantTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventParticipantTeam,
		arg.EventID,
		arg.UserID,
		arg.TeamID,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
