// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_field_policy.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const countEventRegistrationAnswers = `-- name: CountEventRegistrationAnswers :one
SELECT count(DISTINCT answer.user_id)
FROM event_form_answers answer
         JOIN event_form_versions version ON version.id = answer.form_version_id
         JOIN event_forms form ON form.id = version.form_id
WHERE answer.event_id = $1 AND form.purpose = 'registration'
`

func (q *Queries) CountEventRegistrationAnswers(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventRegistrationAnswers, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEventParticipantFieldsMissing = `-- name: GetEventParticipantFieldsMissing :one
SELECT fields_missing FROM event_participants
WHERE event_id = $1 AND user_id = $2
`

type GetEventParticipantFieldsMissingParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetEventParticipantFieldsMissing(ctx context.Context, arg GetEventParticipantFieldsMissingParams) (int32, error) {
	row := q.db.QueryRow(ctx, getEventParticipantFieldsMissing, arg.EventID, arg.UserID)
	var fields_missing int32
	err := row.Scan(&fields_missing)
	return fields_missing, err
}

const getEventTeamFieldsMissing = `-- name: GetEventTeamFieldsMissing :one
SELECT fields_missing FROM event_teams
WHERE event_id = $1 AND id = $2
`

type GetEventTeamFieldsMissingParams struct {
	EventID uuid.UUID `json:"event_id"`
	TeamID  uuid.UUID `json:"team_id"`
}

func (q *Queries) GetEventTeamFieldsMissing(ctx context.Context, arg GetEventTeamFieldsMissingParams) (int32, error) {
	row := q.db.QueryRow(ctx, getEventTeamFieldsMissing, arg.EventID, arg.TeamID)
	var fields_missing int32
	err := row.Scan(&fields_missing)
	return fields_missing, err
}

const getLastEventStaffFieldChange = `-- name: GetLastEventStaffFieldChange :one
SELECT change.field_keys, change.changed_at, change.actor_id,
       COALESCE(NULLIF(btrim(actor.first_name || ' ' || actor.last_name), ''), actor.email, '')::text AS actor_name
FROM event_staff_field_changes change
         LEFT JOIN users actor ON actor.id = change.actor_id
WHERE change.event_id = $1
  AND change.scope = $2
  AND change.subject_id = $3
ORDER BY change.changed_at DESC
LIMIT 1
`

type GetLastEventStaffFieldChangeParams struct {
	EventID   uuid.UUID `json:"event_id"`
	Scope     string    `json:"scope"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type GetLastEventStaffFieldChangeRow struct {
	FieldKeys []string      `json:"field_keys"`
	ChangedAt time.Time     `json:"changed_at"`
	ActorID   uuid.NullUUID `json:"actor_id"`
	ActorName string        `json:"actor_name"`
}

func (q *Queries) GetLastEventStaffFieldChange(ctx context.Context, arg GetLastEventStaffFieldChangeParams) (GetLastEventStaffFieldChangeRow, error) {
	row := q.db.QueryRow(ctx, getLastEventStaffFieldChange, arg.EventID, arg.Scope, arg.SubjectID)
	var i GetLastEventStaffFieldChangeRow
	err := row.Scan(
		&i.FieldKeys,
		&i.ChangedAt,
		&i.ActorID,
		&i.ActorName,
	)
	return i, err
}

const getLatestEventRegistrationAnswerRow = `-- name: GetLatestEventRegistrationAnswerRow :one
SELECT answer.form_version_id, answer.answers
FROM event_form_answers answer
         JOIN event_form_versions version ON version.id = answer.form_version_id
         JOIN event_forms form ON form.id = version.form_id
WHERE answer.event_id = $1
  AND answer.user_id = $2
  AND form.purpose = 'registration'
ORDER BY answer.submitted_at DESC
LIMIT 1
`

type GetLatestEventRegistrationAnswerRowParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type GetLatestEventRegistrationAnswerRowRow struct {
	FormVersionID uuid.UUID `json:"form_version_id"`
	Answers       []byte    `json:"answers"`
}

// The participant's newest registration answer row (its version id keeps the
// staff-only values next to the answers they belong to).
func (q *Queries) GetLatestEventRegistrationAnswerRow(ctx context.Context, arg GetLatestEventRegistrationAnswerRowParams) (GetLatestEventRegistrationAnswerRowRow, error) {
	row := q.db.QueryRow(ctx, getLatestEventRegistrationAnswerRow, arg.EventID, arg.UserID)
	var i GetLatestEventRegistrationAnswerRowRow
	err := row.Scan(&i.FormVersionID, &i.Answers)
	return i, err
}

const insertEventStaffFieldChange = `-- name: InsertEventStaffFieldChange :exec
INSERT INTO event_staff_field_changes (id, event_id, scope, subject_id, actor_id, field_keys, changed_at)
VALUES ($1, $2, $3, $4, $5, $6::text[], $7)
`

type InsertEventStaffFieldChangeParams struct {
	ID        uuid.UUID     `json:"id"`
	EventID   uuid.UUID     `json:"event_id"`
	Scope     string        `json:"scope"`
	SubjectID uuid.UUID     `json:"subject_id"`
	ActorID   uuid.NullUUID `json:"actor_id"`
	FieldKeys []string      `json:"field_keys"`
	ChangedAt time.Time     `json:"changed_at"`
}

func (q *Queries) InsertEventStaffFieldChange(ctx context.Context, arg InsertEventStaffFieldChangeParams) error {
	_, err := q.db.Exec(ctx, insertEventStaffFieldChange,
		arg.ID,
		arg.EventID,
		arg.Scope,
		arg.SubjectID,
		arg.ActorID,
		arg.FieldKeys,
		arg.ChangedAt,
	)
	return err
}

const listEventParticipantRegistrationAnswers = `-- name: ListEventParticipantRegistrationAnswers :many
SELECT participant.user_id, event_registration_answers(participant.event_id, participant.user_id)::jsonb AS answers
FROM event_participants participant
WHERE participant.event_id = $1
`

type ListEventParticipantRegistrationAnswersRow struct {
	UserID  uuid.UUID `json:"user_id"`
	Answers []byte    `json:"answers"`
}

// Every participant of the event with the latest registration answers (NULL
// when none): the input of the «missing required fields» recount.
func (q *Queries) ListEventParticipantRegistrationAnswers(ctx context.Context, eventID uuid.UUID) ([]ListEventParticipantRegistrationAnswersRow, error) {
	rows, err := q.db.Query(ctx, listEventParticipantRegistrationAnswers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventParticipantRegistrationAnswersRow{}
	for rows.Next() {
		var i ListEventParticipantRegistrationAnswersRow
		if err := rows.Scan(&i.UserID, &i.Answers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTeamExtraFields = `-- name: ListEventTeamExtraFields :many
SELECT id, extra_fields FROM event_teams WHERE event_id = $1
`

type ListEventTeamExtraFieldsRow struct {
	ID          uuid.UUID `json:"id"`
	ExtraFields []byte    `json:"extra_fields"`
}

func (q *Queries) ListEventTeamExtraFields(ctx context.Context, eventID uuid.UUID) ([]ListEventTeamExtraFieldsRow, error) {
	rows, err := q.db.Query(ctx, listEventTeamExtraFields, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventTeamExtraFieldsRow{}
	for rows.Next() {
		var i ListEventTeamExtraFieldsRow
		if err := rows.Scan(&i.ID, &i.ExtraFields); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventParticipantsFieldsMissing = `-- name: SetEventParticipantsFieldsMissing :exec
UPDATE event_participants participant
SET fields_missing = counted.missing
FROM (SELECT unnest($2::uuid[]) AS user_id, unnest($3::int[]) AS missing) counted
WHERE participant.event_id = $1
  AND participant.user_id = counted.user_id
  AND participant.fields_missing <> counted.missing
`

type SetEventParticipantsFieldsMissingParams struct {
	EventID uuid.UUID   `json:"event_id"`
	UserIds []uuid.UUID `json:"user_ids"`
	Missing []int32     `json:"missing"`
}

func (q *Queries) SetEventParticipantsFieldsMissing(ctx context.Context, arg SetEventParticipantsFieldsMissingParams) error {
	_, err := q.db.Exec(ctx, setEventParticipantsFieldsMissing, arg.EventID, arg.UserIds, arg.Missing)
	return err
}

const setEventTeamsFieldsMissing = `-- name: SetEventTeamsFieldsMissing :exec
UPDATE event_teams team
SET fields_missing = counted.missing
FROM (SELECT unnest($2::uuid[]) AS team_id, unnest($3::int[]) AS missing) counted
WHERE team.event_id = $1
  AND team.id = counted.team_id
  AND team.fields_missing <> counted.missing
`

type SetEventTeamsFieldsMissingParams struct {
	EventID uuid.UUID   `json:"event_id"`
	TeamIds []uuid.UUID `json:"team_ids"`
	Missing []int32     `json:"missing"`
}

func (q *Queries) SetEventTeamsFieldsMissing(ctx context.Context, arg SetEventTeamsFieldsMissingParams) error {
	_, err := q.db.Exec(ctx, setEventTeamsFieldsMissing, arg.EventID, arg.TeamIds, arg.Missing)
	return err
}

const updateEventFormAnswerValues = `-- name: UpdateEventFormAnswerValues :execrows
UPDATE event_form_answers
SET answers = $1
WHERE event_id = $2
  AND user_id = $3
  AND form_version_id = $4
`

type UpdateEventFormAnswerValuesParams struct {
	Answers       []byte    `json:"answers"`
	EventID       uuid.UUID `json:"event_id"`
	UserID        uuid.UUID `json:"user_id"`
	FormVersionID uuid.UUID `json:"form_version_id"`
}

// Staff-only edits change the values only: submitted_at stays the moment the
// participant answered.
func (q *Queries) UpdateEventFormAnswerValues(ctx context.Context, arg UpdateEventFormAnswerValuesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventFormAnswerValues,
		arg.Answers,
		arg.EventID,
		arg.UserID,
		arg.FormVersionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
