// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveEventExercises = `-- name: ArchiveEventExercises :exec
UPDATE exercises
SET archived_at = COALESCE(archived_at, $1::timestamptz),
    updated_at  = $1::timestamptz
WHERE owner_event_id = $2
`

type ArchiveEventExercisesParams struct {
	Now     time.Time     `json:"now"`
	EventID uuid.NullUUID `json:"event_id"`
}

// Event deletion archives the exercises the event owns (same transaction as
// the delete; the owner pointer is then nulled by the foreign key).
func (q *Queries) ArchiveEventExercises(ctx context.Context, arg ArchiveEventExercisesParams) error {
	_, err := q.db.Exec(ctx, archiveEventExercises, arg.Now, arg.EventID)
	return err
}

const countExercises = `-- name: CountExercises :one
SELECT count(*)
FROM exercises
WHERE ($1::text = '' OR name ILIKE '%' || $1::text || '%'
    OR description ILIKE '%' || $1::text || '%')
  AND (cardinality($2::text[]) = 0 OR tags && $2::text[])
  AND (CASE WHEN $3::text = 'only' THEN archived_at IS NOT NULL ELSE archived_at IS NULL END)
  AND ($4::text = '' OR ($4::text = 'catalog' AND scope = 0)
    OR ($4::text = 'event' AND scope = 1))
  AND (COALESCE(cardinality($5::uuid[]), 0) = 0 OR owner_event_id = ANY ($5::uuid[])
    OR (scope = 0 AND EXISTS (SELECT 1
                              FROM unnest($5::uuid[]) AS selected(event_id)
                              WHERE exercise_available_to_event(exercises.id, selected.event_id))))
  AND ($6::text = ''
    OR exercise_has_infrastructure(id) = ($6::text = 'yes'))
  AND ($7::uuid IS NULL OR exercise_readable_by(id, $7::uuid))
`

type CountExercisesParams struct {
	Search         string        `json:"search"`
	Tags           []string      `json:"tags"`
	Archived       string        `json:"archived"`
	Scope          string        `json:"scope"`
	EventIds       []uuid.UUID   `json:"event_ids"`
	Infrastructure string        `json:"infrastructure"`
	ViewerID       uuid.NullUUID `json:"viewer_id"`
}

func (q *Queries) CountExercises(ctx context.Context, arg CountExercisesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExercises,
		arg.Search,
		arg.Tags,
		arg.Archived,
		arg.Scope,
		arg.EventIds,
		arg.Infrastructure,
		arg.ViewerID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExercisesPage = `-- name: CountExercisesPage :one
WITH listed AS (SELECT exercise_status(draft_version_id, published_version_id, archived_at IS NOT NULL,
                                       $2::uuid IS NULL OR scope = 1)::text AS status
                FROM exercises
                WHERE ($3::text = '' OR name ILIKE '%' || $3::text || '%'
                    OR description ILIKE '%' || $3::text || '%')
                  AND (cardinality($4::text[]) = 0 OR tags && $4::text[])
                  AND (CASE WHEN $5::text = 'only' THEN archived_at IS NOT NULL ELSE archived_at IS NULL END)
                  AND ($6::text = '' OR ($6::text = 'catalog' AND scope = 0)
                    OR ($6::text = 'event' AND scope = 1))
                  AND (COALESCE(cardinality($7::uuid[]), 0) = 0 OR owner_event_id = ANY ($7::uuid[])
                    OR (scope = 0 AND EXISTS (SELECT 1
                                              FROM unnest($7::uuid[]) AS selected(event_id)
                                              WHERE exercise_available_to_event(exercises.id, selected.event_id))))
                  AND ($8::text = ''
                    OR exercise_has_infrastructure(id) = ($8::text = 'yes'))
                  AND ($2::uuid IS NULL OR exercise_readable_by(id, $2::uuid)))
SELECT count(*)
FROM listed
WHERE ($1::text = '' OR listed.status = $1::text)
`

type CountExercisesPageParams struct {
	Status         string        `json:"status"`
	ViewerID       uuid.NullUUID `json:"viewer_id"`
	Search         string        `json:"search"`
	Tags           []string      `json:"tags"`
	Archived       string        `json:"archived"`
	Scope          string        `json:"scope"`
	EventIds       []uuid.UUID   `json:"event_ids"`
	Infrastructure string        `json:"infrastructure"`
}

func (q *Queries) CountExercisesPage(ctx context.Context, arg CountExercisesPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExercisesPage,
		arg.Status,
		arg.ViewerID,
		arg.Search,
		arg.Tags,
		arg.Archived,
		arg.Scope,
		arg.EventIds,
		arg.Infrastructure,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (id, name, description, tags, created_at, created_by, updated_at, updated_by,
                       scope, owner_event_id, access_level, origin_event_id, forked_from_exercise_id, forked_from_version_id)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11,
        $12, $13, $14)
RETURNING id, name, description, tags, created_at, created_by, updated_at, updated_by, draft_version_id, published_version_id, archived_at, scope, owner_event_id, access_level, origin_event_id, forked_from_exercise_id, forked_from_version_id
`

type CreateExerciseParams struct {
	ID                   uuid.UUID     `json:"id"`
	Name                 string        `json:"name"`
	Description          string        `json:"description"`
	Tags                 []string      `json:"tags"`
	CreatedAt            time.Time     `json:"created_at"`
	CreatedBy            uuid.NullUUID `json:"created_by"`
	UpdatedAt            time.Time     `json:"updated_at"`
	UpdatedBy            uuid.NullUUID `json:"updated_by"`
	Scope                int16         `json:"scope"`
	OwnerEventID         uuid.NullUUID `json:"owner_event_id"`
	AccessLevel          int16         `json:"access_level"`
	OriginEventID        uuid.NullUUID `json:"origin_event_id"`
	ForkedFromExerciseID uuid.NullUUID `json:"forked_from_exercise_id"`
	ForkedFromVersionID  uuid.NullUUID `json:"forked_from_version_id"`
}

// Timestamps come from the domain factory, not DB defaults.
func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.Scope,
		arg.OwnerEventID,
		arg.AccessLevel,
		arg.OriginEventID,
		arg.ForkedFromExerciseID,
		arg.ForkedFromVersionID,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DraftVersionID,
		&i.PublishedVersionID,
		&i.ArchivedAt,
		&i.Scope,
		&i.OwnerEventID,
		&i.AccessLevel,
		&i.OriginEventID,
		&i.ForkedFromExerciseID,
		&i.ForkedFromVersionID,
	)
	return i, err
}

const createExerciseProposal = `-- name: CreateExerciseProposal :one
INSERT INTO exercise_proposals (id, exercise_id, event_id, status, note, proposed_by, proposed_at)
VALUES ($1, $2, $3, 0, $4, $5, $6)
RETURNING id, exercise_id, event_id, status, note, proposed_by, proposed_at, decided_by, decided_at, decision_note, catalog_exercise_id
`

type CreateExerciseProposalParams struct {
	ID         uuid.UUID     `json:"id"`
	ExerciseID uuid.UUID     `json:"exercise_id"`
	EventID    uuid.NullUUID `json:"event_id"`
	Note       string        `json:"note"`
	ProposedBy uuid.NullUUID `json:"proposed_by"`
	ProposedAt time.Time     `json:"proposed_at"`
}

func (q *Queries) CreateExerciseProposal(ctx context.Context, arg CreateExerciseProposalParams) (ExerciseProposal, error) {
	row := q.db.QueryRow(ctx, createExerciseProposal,
		arg.ID,
		arg.ExerciseID,
		arg.EventID,
		arg.Note,
		arg.ProposedBy,
		arg.ProposedAt,
	)
	var i ExerciseProposal
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.EventID,
		&i.Status,
		&i.Note,
		&i.ProposedBy,
		&i.ProposedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CatalogExerciseID,
	)
	return i, err
}

const decideExerciseProposal = `-- name: DecideExerciseProposal :execrows
UPDATE exercise_proposals
SET status              = $1,
    decided_by          = $2,
    decided_at          = $3,
    decision_note       = $4,
    catalog_exercise_id = $5
WHERE id = $6
  AND status = 0
`

type DecideExerciseProposalParams struct {
	Status            int16              `json:"status"`
	DecidedBy         uuid.NullUUID      `json:"decided_by"`
	DecidedAt         pgtype.Timestamptz `json:"decided_at"`
	DecisionNote      string             `json:"decision_note"`
	CatalogExerciseID uuid.NullUUID      `json:"catalog_exercise_id"`
	ID                uuid.UUID          `json:"id"`
}

func (q *Queries) DecideExerciseProposal(ctx context.Context, arg DecideExerciseProposalParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideExerciseProposal,
		arg.Status,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.DecisionNote,
		arg.CatalogExerciseID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExercise = `-- name: DeleteExercise :execrows
DELETE
FROM exercises
WHERE id = $1
`

func (q *Queries) DeleteExercise(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExercise, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExerciseEventAccess = `-- name: DeleteExerciseEventAccess :exec
DELETE
FROM exercise_event_access
WHERE exercise_id = $1
`

func (q *Queries) DeleteExerciseEventAccess(ctx context.Context, exerciseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExerciseEventAccess, exerciseID)
	return err
}

const exerciseDraftDiffersFromPublished = `-- name: ExerciseDraftDiffersFromPublished :one
SELECT (d.variants <> p.variants OR d.admin_note <> p.admin_note)::boolean AS differs
FROM exercises e
JOIN exercise_versions d ON d.id = e.draft_version_id
JOIN exercise_versions p ON p.id = e.published_version_id
WHERE e.id = $1
`

// jsonb equality is semantic (key order and whitespace are irrelevant), so a
// working copy re-saved or restored with the published content compares
// equal. Zero rows when either pointer is NULL: those cases are decided by
// the domain (Exercise.HasUnpublishedChanges) without asking.
// label is deliberately not compared: it names snapshots, never content.
func (q *Queries) ExerciseDraftDiffersFromPublished(ctx context.Context, exerciseID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, exerciseDraftDiffersFromPublished, exerciseID)
	var differs bool
	err := row.Scan(&differs)
	return differs, err
}

const getEventInfrastructureAllowed = `-- name: GetEventInfrastructureAllowed :one
SELECT infrastructure_allowed
FROM events
WHERE id = $1
`

func (q *Queries) GetEventInfrastructureAllowed(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getEventInfrastructureAllowed, id)
	var infrastructure_allowed bool
	err := row.Scan(&infrastructure_allowed)
	return infrastructure_allowed, err
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, name, description, tags, created_at, created_by, updated_at, updated_by, draft_version_id, published_version_id, archived_at, scope, owner_event_id, access_level, origin_event_id, forked_from_exercise_id, forked_from_version_id
FROM exercises
WHERE id = $1
`

func (q *Queries) GetExerciseByID(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DraftVersionID,
		&i.PublishedVersionID,
		&i.ArchivedAt,
		&i.Scope,
		&i.OwnerEventID,
		&i.AccessLevel,
		&i.OriginEventID,
		&i.ForkedFromExerciseID,
		&i.ForkedFromVersionID,
	)
	return i, err
}

const getExerciseInfrastructure = `-- name: GetExerciseInfrastructure :one
SELECT exercise_has_infrastructure($1)::boolean
`

func (q *Queries) GetExerciseInfrastructure(ctx context.Context, exerciseID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getExerciseInfrastructure, exerciseID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getExerciseProposal = `-- name: GetExerciseProposal :one
SELECT id, exercise_id, event_id, status, note, proposed_by, proposed_at, decided_by, decided_at, decision_note, catalog_exercise_id
FROM exercise_proposals
WHERE id = $1
`

func (q *Queries) GetExerciseProposal(ctx context.Context, id uuid.UUID) (ExerciseProposal, error) {
	row := q.db.QueryRow(ctx, getExerciseProposal, id)
	var i ExerciseProposal
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.EventID,
		&i.Status,
		&i.Note,
		&i.ProposedBy,
		&i.ProposedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CatalogExerciseID,
	)
	return i, err
}

const insertExerciseEventAccess = `-- name: InsertExerciseEventAccess :exec
INSERT INTO exercise_event_access (exercise_id, event_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type InsertExerciseEventAccessParams struct {
	ExerciseID uuid.UUID   `json:"exercise_id"`
	EventIds   []uuid.UUID `json:"event_ids"`
}

func (q *Queries) InsertExerciseEventAccess(ctx context.Context, arg InsertExerciseEventAccessParams) error {
	_, err := q.db.Exec(ctx, insertExerciseEventAccess, arg.ExerciseID, arg.EventIds)
	return err
}

const isExerciseAvailableToEvent = `-- name: IsExerciseAvailableToEvent :one
SELECT exercise_available_to_event($1, $2)::boolean
`

type IsExerciseAvailableToEventParams struct {
	ExerciseID uuid.UUID `json:"exercise_id"`
	EventID    uuid.UUID `json:"event_id"`
}

func (q *Queries) IsExerciseAvailableToEvent(ctx context.Context, arg IsExerciseAvailableToEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, isExerciseAvailableToEvent, arg.ExerciseID, arg.EventID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const isExerciseReadableBy = `-- name: IsExerciseReadableBy :one
SELECT exercise_readable_by($1, $2)::boolean
`

type IsExerciseReadableByParams struct {
	ExerciseID uuid.UUID `json:"exercise_id"`
	ViewerID   uuid.UUID `json:"viewer_id"`
}

func (q *Queries) IsExerciseReadableBy(ctx context.Context, arg IsExerciseReadableByParams) (bool, error) {
	row := q.db.QueryRow(ctx, isExerciseReadableBy, arg.ExerciseID, arg.ViewerID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listExerciseCardExtras = `-- name: ListExerciseCardExtras :many
SELECT e.id,
       COALESCE(NULLIF(owner.internal_name, ''), owner.name, '')::text AS owner_event_name,
       COALESCE(source.name, '')::text AS forked_from_name,
       exercise_has_infrastructure(e.id)::boolean AS infrastructure,
       proposal.id AS pending_proposal_id
FROM exercises e
LEFT JOIN events owner ON owner.id = e.owner_event_id
LEFT JOIN exercises source ON source.id = e.forked_from_exercise_id
LEFT JOIN exercise_proposals proposal ON proposal.exercise_id = e.id AND proposal.status = 0
WHERE e.id = ANY ($1::uuid[])
`

type ListExerciseCardExtrasRow struct {
	ID                uuid.UUID     `json:"id"`
	OwnerEventName    string        `json:"owner_event_name"`
	ForkedFromName    string        `json:"forked_from_name"`
	Infrastructure    bool          `json:"infrastructure"`
	PendingProposalID uuid.NullUUID `json:"pending_proposal_id"`
}

// Card decorations for a page of exercises in one query: owner event name,
// fork source name, infrastructure and a pending proposal.
func (q *Queries) ListExerciseCardExtras(ctx context.Context, ids []uuid.UUID) ([]ListExerciseCardExtrasRow, error) {
	rows, err := q.db.Query(ctx, listExerciseCardExtras, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExerciseCardExtrasRow{}
	for rows.Next() {
		var i ListExerciseCardExtrasRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerEventName,
			&i.ForkedFromName,
			&i.Infrastructure,
			&i.PendingProposalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseProposals = `-- name: ListExerciseProposals :many
SELECT proposal.id, proposal.exercise_id, proposal.event_id, proposal.status, proposal.note, proposal.proposed_by, proposal.proposed_at, proposal.decided_by, proposal.decided_at, proposal.decision_note, proposal.catalog_exercise_id,
       source.name::text AS exercise_name,
       COALESCE(NULLIF(ev.internal_name, ''), ev.name, '')::text AS event_name,
       COALESCE(NULLIF(btrim(concat_ws(' ', person.first_name, person.last_name)), ''), person.email, '')::text AS proposed_by_name
FROM exercise_proposals proposal
JOIN exercises source ON source.id = proposal.exercise_id
LEFT JOIN events ev ON ev.id = proposal.event_id
LEFT JOIN users person ON person.id = proposal.proposed_by
WHERE ($1::smallint IS NULL OR proposal.status = $1::smallint)
ORDER BY proposal.proposed_at DESC, proposal.id DESC
LIMIT 200
`

type ListExerciseProposalsRow struct {
	ID                uuid.UUID          `json:"id"`
	ExerciseID        uuid.UUID          `json:"exercise_id"`
	EventID           uuid.NullUUID      `json:"event_id"`
	Status            int16              `json:"status"`
	Note              string             `json:"note"`
	ProposedBy        uuid.NullUUID      `json:"proposed_by"`
	ProposedAt        time.Time          `json:"proposed_at"`
	DecidedBy         uuid.NullUUID      `json:"decided_by"`
	DecidedAt         pgtype.Timestamptz `json:"decided_at"`
	DecisionNote      string             `json:"decision_note"`
	CatalogExerciseID uuid.NullUUID      `json:"catalog_exercise_id"`
	ExerciseName      string             `json:"exercise_name"`
	EventName         string             `json:"event_name"`
	ProposedByName    string             `json:"proposed_by_name"`
}

func (q *Queries) ListExerciseProposals(ctx context.Context, status pgtype.Int2) ([]ListExerciseProposalsRow, error) {
	rows, err := q.db.Query(ctx, listExerciseProposals, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExerciseProposalsRow{}
	for rows.Next() {
		var i ListExerciseProposalsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.EventID,
			&i.Status,
			&i.Note,
			&i.ProposedBy,
			&i.ProposedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
			&i.CatalogExerciseID,
			&i.ExerciseName,
			&i.EventName,
			&i.ProposedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseTags = `-- name: ListExerciseTags :many
SELECT tag::text AS tag, count(DISTINCT e.id)::bigint AS exercise_count
FROM exercises AS e
CROSS JOIN LATERAL unnest(e.tags) AS tag
WHERE ($1::text = ''
    OR left(tag, char_length($1::text)) = lower($1::text))
  AND ($2::uuid IS NULL OR exercise_readable_by(e.id, $2::uuid))
GROUP BY tag
ORDER BY exercise_count DESC, tag ASC
LIMIT $3
`

type ListExerciseTagsParams struct {
	Prefix   string        `json:"prefix"`
	ViewerID uuid.NullUUID `json:"viewer_id"`
	LimitVal int32         `json:"limit_val"`
}

type ListExerciseTagsRow struct {
	Tag           string `json:"tag"`
	ExerciseCount int64  `json:"exercise_count"`
}

// Tags of existing exercises by use; an empty prefix returns the most used.
// Prefix matching is literal (%, _ are not LIKE wildcards) and
// case-insensitive. viewer_id set = count only exercises the viewer may read.
func (q *Queries) ListExerciseTags(ctx context.Context, arg ListExerciseTagsParams) ([]ListExerciseTagsRow, error) {
	rows, err := q.db.Query(ctx, listExerciseTags, arg.Prefix, arg.ViewerID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExerciseTagsRow{}
	for rows.Next() {
		var i ListExerciseTagsRow
		if err := rows.Scan(&i.Tag, &i.ExerciseCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseUsageEvents = `-- name: ListExerciseUsageEvents :many
SELECT ev.id,
       COALESCE(NULLIF(ev.internal_name, ''), ev.name)::text AS name,
       (ev.archive_at IS NOT NULL AND ev.archive_at <= $1::timestamptz)::boolean AS archived
FROM events ev
WHERE EXISTS (SELECT 1
              FROM event_exercises ee
              WHERE ee.event_id = ev.id
                AND ee.exercise_id = $2)
ORDER BY lower(COALESCE(NULLIF(ev.internal_name, ''), ev.name)), ev.id
`

type ListExerciseUsageEventsParams struct {
	Now        time.Time `json:"now"`
	ExerciseID uuid.UUID `json:"exercise_id"`
}

type ListExerciseUsageEventsRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Archived bool      `json:"archived"`
}

// Events that reference any version of the exercise through any attachment
// revision (active or superseded), each once. Name is the platform-facing
// internal name (falls back to the public one). Archived uses the same rule
// as the events list: the archive instant has passed.
func (q *Queries) ListExerciseUsageEvents(ctx context.Context, arg ListExerciseUsageEventsParams) ([]ListExerciseUsageEventsRow, error) {
	rows, err := q.db.Query(ctx, listExerciseUsageEvents, arg.Now, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExerciseUsageEventsRow{}
	for rows.Next() {
		var i ListExerciseUsageEventsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Archived); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesCursor = `-- name: ListExercisesCursor :many

SELECT exercises.id, exercises.name, exercises.description, exercises.tags, exercises.created_at, exercises.created_by, exercises.updated_at, exercises.updated_by, exercises.draft_version_id, exercises.published_version_id, exercises.archived_at, exercises.scope, exercises.owner_event_id, exercises.access_level, exercises.origin_event_id, exercises.forked_from_exercise_id, exercises.forked_from_version_id,
       exercise_status(draft_version_id, published_version_id, archived_at IS NOT NULL,
                       $1::uuid IS NULL OR scope = 1)::text AS status
FROM exercises
WHERE ($2::text = '' OR name ILIKE '%' || $2::text || '%'
    OR description ILIKE '%' || $2::text || '%')
  AND (cardinality($3::text[]) = 0 OR tags && $3::text[])
  AND (CASE WHEN $4::text = 'only' THEN archived_at IS NOT NULL ELSE archived_at IS NULL END)
  AND ($5::text = '' OR ($5::text = 'catalog' AND scope = 0)
    OR ($5::text = 'event' AND scope = 1))
  AND (COALESCE(cardinality($6::uuid[]), 0) = 0 OR owner_event_id = ANY ($6::uuid[])
    OR (scope = 0 AND EXISTS (SELECT 1
                              FROM unnest($6::uuid[]) AS selected(event_id)
                              WHERE exercise_available_to_event(exercises.id, selected.event_id))))
  AND ($7::text = ''
    OR exercise_has_infrastructure(id) = ($7::text = 'yes'))
  AND ($1::uuid IS NULL OR exercise_readable_by(id, $1::uuid))
  AND (created_at, id) < ($8::timestamptz, $9::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $10
`

type ListExercisesCursorParams struct {
	ViewerID        uuid.NullUUID `json:"viewer_id"`
	Search          string        `json:"search"`
	Tags            []string      `json:"tags"`
	Archived        string        `json:"archived"`
	Scope           string        `json:"scope"`
	EventIds        []uuid.UUID   `json:"event_ids"`
	Infrastructure  string        `json:"infrastructure"`
	CursorCreatedAt time.Time     `json:"cursor_created_at"`
	CursorID        uuid.UUID     `json:"cursor_id"`
	LimitVal        int32         `json:"limit_val"`
}

type ListExercisesCursorRow struct {
	Exercise Exercise `json:"exercise"`
	Status   string   `json:"status"`
}

// Shared list filters (keep the four list/count queries in sync):
// scope ” | catalog | event; event_ids keeps exercises relevant to ANY of
// the events (owned by one, or a catalog exercise available to one) — with
// scope 'catalog' that is "available to any", with 'event' "owned by any";
// viewer_id set = a non-admin who sees only what they may read.
func (q *Queries) ListExercisesCursor(ctx context.Context, arg ListExercisesCursorParams) ([]ListExercisesCursorRow, error) {
	rows, err := q.db.Query(ctx, listExercisesCursor,
		arg.ViewerID,
		arg.Search,
		arg.Tags,
		arg.Archived,
		arg.Scope,
		arg.EventIds,
		arg.Infrastructure,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExercisesCursorRow{}
	for rows.Next() {
		var i ListExercisesCursorRow
		if err := rows.Scan(
			&i.Exercise.ID,
			&i.Exercise.Name,
			&i.Exercise.Description,
			&i.Exercise.Tags,
			&i.Exercise.CreatedAt,
			&i.Exercise.CreatedBy,
			&i.Exercise.UpdatedAt,
			&i.Exercise.UpdatedBy,
			&i.Exercise.DraftVersionID,
			&i.Exercise.PublishedVersionID,
			&i.Exercise.ArchivedAt,
			&i.Exercise.Scope,
			&i.Exercise.OwnerEventID,
			&i.Exercise.AccessLevel,
			&i.Exercise.OriginEventID,
			&i.Exercise.ForkedFromExerciseID,
			&i.Exercise.ForkedFromVersionID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesEventAccess = `-- name: ListExercisesEventAccess :many
SELECT access.exercise_id,
       access.event_id,
       COALESCE(NULLIF(ev.internal_name, ''), ev.name)::text AS event_name
FROM exercise_event_access access
JOIN events ev ON ev.id = access.event_id
WHERE access.exercise_id = ANY ($1::uuid[])
ORDER BY access.exercise_id, lower(COALESCE(NULLIF(ev.internal_name, ''), ev.name)), ev.id
`

type ListExercisesEventAccessRow struct {
	ExerciseID uuid.UUID `json:"exercise_id"`
	EventID    uuid.UUID `json:"event_id"`
	EventName  string    `json:"event_name"`
}

// The "selected events" of a page of exercises in one query, with the
// platform-facing event name.
func (q *Queries) ListExercisesEventAccess(ctx context.Context, exerciseIds []uuid.UUID) ([]ListExercisesEventAccessRow, error) {
	rows, err := q.db.Query(ctx, listExercisesEventAccess, exerciseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExercisesEventAccessRow{}
	for rows.Next() {
		var i ListExercisesEventAccessRow
		if err := rows.Scan(&i.ExerciseID, &i.EventID, &i.EventName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesPage = `-- name: ListExercisesPage :many
WITH listed AS (SELECT id,
                       exercise_status(draft_version_id, published_version_id, archived_at IS NOT NULL,
                                       $6::uuid IS NULL OR scope = 1)::text AS status
                FROM exercises
                WHERE ($7::text = '' OR name ILIKE '%' || $7::text || '%'
                    OR description ILIKE '%' || $7::text || '%')
                  AND (cardinality($8::text[]) = 0 OR tags && $8::text[])
                  AND (CASE WHEN $9::text = 'only' THEN archived_at IS NOT NULL ELSE archived_at IS NULL END)
                  AND ($10::text = '' OR ($10::text = 'catalog' AND scope = 0)
                    OR ($10::text = 'event' AND scope = 1))
                  AND (COALESCE(cardinality($11::uuid[]), 0) = 0 OR owner_event_id = ANY ($11::uuid[])
                    OR (scope = 0 AND EXISTS (SELECT 1
                                              FROM unnest($11::uuid[]) AS selected(event_id)
                                              WHERE exercise_available_to_event(exercises.id, selected.event_id))))
                  AND ($12::text = ''
                    OR exercise_has_infrastructure(id) = ($12::text = 'yes'))
                  AND ($6::uuid IS NULL OR exercise_readable_by(id, $6::uuid)))
SELECT exercises.id, exercises.name, exercises.description, exercises.tags, exercises.created_at, exercises.created_by, exercises.updated_at, exercises.updated_by, exercises.draft_version_id, exercises.published_version_id, exercises.archived_at, exercises.scope, exercises.owner_event_id, exercises.access_level, exercises.origin_event_id, exercises.forked_from_exercise_id, exercises.forked_from_version_id, listed.status
FROM listed
JOIN exercises USING (id)
WHERE ($1::text = '' OR listed.status = $1::text)
ORDER BY
  CASE WHEN $2::text = 'name' AND $3::text = 'asc' THEN lower(name) END ASC,
  CASE WHEN $2::text = 'name' AND $3::text = 'desc' THEN lower(name) END DESC,
  CASE WHEN $2::text = 'tags' AND $3::text = 'asc' THEN lower(array_to_string(tags, ',')) END ASC,
  CASE WHEN $2::text = 'tags' AND $3::text = 'desc' THEN lower(array_to_string(tags, ',')) END DESC,
  -- Status rank: none < draft_only < changed < published < archived.
  CASE WHEN $2::text = 'status' AND $3::text = 'asc' THEN
    array_position(ARRAY ['none', 'draft_only', 'changed', 'published', 'archived'], listed.status) END ASC,
  CASE WHEN $2::text = 'status' AND $3::text = 'desc' THEN
    array_position(ARRAY ['none', 'draft_only', 'changed', 'published', 'archived'], listed.status) END DESC,
  CASE WHEN $2::text = 'updated' AND $3::text = 'asc' THEN updated_at END ASC,
  CASE WHEN $2::text = 'updated' AND $3::text = 'desc' THEN updated_at END DESC,
  exercises.updated_at DESC, exercises.id DESC
LIMIT $5 OFFSET $4
`

type ListExercisesPageParams struct {
	Status         string        `json:"status"`
	SortBy         string        `json:"sort_by"`
	SortDir        string        `json:"sort_dir"`
	OffsetVal      int32         `json:"offset_val"`
	LimitVal       int32         `json:"limit_val"`
	ViewerID       uuid.NullUUID `json:"viewer_id"`
	Search         string        `json:"search"`
	Tags           []string      `json:"tags"`
	Archived       string        `json:"archived"`
	Scope          string        `json:"scope"`
	EventIds       []uuid.UUID   `json:"event_ids"`
	Infrastructure string        `json:"infrastructure"`
}

type ListExercisesPageRow struct {
	Exercise Exercise `json:"exercise"`
	Status   string   `json:"status"`
}

// status is the single derived catalog status (exercise_status); the working
// copy counts only for readers who may see it (admins, members of the owner
// event) — for the others a catalog exercise is simply "published".
func (q *Queries) ListExercisesPage(ctx context.Context, arg ListExercisesPageParams) ([]ListExercisesPageRow, error) {
	rows, err := q.db.Query(ctx, listExercisesPage,
		arg.Status,
		arg.SortBy,
		arg.SortDir,
		arg.OffsetVal,
		arg.LimitVal,
		arg.ViewerID,
		arg.Search,
		arg.Tags,
		arg.Archived,
		arg.Scope,
		arg.EventIds,
		arg.Infrastructure,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExercisesPageRow{}
	for rows.Next() {
		var i ListExercisesPageRow
		if err := rows.Scan(
			&i.Exercise.ID,
			&i.Exercise.Name,
			&i.Exercise.Description,
			&i.Exercise.Tags,
			&i.Exercise.CreatedAt,
			&i.Exercise.CreatedBy,
			&i.Exercise.UpdatedAt,
			&i.Exercise.UpdatedBy,
			&i.Exercise.DraftVersionID,
			&i.Exercise.PublishedVersionID,
			&i.Exercise.ArchivedAt,
			&i.Exercise.Scope,
			&i.Exercise.OwnerEventID,
			&i.Exercise.AccessLevel,
			&i.Exercise.OriginEventID,
			&i.Exercise.ForkedFromExerciseID,
			&i.Exercise.ForkedFromVersionID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileExerciseIDs = `-- name: ListFileExerciseIDs :many
SELECT DISTINCT version.exercise_id
FROM file_references reference
JOIN exercise_versions version ON version.id = reference.ref_id
WHERE reference.file_id = $1
  AND reference.ref_type = $2
`

type ListFileExerciseIDsParams struct {
	FileID  uuid.UUID `json:"file_id"`
	RefType string    `json:"ref_type"`
}

// Exercises whose versions reference a file (attachment download policy).
func (q *Queries) ListFileExerciseIDs(ctx context.Context, arg ListFileExerciseIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFileExerciseIDs, arg.FileID, arg.RefType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var exercise_id uuid.UUID
		if err := rows.Scan(&exercise_id); err != nil {
			return nil, err
		}
		items = append(items, exercise_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileOwners = `-- name: ListFileOwners :many
SELECT id, created_by
FROM files
WHERE id = ANY ($1::uuid[])
`

type ListFileOwnersRow struct {
	ID        uuid.UUID     `json:"id"`
	CreatedBy uuid.NullUUID `json:"created_by"`
}

// Who uploaded each of the files: an exercise draft may attach only files its author uploaded or the exercise
// already holds.
func (q *Queries) ListFileOwners(ctx context.Context, ids []uuid.UUID) ([]ListFileOwnersRow, error) {
	rows, err := q.db.Query(ctx, listFileOwners, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFileOwnersRow{}
	for rows.Next() {
		var i ListFileOwnersRow
		if err := rows.Scan(&i.ID, &i.CreatedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEventMemberships = `-- name: ListUserEventMemberships :many
SELECT member.event_id, member.role,
       COALESCE(NULLIF(ev.internal_name, ''), ev.name)::text AS name,
       ev.tag, ev.infrastructure_allowed
FROM event_managers member
JOIN events ev ON ev.id = member.event_id
WHERE member.user_id = $1
ORDER BY lower(COALESCE(NULLIF(ev.internal_name, ''), ev.name)), ev.id
`

type ListUserEventMembershipsRow struct {
	EventID               uuid.UUID `json:"event_id"`
	Role                  int16     `json:"role"`
	Name                  string    `json:"name"`
	Tag                   string    `json:"tag"`
	InfrastructureAllowed bool      `json:"infrastructure_allowed"`
}

// The events a user is a member of, for the exercises app rights summary.
func (q *Queries) ListUserEventMemberships(ctx context.Context, userID uuid.UUID) ([]ListUserEventMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserEventMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserEventMembershipsRow{}
	for rows.Next() {
		var i ListUserEventMembershipsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Role,
			&i.Name,
			&i.Tag,
			&i.InfrastructureAllowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :execrows
UPDATE exercises
SET name        = $1,
    description = $2,
    tags        = $3,
    archived_at = $4,
    access_level = $5,
    updated_at  = $6,
    updated_by  = $7
WHERE id = $8
  -- Optimistic lock: 0 rows means "modified since read" (or gone).
  AND updated_at IS NOT DISTINCT FROM $9
`

type UpdateExerciseParams struct {
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	Tags              []string           `json:"tags"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	AccessLevel       int16              `json:"access_level"`
	UpdatedAt         time.Time          `json:"updated_at"`
	UpdatedBy         uuid.NullUUID      `json:"updated_by"`
	ID                uuid.UUID          `json:"id"`
	ExpectedUpdatedAt time.Time          `json:"expected_updated_at"`
}

// Whole-identity write. Deliberately excludes draft_version_id /
// published_version_id (owned by the lifecycle CTEs — including them here
// would race a concurrent publish) and created_at/created_by (immutable).
func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExercise,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.ArchivedAt,
		arg.AccessLevel,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
