// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercise_resource_elevations.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExerciseResourceElevation = `-- name: CreateExerciseResourceElevation :exec
INSERT INTO exercise_resource_elevations (id, exercise_id, version_id, status, reason, requested, requested_by, requested_at)
VALUES ($1, $2, $3, 0, $4, $5, $6, $7)
`

type CreateExerciseResourceElevationParams struct {
	ID          uuid.UUID     `json:"id"`
	ExerciseID  uuid.UUID     `json:"exercise_id"`
	VersionID   uuid.NullUUID `json:"version_id"`
	Reason      string        `json:"reason"`
	Requested   []byte        `json:"requested"`
	RequestedBy uuid.NullUUID `json:"requested_by"`
	RequestedAt time.Time     `json:"requested_at"`
}

// Timestamps and the id come from the domain factory. The partial unique index allows one pending request per
// exercise.
func (q *Queries) CreateExerciseResourceElevation(ctx context.Context, arg CreateExerciseResourceElevationParams) error {
	_, err := q.db.Exec(ctx, createExerciseResourceElevation,
		arg.ID,
		arg.ExerciseID,
		arg.VersionID,
		arg.Reason,
		arg.Requested,
		arg.RequestedBy,
		arg.RequestedAt,
	)
	return err
}

const decideExerciseResourceElevation = `-- name: DecideExerciseResourceElevation :execrows
UPDATE exercise_resource_elevations
SET status        = $1,
    approved      = $2,
    decision_note = $3,
    decided_by    = $4,
    decided_at    = $5
WHERE id = $6
  AND status = 0
`

type DecideExerciseResourceElevationParams struct {
	Status       int16              `json:"status"`
	Approved     []byte             `json:"approved"`
	DecisionNote string             `json:"decision_note"`
	DecidedBy    uuid.NullUUID      `json:"decided_by"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	ID           uuid.UUID          `json:"id"`
}

// Only a pending request can be decided; 0 rows: it was decided meanwhile.
func (q *Queries) DecideExerciseResourceElevation(ctx context.Context, arg DecideExerciseResourceElevationParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideExerciseResourceElevation,
		arg.Status,
		arg.Approved,
		arg.DecisionNote,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExerciseResourceElevation = `-- name: GetExerciseResourceElevation :one
SELECT id, exercise_id, version_id, status, reason, requested, approved, decision_note, requested_by, requested_at, decided_by, decided_at
FROM exercise_resource_elevations
WHERE id = $1
`

func (q *Queries) GetExerciseResourceElevation(ctx context.Context, id uuid.UUID) (ExerciseResourceElevation, error) {
	row := q.db.QueryRow(ctx, getExerciseResourceElevation, id)
	var i ExerciseResourceElevation
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.VersionID,
		&i.Status,
		&i.Reason,
		&i.Requested,
		&i.Approved,
		&i.DecisionNote,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const getLatestExerciseResourceElevation = `-- name: GetLatestExerciseResourceElevation :one
SELECT id, exercise_id, version_id, status, reason, requested, approved, decision_note, requested_by, requested_at, decided_by, decided_at
FROM exercise_resource_elevations
WHERE exercise_id = $1
ORDER BY (status = 0) DESC, requested_at DESC, id DESC
LIMIT 1
`

// The open request of the exercise, else its latest decided one.
func (q *Queries) GetLatestExerciseResourceElevation(ctx context.Context, exerciseID uuid.UUID) (ExerciseResourceElevation, error) {
	row := q.db.QueryRow(ctx, getLatestExerciseResourceElevation, exerciseID)
	var i ExerciseResourceElevation
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.VersionID,
		&i.Status,
		&i.Reason,
		&i.Requested,
		&i.Approved,
		&i.DecisionNote,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const listApprovedExerciseResourceElevations = `-- name: ListApprovedExerciseResourceElevations :many
SELECT exercise_id, approved
FROM exercise_resource_elevations
WHERE exercise_id = ANY ($1::uuid[])
  AND status = 1
  AND approved IS NOT NULL
`

type ListApprovedExerciseResourceElevationsRow struct {
	ExerciseID uuid.UUID `json:"exercise_id"`
	Approved   []byte    `json:"approved"`
}

// The approved values of every approved elevation of the given exercises.
func (q *Queries) ListApprovedExerciseResourceElevations(ctx context.Context, exerciseIds []uuid.UUID) ([]ListApprovedExerciseResourceElevationsRow, error) {
	rows, err := q.db.Query(ctx, listApprovedExerciseResourceElevations, exerciseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedExerciseResourceElevationsRow{}
	for rows.Next() {
		var i ListApprovedExerciseResourceElevationsRow
		if err := rows.Scan(&i.ExerciseID, &i.Approved); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseResourceElevations = `-- name: ListExerciseResourceElevations :many
SELECT elevation.id, elevation.exercise_id, elevation.version_id, elevation.status, elevation.reason, elevation.requested, elevation.approved, elevation.decision_note, elevation.requested_by, elevation.requested_at, elevation.decided_by, elevation.decided_at, exercise.name AS exercise_name
FROM exercise_resource_elevations elevation
         JOIN exercises exercise ON exercise.id = elevation.exercise_id
WHERE ($1::smallint IS NULL OR elevation.status = $1::smallint)
  AND ($2::uuid IS NULL OR elevation.exercise_id = $2::uuid)
ORDER BY elevation.requested_at DESC, elevation.id DESC
`

type ListExerciseResourceElevationsParams struct {
	Status     pgtype.Int2   `json:"status"`
	ExerciseID uuid.NullUUID `json:"exercise_id"`
}

type ListExerciseResourceElevationsRow struct {
	ID           uuid.UUID          `json:"id"`
	ExerciseID   uuid.UUID          `json:"exercise_id"`
	VersionID    uuid.NullUUID      `json:"version_id"`
	Status       int16              `json:"status"`
	Reason       string             `json:"reason"`
	Requested    []byte             `json:"requested"`
	Approved     []byte             `json:"approved"`
	DecisionNote string             `json:"decision_note"`
	RequestedBy  uuid.NullUUID      `json:"requested_by"`
	RequestedAt  time.Time          `json:"requested_at"`
	DecidedBy    uuid.NullUUID      `json:"decided_by"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	ExerciseName string             `json:"exercise_name"`
}

// Newest first; status and exercise narrow the list (a null argument does not filter).
func (q *Queries) ListExerciseResourceElevations(ctx context.Context, arg ListExerciseResourceElevationsParams) ([]ListExerciseResourceElevationsRow, error) {
	rows, err := q.db.Query(ctx, listExerciseResourceElevations, arg.Status, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExerciseResourceElevationsRow{}
	for rows.Next() {
		var i ListExerciseResourceElevationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.VersionID,
			&i.Status,
			&i.Reason,
			&i.Requested,
			&i.Approved,
			&i.DecisionNote,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
