// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lab_traffic.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyLabTrafficTouch = `-- name: ApplyLabTrafficTouch :exec
INSERT INTO event_lab_touches (id, event_id, team_id, user_id, event_challenge_id, surface,
                               attempts_count, lab_initiated_attempts_count, first_seen_at, last_seen_at, first_responded_at,
                               packets_out, packets_in, bytes_out, bytes_in)
VALUES ($1, $2, $3, $4::uuid, $5, $6,
        $7, $8, $9::timestamptz, $10::timestamptz, $11::timestamptz,
        $12, $13, $14, $15)
ON CONFLICT (event_id, team_id, user_id, event_challenge_id, surface) WHERE user_id IS NOT NULL
DO UPDATE SET
    attempts_count     = GREATEST(event_lab_touches.attempts_count, EXCLUDED.attempts_count),
    lab_initiated_attempts_count = GREATEST(event_lab_touches.lab_initiated_attempts_count, EXCLUDED.lab_initiated_attempts_count),
    first_seen_at      = LEAST(event_lab_touches.first_seen_at, EXCLUDED.first_seen_at),
    last_seen_at       = GREATEST(event_lab_touches.last_seen_at, EXCLUDED.last_seen_at),
    first_responded_at = LEAST(event_lab_touches.first_responded_at, EXCLUDED.first_responded_at),
    packets_out        = GREATEST(event_lab_touches.packets_out, EXCLUDED.packets_out),
    packets_in         = GREATEST(event_lab_touches.packets_in, EXCLUDED.packets_in),
    bytes_out          = GREATEST(event_lab_touches.bytes_out, EXCLUDED.bytes_out),
    bytes_in           = GREATEST(event_lab_touches.bytes_in, EXCLUDED.bytes_in)
`

type ApplyLabTrafficTouchParams struct {
	ID                        uuid.UUID          `json:"id"`
	EventID                   uuid.UUID          `json:"event_id"`
	TeamID                    uuid.UUID          `json:"team_id"`
	UserID                    uuid.UUID          `json:"user_id"`
	EventChallengeID          uuid.UUID          `json:"event_challenge_id"`
	Surface                   string             `json:"surface"`
	AttemptsCount             int64              `json:"attempts_count"`
	LabInitiatedAttemptsCount int64              `json:"lab_initiated_attempts_count"`
	FirstSeenAt               pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt                pgtype.Timestamptz `json:"last_seen_at"`
	FirstRespondedAt          pgtype.Timestamptz `json:"first_responded_at"`
	PacketsOut                int64              `json:"packets_out"`
	PacketsIn                 int64              `json:"packets_in"`
	BytesOut                  int64              `json:"bytes_out"`
	BytesIn                   int64              `json:"bytes_in"`
}

// Overwrites the final row of a user x lab x access type with the collector's
// cumulative values. Totals never go down (a stale resend cannot lower them),
// first is min, last is max, first_responded_at the earliest answer.
func (q *Queries) ApplyLabTrafficTouch(ctx context.Context, arg ApplyLabTrafficTouchParams) error {
	_, err := q.db.Exec(ctx, applyLabTrafficTouch,
		arg.ID,
		arg.EventID,
		arg.TeamID,
		arg.UserID,
		arg.EventChallengeID,
		arg.Surface,
		arg.AttemptsCount,
		arg.LabInitiatedAttemptsCount,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.FirstRespondedAt,
		arg.PacketsOut,
		arg.PacketsIn,
		arg.BytesOut,
		arg.BytesIn,
	)
	return err
}

const createLabTrafficCoverage = `-- name: CreateLabTrafficCoverage :exec
INSERT INTO lab_traffic_coverage (id, event_id, team_id, surface, source, boot_id, covered_from, covered_to, partial, explicit)
SELECT $1, e.id, $2, $3, $4, $5,
       $6::timestamptz, $7::timestamptz, $8::boolean, $9::boolean
FROM events e
WHERE e.id = $10
`

type CreateLabTrafficCoverageParams struct {
	ID          uuid.UUID `json:"id"`
	TeamID      uuid.UUID `json:"team_id"`
	Surface     string    `json:"surface"`
	Source      string    `json:"source"`
	BootID      string    `json:"boot_id"`
	CoveredFrom time.Time `json:"covered_from"`
	CoveredTo   time.Time `json:"covered_to"`
	Partial     bool      `json:"partial"`
	Explicit    bool      `json:"explicit"`
	EventID     uuid.UUID `json:"event_id"`
}

// A no-op for an event that no longer exists (a stale group).
func (q *Queries) CreateLabTrafficCoverage(ctx context.Context, arg CreateLabTrafficCoverageParams) error {
	_, err := q.db.Exec(ctx, createLabTrafficCoverage,
		arg.ID,
		arg.TeamID,
		arg.Surface,
		arg.Source,
		arg.BootID,
		arg.CoveredFrom,
		arg.CoveredTo,
		arg.Partial,
		arg.Explicit,
		arg.EventID,
	)
	return err
}

const extendLabTrafficCoverage = `-- name: ExtendLabTrafficCoverage :execrows
UPDATE lab_traffic_coverage
SET covered_from = LEAST(covered_from, $1::timestamptz),
    covered_to   = GREATEST(covered_to, $2::timestamptz)
WHERE id = (SELECT s.id
            FROM lab_traffic_coverage s
            WHERE s.event_id = $3
              AND s.team_id = $4
              AND s.surface = $5
              AND s.source = $6
              AND s.boot_id = $7
              AND s.partial = $8
              AND s.explicit = $9
              AND s.covered_to >= $1::timestamptz - make_interval(secs => $10::double precision)
              AND s.covered_from <= $2::timestamptz + make_interval(secs => $10::double precision)
            ORDER BY s.covered_to DESC
            LIMIT 1)
`

type ExtendLabTrafficCoverageParams struct {
	CoveredFrom      time.Time `json:"covered_from"`
	CoveredTo        time.Time `json:"covered_to"`
	EventID          uuid.UUID `json:"event_id"`
	TeamID           uuid.UUID `json:"team_id"`
	Surface          string    `json:"surface"`
	Source           string    `json:"source"`
	BootID           string    `json:"boot_id"`
	Partial          bool      `json:"partial"`
	Explicit         bool      `json:"explicit"`
	ToleranceSeconds float64   `json:"tolerance_seconds"`
}

// Grows the latest segment of the same collector boot when the new span joins
// it (within the tolerance); zero rows means a new segment is needed.
func (q *Queries) ExtendLabTrafficCoverage(ctx context.Context, arg ExtendLabTrafficCoverageParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendLabTrafficCoverage,
		arg.CoveredFrom,
		arg.CoveredTo,
		arg.EventID,
		arg.TeamID,
		arg.Surface,
		arg.Source,
		arg.BootID,
		arg.Partial,
		arg.Explicit,
		arg.ToleranceSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLabDeployedSince = `-- name: GetLabDeployedSince :one
SELECT COALESCE(MIN(deployed_at), '0001-01-01 00:00:00+00'::timestamptz)::timestamptz AS deployed_at
FROM lab_bindings
WHERE event_id = $1
  AND event_team_id = $2
  AND event_challenge_id = $3
`

type GetLabDeployedSinceParams struct {
	EventID          uuid.UUID `json:"event_id"`
	EventTeamID      uuid.UUID `json:"event_team_id"`
	EventChallengeID uuid.UUID `json:"event_challenge_id"`
}

// The earliest moment a lab of this task existed for the team; 0001-01-01 when
// it was never deployed.
func (q *Queries) GetLabDeployedSince(ctx context.Context, arg GetLabDeployedSinceParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, getLabDeployedSince, arg.EventID, arg.EventTeamID, arg.EventChallengeID)
	var deployed_at time.Time
	err := row.Scan(&deployed_at)
	return deployed_at, err
}

const isUserInEventTeam = `-- name: IsUserInEventTeam :one
SELECT EXISTS (SELECT 1
               FROM event_participants
               WHERE event_id = $1
                 AND team_id = $2
                 AND user_id = $3) AS member
`

type IsUserInEventTeamParams struct {
	EventID uuid.UUID     `json:"event_id"`
	TeamID  uuid.NullUUID `json:"team_id"`
	UserID  uuid.UUID     `json:"user_id"`
}

func (q *Queries) IsUserInEventTeam(ctx context.Context, arg IsUserInEventTeamParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInEventTeam, arg.EventID, arg.TeamID, arg.UserID)
	var member bool
	err := row.Scan(&member)
	return member, err
}

const listLabTrafficCoverage = `-- name: ListLabTrafficCoverage :many
SELECT surface, covered_from, covered_to, partial, explicit
FROM lab_traffic_coverage
WHERE event_id = $1
  AND team_id = $2
  AND covered_to >= $3::timestamptz
  AND covered_from <= $4::timestamptz
ORDER BY surface, covered_from
`

type ListLabTrafficCoverageParams struct {
	EventID uuid.UUID `json:"event_id"`
	TeamID  uuid.UUID `json:"team_id"`
	Since   time.Time `json:"since"`
	Until   time.Time `json:"until"`
}

type ListLabTrafficCoverageRow struct {
	Surface     string    `json:"surface"`
	CoveredFrom time.Time `json:"covered_from"`
	CoveredTo   time.Time `json:"covered_to"`
	Partial     bool      `json:"partial"`
	Explicit    bool      `json:"explicit"`
}

// Spans of a team that overlap [since, until].
func (q *Queries) ListLabTrafficCoverage(ctx context.Context, arg ListLabTrafficCoverageParams) ([]ListLabTrafficCoverageRow, error) {
	rows, err := q.db.Query(ctx, listLabTrafficCoverage,
		arg.EventID,
		arg.TeamID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabTrafficCoverageRow{}
	for rows.Next() {
		var i ListLabTrafficCoverageRow
		if err := rows.Scan(
			&i.Surface,
			&i.CoveredFrom,
			&i.CoveredTo,
			&i.Partial,
			&i.Explicit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeEventLabTouches = `-- name: PurgeEventLabTouches :execrows
DELETE FROM event_lab_touches
WHERE id IN (SELECT t.id
             FROM event_lab_touches t
             JOIN events e ON e.id = t.event_id
             WHERE e.lifecycle_configured
               AND LEAST(e.manual_finished_at, e.finish_at) < $1::timestamptz
             LIMIT $2
             FOR UPDATE OF t SKIP LOCKED)
`

type PurgeEventLabTouchesParams struct {
	EndedBefore time.Time `json:"ended_before"`
	BatchSize   int32     `json:"batch_size"`
}

// Aggregates of events that ended before the cutoff.
func (q *Queries) PurgeEventLabTouches(ctx context.Context, arg PurgeEventLabTouchesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEventLabTouches, arg.EndedBefore, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeEventLabTrafficCoverage = `-- name: PurgeEventLabTrafficCoverage :execrows
DELETE FROM lab_traffic_coverage
WHERE id IN (SELECT c.id
             FROM lab_traffic_coverage c
             JOIN events e ON e.id = c.event_id
             WHERE e.lifecycle_configured
               AND LEAST(e.manual_finished_at, e.finish_at) < $1::timestamptz
             LIMIT $2
             FOR UPDATE OF c SKIP LOCKED)
`

type PurgeEventLabTrafficCoverageParams struct {
	EndedBefore time.Time `json:"ended_before"`
	BatchSize   int32     `json:"batch_size"`
}

func (q *Queries) PurgeEventLabTrafficCoverage(ctx context.Context, arg PurgeEventLabTrafficCoverageParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEventLabTrafficCoverage, arg.EndedBefore, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const summarizeLabTouches = `-- name: SummarizeLabTouches :many
SELECT surface,
       LEAST(COALESCE(SUM(attempts_count), 0), 9223372036854775807)::bigint AS attempts,
       LEAST(COALESCE(SUM(lab_initiated_attempts_count), 0), 9223372036854775807)::bigint AS lab_initiated_attempts,
       -- The repository maps year one back to the compatible zero-valued
       -- model edge. Persisted participant dates remain SQL NULL.
       COALESCE(MIN(first_seen_at), '0001-01-01 00:00:00+00'::timestamptz)::timestamptz AS first_seen_at,
       COALESCE(MIN(first_responded_at), '0001-01-01 00:00:00+00'::timestamptz)::timestamptz AS first_responded_at,
       LEAST(COALESCE(SUM(packets_out), 0), 9223372036854775807)::bigint AS packets_out,
       LEAST(COALESCE(SUM(packets_in), 0), 9223372036854775807)::bigint AS packets_in,
       LEAST(COALESCE(SUM(bytes_out), 0), 9223372036854775807)::bigint AS bytes_out,
       LEAST(COALESCE(SUM(bytes_in), 0), 9223372036854775807)::bigint       AS bytes_in
FROM event_lab_touches
WHERE event_id = $1
  AND team_id = $2
  AND event_challenge_id = $3
  AND ($4::uuid = '00000000-0000-0000-0000-000000000000' OR user_id = $4::uuid)
  AND (first_seen_at IS NULL OR first_seen_at < $5::timestamptz)
GROUP BY surface, (first_seen_at IS NULL), (first_seen_at IS NULL AND attempts_count = 0 AND lab_initiated_attempts_count > 0)
`

type SummarizeLabTouchesParams struct {
	EventID          uuid.UUID `json:"event_id"`
	TeamID           uuid.UUID `json:"team_id"`
	EventChallengeID uuid.UUID `json:"event_challenge_id"`
	UserID           uuid.UUID `json:"user_id"`
	Before           time.Time `json:"before"`
}

type SummarizeLabTouchesRow struct {
	Surface              string    `json:"surface"`
	Attempts             int64     `json:"attempts"`
	LabInitiatedAttempts int64     `json:"lab_initiated_attempts"`
	FirstSeenAt          time.Time `json:"first_seen_at"`
	FirstRespondedAt     time.Time `json:"first_responded_at"`
	PacketsOut           int64     `json:"packets_out"`
	PacketsIn            int64     `json:"packets_in"`
	BytesOut             int64     `json:"bytes_out"`
	BytesIn              int64     `json:"bytes_in"`
}

// What a user (or, with a nil user, anybody in the team) did against one task
// before a moment. Keep lab-only rows separate from participant observations:
// their packets cannot supply missing participant response evidence.
// A teammate's known date must not hide another participant's missing date.
func (q *Queries) SummarizeLabTouches(ctx context.Context, arg SummarizeLabTouchesParams) ([]SummarizeLabTouchesRow, error) {
	rows, err := q.db.Query(ctx, summarizeLabTouches,
		arg.EventID,
		arg.TeamID,
		arg.EventChallengeID,
		arg.UserID,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeLabTouchesRow{}
	for rows.Next() {
		var i SummarizeLabTouchesRow
		if err := rows.Scan(
			&i.Surface,
			&i.Attempts,
			&i.LabInitiatedAttempts,
			&i.FirstSeenAt,
			&i.FirstRespondedAt,
			&i.PacketsOut,
			&i.PacketsIn,
			&i.BytesOut,
			&i.BytesIn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
