// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lab_bindings.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLabBinding = `-- name: CreateLabBinding :one
INSERT INTO lab_bindings (id,event_id,event_team_id,event_challenge_id,lab_group_name,lab_name,created_at,generation)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (event_team_id, event_challenge_id) DO NOTHING
RETURNING id, event_id, event_team_id, lab_group_name, lab_name, created_at, readiness, event_challenge_id, generation, deployed_at, failure_reason
`

type CreateLabBindingParams struct {
	ID               uuid.UUID `json:"id"`
	EventID          uuid.UUID `json:"event_id"`
	EventTeamID      uuid.UUID `json:"event_team_id"`
	EventChallengeID uuid.UUID `json:"event_challenge_id"`
	LabGroupName     string    `json:"lab_group_name"`
	LabName          string    `json:"lab_name"`
	CreatedAt        time.Time `json:"created_at"`
	Generation       int32     `json:"generation"`
}

func (q *Queries) CreateLabBinding(ctx context.Context, arg CreateLabBindingParams) (LabBinding, error) {
	row := q.db.QueryRow(ctx, createLabBinding,
		arg.ID,
		arg.EventID,
		arg.EventTeamID,
		arg.EventChallengeID,
		arg.LabGroupName,
		arg.LabName,
		arg.CreatedAt,
		arg.Generation,
	)
	var i LabBinding
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventTeamID,
		&i.LabGroupName,
		&i.LabName,
		&i.CreatedAt,
		&i.Readiness,
		&i.EventChallengeID,
		&i.Generation,
		&i.DeployedAt,
		&i.FailureReason,
	)
	return i, err
}

const getLabBinding = `-- name: GetLabBinding :one
SELECT id, event_id, event_team_id, lab_group_name, lab_name, created_at, readiness, event_challenge_id, generation, deployed_at, failure_reason FROM lab_bindings WHERE event_team_id = $1 AND event_challenge_id = $2
`

type GetLabBindingParams struct {
	EventTeamID      uuid.UUID `json:"event_team_id"`
	EventChallengeID uuid.UUID `json:"event_challenge_id"`
}

func (q *Queries) GetLabBinding(ctx context.Context, arg GetLabBindingParams) (LabBinding, error) {
	row := q.db.QueryRow(ctx, getLabBinding, arg.EventTeamID, arg.EventChallengeID)
	var i LabBinding
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventTeamID,
		&i.LabGroupName,
		&i.LabName,
		&i.CreatedAt,
		&i.Readiness,
		&i.EventChallengeID,
		&i.Generation,
		&i.DeployedAt,
		&i.FailureReason,
	)
	return i, err
}

const listPendingEventLabBindings = `-- name: ListPendingEventLabBindings :many
SELECT lb.id, lb.event_team_id, lb.event_challenge_id, lb.lab_group_name, lb.lab_name,
       lb.generation, lb.deployed_at, lb.created_at,
       tc.variant_index, ee.exercise_version_id
FROM lab_bindings lb
JOIN team_challenges tc ON tc.event_team_id = lb.event_team_id
                       AND tc.event_challenge_id = lb.event_challenge_id
JOIN event_challenges ec ON ec.id = lb.event_challenge_id
JOIN event_exercises ee ON ee.id = ec.event_exercise_id
WHERE lb.event_id = $1
  AND lb.readiness = 0
  -- Labs of a later stage wait until their deploy lead before they open.
  AND ee.id <> ALL ($2::uuid[])
ORDER BY lb.created_at, lb.id
`

type ListPendingEventLabBindingsParams struct {
	EventID           uuid.UUID   `json:"event_id"`
	NotDueExerciseIds []uuid.UUID `json:"not_due_exercise_ids"`
}

type ListPendingEventLabBindingsRow struct {
	ID                uuid.UUID          `json:"id"`
	EventTeamID       uuid.UUID          `json:"event_team_id"`
	EventChallengeID  uuid.UUID          `json:"event_challenge_id"`
	LabGroupName      string             `json:"lab_group_name"`
	LabName           string             `json:"lab_name"`
	Generation        int32              `json:"generation"`
	DeployedAt        pgtype.Timestamptz `json:"deployed_at"`
	CreatedAt         time.Time          `json:"created_at"`
	VariantIndex      int32              `json:"variant_index"`
	ExerciseVersionID uuid.UUID          `json:"exercise_version_id"`
}

// Stand engine work queue: every not yet ready Lab of one event together with
// the pinned version and variant needed to resolve its topology.
func (q *Queries) ListPendingEventLabBindings(ctx context.Context, arg ListPendingEventLabBindingsParams) ([]ListPendingEventLabBindingsRow, error) {
	rows, err := q.db.Query(ctx, listPendingEventLabBindings, arg.EventID, arg.NotDueExerciseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingEventLabBindingsRow{}
	for rows.Next() {
		var i ListPendingEventLabBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventTeamID,
			&i.EventChallengeID,
			&i.LabGroupName,
			&i.LabName,
			&i.Generation,
			&i.DeployedAt,
			&i.CreatedAt,
			&i.VariantIndex,
			&i.ExerciseVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingLabGroupCleanupRequests = `-- name: ListPendingLabGroupCleanupRequests :many
SELECT lab_group_name
FROM lab_group_cleanup_requests
WHERE destroyed_at IS NULL
ORDER BY requested_at, lab_group_name
`

func (q *Queries) ListPendingLabGroupCleanupRequests(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPendingLabGroupCleanupRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var lab_group_name string
		if err := rows.Scan(&lab_group_name); err != nil {
			return nil, err
		}
		items = append(items, lab_group_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamInfrastructureLabs = `-- name: ListTeamInfrastructureLabs :many
SELECT id, event_id, event_team_id, lab_group_name, lab_name, created_at, readiness, event_challenge_id, generation, deployed_at, failure_reason
FROM lab_bindings
WHERE event_team_id = $1
  AND readiness <> 3
ORDER BY lab_name
`

func (q *Queries) ListTeamInfrastructureLabs(ctx context.Context, eventTeamID uuid.UUID) ([]LabBinding, error) {
	rows, err := q.db.Query(ctx, listTeamInfrastructureLabs, eventTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LabBinding{}
	for rows.Next() {
		var i LabBinding
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventTeamID,
			&i.LabGroupName,
			&i.LabName,
			&i.CreatedAt,
			&i.Readiness,
			&i.EventChallengeID,
			&i.Generation,
			&i.DeployedAt,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawnLabBindings = `-- name: ListWithdrawnLabBindings :many
SELECT lb.id, lb.event_id, lb.event_team_id, lb.lab_group_name, lb.lab_name, lb.created_at, lb.readiness, lb.event_challenge_id, lb.generation, lb.deployed_at, lb.failure_reason
FROM lab_bindings lb
JOIN events e ON e.id = lb.event_id
WHERE e.withdraw_at IS NOT NULL
  AND e.withdraw_at <= $1
  AND lb.readiness <> 3
ORDER BY lb.lab_group_name, lb.id
`

// Lab groups are retained through finish, then become eligible for final teardown
// only once the event is withdrawn. A destroyed binding never re-enters this
// queue; a failed agent call leaves it eligible for River's next retry.
func (q *Queries) ListWithdrawnLabBindings(ctx context.Context, now pgtype.Timestamptz) ([]LabBinding, error) {
	rows, err := q.db.Query(ctx, listWithdrawnLabBindings, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LabBinding{}
	for rows.Next() {
		var i LabBinding
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventTeamID,
			&i.LabGroupName,
			&i.LabName,
			&i.CreatedAt,
			&i.Readiness,
			&i.EventChallengeID,
			&i.Generation,
			&i.DeployedAt,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventLabBindingsDestroyed = `-- name: MarkEventLabBindingsDestroyed :exec
UPDATE lab_bindings
SET readiness = 3
WHERE event_id = $1
  AND readiness <> 3
`

func (q *Queries) MarkEventLabBindingsDestroyed(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventLabBindingsDestroyed, eventID)
	return err
}

const markLabBindingDeployed = `-- name: MarkLabBindingDeployed :execrows
UPDATE lab_bindings
SET deployed_at = $1
WHERE id = $2
  AND generation = $3
  AND readiness = 0
  AND deployed_at IS NULL
`

type MarkLabBindingDeployedParams struct {
	DeployedAt pgtype.Timestamptz `json:"deployed_at"`
	ID         uuid.UUID          `json:"id"`
	Generation int32              `json:"generation"`
}

func (q *Queries) MarkLabBindingDeployed(ctx context.Context, arg MarkLabBindingDeployedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markLabBindingDeployed, arg.DeployedAt, arg.ID, arg.Generation)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markLabBindingDestroyed = `-- name: MarkLabBindingDestroyed :execrows
UPDATE lab_bindings
SET readiness = 3
WHERE id = $1
  AND readiness <> 3
`

func (q *Queries) MarkLabBindingDestroyed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markLabBindingDestroyed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markLabBindingFailedWithReason = `-- name: MarkLabBindingFailedWithReason :execrows
UPDATE lab_bindings
SET readiness = 2,
    failure_reason = $1
WHERE id = $2
  AND generation = $3
  AND readiness = 0
`

type MarkLabBindingFailedWithReasonParams struct {
	FailureReason pgtype.Text `json:"failure_reason"`
	ID            uuid.UUID   `json:"id"`
	Generation    int32       `json:"generation"`
}

func (q *Queries) MarkLabBindingFailedWithReason(ctx context.Context, arg MarkLabBindingFailedWithReasonParams) (int64, error) {
	result, err := q.db.Exec(ctx, markLabBindingFailedWithReason, arg.FailureReason, arg.ID, arg.Generation)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markLabGroupCleanupRequestDestroyed = `-- name: MarkLabGroupCleanupRequestDestroyed :execrows
UPDATE lab_group_cleanup_requests
SET destroyed_at = $1
WHERE lab_group_name = $2
  AND destroyed_at IS NULL
`

type MarkLabGroupCleanupRequestDestroyedParams struct {
	DestroyedAt  pgtype.Timestamptz `json:"destroyed_at"`
	LabGroupName string             `json:"lab_group_name"`
}

func (q *Queries) MarkLabGroupCleanupRequestDestroyed(ctx context.Context, arg MarkLabGroupCleanupRequestDestroyedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markLabGroupCleanupRequestDestroyed, arg.DestroyedAt, arg.LabGroupName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markStandLabReady = `-- name: MarkStandLabReady :one
WITH lab AS (
    UPDATE lab_bindings binding
    SET readiness = 1
    WHERE binding.id = $1
      AND binding.generation = $2
      AND binding.readiness = 0
    RETURNING binding.event_team_id, binding.event_challenge_id
), challenge AS (
    UPDATE team_challenges tc
    SET readiness = 1
    FROM lab
    WHERE tc.event_team_id = lab.event_team_id
      AND tc.event_challenge_id = lab.event_challenge_id
      AND tc.readiness = 0
    RETURNING tc.id
)
SELECT count(*)::bigint FROM lab
`

type MarkStandLabReadyParams struct {
	ID         uuid.UUID `json:"id"`
	Generation int32     `json:"generation"`
}

// A ready Lab makes its preparing team challenge ready in the same statement.
// Returns the number of bindings changed (0 = stale generation or repeat).
func (q *Queries) MarkStandLabReady(ctx context.Context, arg MarkStandLabReadyParams) (int64, error) {
	row := q.db.QueryRow(ctx, markStandLabReady, arg.ID, arg.Generation)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const queueTeamLabGroupCleanup = `-- name: QueueTeamLabGroupCleanup :execrows
INSERT INTO lab_group_cleanup_requests (lab_group_name, event_id, requested_at)
SELECT lab_group_name(team.event_id, team.id),
       team.event_id, $1
FROM event_teams team
WHERE team.id = $2
ON CONFLICT (lab_group_name) DO NOTHING
`

type QueueTeamLabGroupCleanupParams struct {
	RequestedAt time.Time `json:"requested_at"`
	EventTeamID uuid.UUID `json:"event_team_id"`
}

// Queue the deterministic team LabGroup even when no challenge Lab has been
// attached yet. The group may already contain VPN clients and a gateway.
func (q *Queries) QueueTeamLabGroupCleanup(ctx context.Context, arg QueueTeamLabGroupCleanupParams) (int64, error) {
	result, err := q.db.Exec(ctx, queueTeamLabGroupCleanup, arg.RequestedAt, arg.EventTeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queueWithdrawnEmptyLabGroups = `-- name: QueueWithdrawnEmptyLabGroups :exec
INSERT INTO lab_group_cleanup_requests (lab_group_name, event_id, requested_at)
SELECT lab_group_name(team.event_id, team.id),
       team.event_id, $1::timestamptz
FROM event_teams team
JOIN events event ON event.id = team.event_id
WHERE event.withdraw_at IS NOT NULL
  AND event.withdraw_at <= $1::timestamptz
  AND NOT EXISTS (SELECT 1 FROM lab_bindings lb WHERE lb.event_team_id = team.id)
ON CONFLICT (lab_group_name) DO NOTHING
`

// A team can own VPN clients and a gateway before it has any challenge Lab.
// On withdrawal, make those groups eligible for the same durable cleanup job.
func (q *Queries) QueueWithdrawnEmptyLabGroups(ctx context.Context, now time.Time) error {
	_, err := q.db.Exec(ctx, queueWithdrawnEmptyLabGroups, now)
	return err
}

const recreateLabBinding = `-- name: RecreateLabBinding :execrows
UPDATE lab_bindings
SET generation = generation + 1,
    lab_name = $1,
    readiness = 0,
    deployed_at = NULL,
    failure_reason = NULL
WHERE id = $2
  AND generation = $3
  AND readiness <> 3
`

type RecreateLabBindingParams struct {
	LabName    string    `json:"lab_name"`
	ID         uuid.UUID `json:"id"`
	Generation int32     `json:"generation"`
}

// A recreated Lab moves to the next generation under a new name, so the
// asynchronously deleted previous Lab never collides, and deploys again.
func (q *Queries) RecreateLabBinding(ctx context.Context, arg RecreateLabBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, recreateLabBinding, arg.LabName, arg.ID, arg.Generation)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetUnpublishedTeamChallengesForRecreate = `-- name: ResetUnpublishedTeamChallengesForRecreate :exec
UPDATE team_challenges tc
SET readiness = 0
FROM lab_bindings lb
WHERE lb.event_team_id = $1
  AND lb.readiness <> 3
  AND tc.event_team_id = lb.event_team_id
  AND tc.event_challenge_id = lb.event_challenge_id
  AND tc.readiness = 1
`

// Not yet published infrastructure challenges wait for the recreated Lab;
// already published ones stay on the team's board (the ACL still requires a
// ready Lab, so access returns only once the new Lab is ready).
func (q *Queries) ResetUnpublishedTeamChallengesForRecreate(ctx context.Context, eventTeamID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetUnpublishedTeamChallengesForRecreate, eventTeamID)
	return err
}

const updateLabBindingReadiness = `-- name: UpdateLabBindingReadiness :execrows
UPDATE lab_bindings
SET readiness = $1
WHERE id = $2
  AND readiness = $3
`

type UpdateLabBindingReadinessParams struct {
	Readiness         int16     `json:"readiness"`
	ID                uuid.UUID `json:"id"`
	ExpectedReadiness int16     `json:"expected_readiness"`
}

func (q *Queries) UpdateLabBindingReadiness(ctx context.Context, arg UpdateLabBindingReadinessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLabBindingReadiness, arg.Readiness, arg.ID, arg.ExpectedReadiness)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
