// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lab_monitoring_current.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const deleteStaleLabMonitoringCurrent = `-- name: DeleteStaleLabMonitoringCurrent :exec
DELETE FROM lab_monitoring_current
WHERE agent_id = $1
  AND updated_at < $2
`

type DeleteStaleLabMonitoringCurrentParams struct {
	AgentID string    `json:"agent_id"`
	Before  time.Time `json:"before"`
}

// A snapshot is the agent's full picture: groups it no longer reports are gone.
func (q *Queries) DeleteStaleLabMonitoringCurrent(ctx context.Context, arg DeleteStaleLabMonitoringCurrentParams) error {
	_, err := q.db.Exec(ctx, deleteStaleLabMonitoringCurrent, arg.AgentID, arg.Before)
	return err
}

const findEventTeamsByLabGroup = `-- name: FindEventTeamsByLabGroup :many
SELECT DISTINCT lb.event_id, lb.event_team_id
FROM lab_bindings lb
WHERE lb.lab_group_name = $1
ORDER BY lb.event_id, lb.event_team_id
`

type FindEventTeamsByLabGroupRow struct {
	EventID     uuid.UUID `json:"event_id"`
	EventTeamID uuid.UUID `json:"event_team_id"`
}

// Every event team bound to the lab group, whatever the event lifecycle: the
// current state must already be there when an event becomes active.
func (q *Queries) FindEventTeamsByLabGroup(ctx context.Context, labGroupName string) ([]FindEventTeamsByLabGroupRow, error) {
	rows, err := q.db.Query(ctx, findEventTeamsByLabGroup, labGroupName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindEventTeamsByLabGroupRow{}
	for rows.Next() {
		var i FindEventTeamsByLabGroupRow
		if err := rows.Scan(&i.EventID, &i.EventTeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLabMonitoringCurrent = `-- name: GetLabMonitoringCurrent :one
SELECT event_id, event_team_id, lab_group_name, agent_id, sequence, observed_at, updated_at, payload
FROM lab_monitoring_current
WHERE event_id = $1
  AND event_team_id = $2
  AND lab_group_name = $3
`

type GetLabMonitoringCurrentParams struct {
	EventID      uuid.UUID `json:"event_id"`
	EventTeamID  uuid.UUID `json:"event_team_id"`
	LabGroupName string    `json:"lab_group_name"`
}

func (q *Queries) GetLabMonitoringCurrent(ctx context.Context, arg GetLabMonitoringCurrentParams) (LabMonitoringCurrent, error) {
	row := q.db.QueryRow(ctx, getLabMonitoringCurrent, arg.EventID, arg.EventTeamID, arg.LabGroupName)
	var i LabMonitoringCurrent
	err := row.Scan(
		&i.EventID,
		&i.EventTeamID,
		&i.LabGroupName,
		&i.AgentID,
		&i.Sequence,
		&i.ObservedAt,
		&i.UpdatedAt,
		&i.Payload,
	)
	return i, err
}

const listEventLabMonitoringCurrent = `-- name: ListEventLabMonitoringCurrent :many
SELECT event_team_id, lab_group_name, payload
FROM lab_monitoring_current
WHERE event_id = $1
ORDER BY event_team_id, lab_group_name
`

type ListEventLabMonitoringCurrentRow struct {
	EventTeamID  uuid.UUID `json:"event_team_id"`
	LabGroupName string    `json:"lab_group_name"`
	Payload      []byte    `json:"payload"`
}

// The merged current state of every lab group of one event, for the organizers' stand list.
func (q *Queries) ListEventLabMonitoringCurrent(ctx context.Context, eventID uuid.UUID) ([]ListEventLabMonitoringCurrentRow, error) {
	rows, err := q.db.Query(ctx, listEventLabMonitoringCurrent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventLabMonitoringCurrentRow{}
	for rows.Next() {
		var i ListEventLabMonitoringCurrentRow
		if err := rows.Scan(&i.EventTeamID, &i.LabGroupName, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformLabMonitoringCurrent = `-- name: ListPlatformLabMonitoringCurrent :many
SELECT c.event_id, e.name AS event_name, c.event_team_id,
       event_team_public_name(t.individual, t.event_id, t.captain_id, t.name)::text AS team_name,
       t.moderators, c.lab_group_name, c.agent_id, c.sequence, c.observed_at, c.updated_at, c.payload
FROM lab_monitoring_current c
JOIN events e ON e.id = c.event_id
JOIN event_teams t ON t.id = c.event_team_id
WHERE ($1::boolean AND c.updated_at >= $2::timestamptz)
   OR (e.lifecycle_configured
       AND e.available_from <= $3::timestamptz
       AND (e.archive_at IS NULL OR e.archive_at > $3::timestamptz)
       AND e.start_at <= $3::timestamptz
       AND (e.finish_at IS NULL OR e.finish_at > $3::timestamptz)
       AND (e.manual_finished_at IS NULL OR e.manual_finished_at > $3::timestamptz)
       AND (e.withdraw_at IS NULL OR e.withdraw_at > $3::timestamptz))
ORDER BY e.name, team_name, c.lab_group_name
`

type ListPlatformLabMonitoringCurrentParams struct {
	IncludeRecent bool      `json:"include_recent"`
	RecentSince   time.Time `json:"recent_since"`
	Now           time.Time `json:"now"`
}

type ListPlatformLabMonitoringCurrentRow struct {
	EventID      uuid.UUID `json:"event_id"`
	EventName    string    `json:"event_name"`
	EventTeamID  uuid.UUID `json:"event_team_id"`
	TeamName     string    `json:"team_name"`
	Moderators   bool      `json:"moderators"`
	LabGroupName string    `json:"lab_group_name"`
	AgentID      string    `json:"agent_id"`
	Sequence     int64     `json:"sequence"`
	ObservedAt   time.Time `json:"observed_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Payload      []byte    `json:"payload"`
}

// Active events by default; include_recent also lists everything the runner
// touched since recent_since, whatever the event state.
func (q *Queries) ListPlatformLabMonitoringCurrent(ctx context.Context, arg ListPlatformLabMonitoringCurrentParams) ([]ListPlatformLabMonitoringCurrentRow, error) {
	rows, err := q.db.Query(ctx, listPlatformLabMonitoringCurrent, arg.IncludeRecent, arg.RecentSince, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformLabMonitoringCurrentRow{}
	for rows.Next() {
		var i ListPlatformLabMonitoringCurrentRow
		if err := rows.Scan(
			&i.EventID,
			&i.EventName,
			&i.EventTeamID,
			&i.TeamName,
			&i.Moderators,
			&i.LabGroupName,
			&i.AgentID,
			&i.Sequence,
			&i.ObservedAt,
			&i.UpdatedAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLabMonitoringCurrent = `-- name: UpsertLabMonitoringCurrent :exec
INSERT INTO lab_monitoring_current (event_id, event_team_id, lab_group_name, agent_id, sequence, observed_at, updated_at, payload)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
ON CONFLICT (event_id, event_team_id, lab_group_name) DO UPDATE
SET agent_id = EXCLUDED.agent_id,
    sequence = EXCLUDED.sequence,
    observed_at = EXCLUDED.observed_at,
    updated_at = EXCLUDED.updated_at,
    payload = EXCLUDED.payload
`

type UpsertLabMonitoringCurrentParams struct {
	EventID      uuid.UUID `json:"event_id"`
	EventTeamID  uuid.UUID `json:"event_team_id"`
	LabGroupName string    `json:"lab_group_name"`
	AgentID      string    `json:"agent_id"`
	Sequence     int64     `json:"sequence"`
	ObservedAt   time.Time `json:"observed_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Payload      []byte    `json:"payload"`
}

func (q *Queries) UpsertLabMonitoringCurrent(ctx context.Context, arg UpsertLabMonitoringCurrentParams) error {
	_, err := q.db.Exec(ctx, upsertLabMonitoringCurrent,
		arg.EventID,
		arg.EventTeamID,
		arg.LabGroupName,
		arg.AgentID,
		arg.Sequence,
		arg.ObservedAt,
		arg.UpdatedAt,
		arg.Payload,
	)
	return err
}
