// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_recipients.sql

package postgres

import (
	"context"

	"github.com/gofrs/uuid"
)

const listEventManagerUserIDs = `-- name: ListEventManagerUserIDs :many
SELECT user_id
FROM event_managers
WHERE event_id = $1
ORDER BY user_id
`

// Every management membership of the Event (owner, moderator, viewer).
func (q *Queries) ListEventManagerUserIDs(ctx context.Context, eventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEventManagerUserIDs, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventWriteManagerUserIDs = `-- name: ListEventWriteManagerUserIDs :many
SELECT user_id
FROM event_managers
WHERE event_id = $1
  AND role IN (0, 1)
ORDER BY user_id
`

// Owners and moderators: the memberships that may act on participants
// (viewers are read-only).
func (q *Queries) ListEventWriteManagerUserIDs(ctx context.Context, eventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEventWriteManagerUserIDs, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformAdminUserIDs = `-- name: ListPlatformAdminUserIDs :many
SELECT id
FROM users
WHERE role IN ('super_admin', 'admin')
  AND status = 'active'
  AND deleted_at IS NULL
ORDER BY id
`

// Active platform administrators (super admins and admins; read-only admin
// viewers cannot act on requests).
func (q *Queries) ListPlatformAdminUserIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPlatformAdminUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
