// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_settings.sql

package postgres

import (
	"context"

	"github.com/gofrs/uuid"
)

const getActiveChannels = `-- name: GetActiveChannels :many
SELECT g.channel
FROM notification_settings g
         LEFT JOIN notification_user_settings u
                   ON u.notification_type = g.notification_type
                       AND u.channel = g.channel
                       AND u.user_id = $1
WHERE g.notification_type = $2
  AND g.enabled
  AND (NOT g.user_can_change OR COALESCE(u.enabled, g.user_default))
ORDER BY g.channel
`

type GetActiveChannelsParams struct {
	UserID           uuid.UUID `json:"user_id"`
	NotificationType string    `json:"notification_type"`
}

func (q *Queries) GetActiveChannels(ctx context.Context, arg GetActiveChannelsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getActiveChannels, arg.UserID, arg.NotificationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var channel string
		if err := rows.Scan(&channel); err != nil {
			return nil, err
		}
		items = append(items, channel)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationSetting = `-- name: GetNotificationSetting :one
SELECT notification_type, channel, enabled, user_can_change, user_default
FROM notification_settings
WHERE notification_type = $1
  AND channel = $2
`

type GetNotificationSettingParams struct {
	NotificationType string `json:"notification_type"`
	Channel          string `json:"channel"`
}

func (q *Queries) GetNotificationSetting(ctx context.Context, arg GetNotificationSettingParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSetting, arg.NotificationType, arg.Channel)
	var i NotificationSetting
	err := row.Scan(
		&i.NotificationType,
		&i.Channel,
		&i.Enabled,
		&i.UserCanChange,
		&i.UserDefault,
	)
	return i, err
}

const listNotificationSettings = `-- name: ListNotificationSettings :many
SELECT notification_type, channel, enabled, user_can_change, user_default
FROM notification_settings
ORDER BY notification_type, channel
`

func (q *Queries) ListNotificationSettings(ctx context.Context) ([]NotificationSetting, error) {
	rows, err := q.db.Query(ctx, listNotificationSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationSetting{}
	for rows.Next() {
		var i NotificationSetting
		if err := rows.Scan(
			&i.NotificationType,
			&i.Channel,
			&i.Enabled,
			&i.UserCanChange,
			&i.UserDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSettings = `-- name: ListUserSettings :many
SELECT user_id, notification_type, channel, enabled
FROM notification_user_settings
WHERE user_id = $1
ORDER BY notification_type, channel
`

func (q *Queries) ListUserSettings(ctx context.Context, userID uuid.UUID) ([]NotificationUserSetting, error) {
	rows, err := q.db.Query(ctx, listUserSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationUserSetting{}
	for rows.Next() {
		var i NotificationUserSetting
		if err := rows.Scan(
			&i.UserID,
			&i.NotificationType,
			&i.Channel,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotificationSetting = `-- name: UpsertNotificationSetting :one
INSERT INTO notification_settings (notification_type, channel, enabled, user_can_change, user_default)
VALUES ($1, $2, $3, $4, $5) ON CONFLICT (notification_type, channel) DO
UPDATE
    SET enabled = EXCLUDED.enabled,
    user_can_change = EXCLUDED.user_can_change,
    user_default = EXCLUDED.user_default
    RETURNING notification_type, channel, enabled, user_can_change, user_default
`

type UpsertNotificationSettingParams struct {
	NotificationType string `json:"notification_type"`
	Channel          string `json:"channel"`
	Enabled          bool   `json:"enabled"`
	UserCanChange    bool   `json:"user_can_change"`
	UserDefault      bool   `json:"user_default"`
}

func (q *Queries) UpsertNotificationSetting(ctx context.Context, arg UpsertNotificationSettingParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, upsertNotificationSetting,
		arg.NotificationType,
		arg.Channel,
		arg.Enabled,
		arg.UserCanChange,
		arg.UserDefault,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.NotificationType,
		&i.Channel,
		&i.Enabled,
		&i.UserCanChange,
		&i.UserDefault,
	)
	return i, err
}

const upsertUserSetting = `-- name: UpsertUserSetting :exec
INSERT INTO notification_user_settings (user_id, notification_type, channel, enabled)
VALUES ($1, $2, $3, $4) ON CONFLICT (user_id, notification_type, channel) DO
UPDATE
    SET enabled = EXCLUDED.enabled
`

type UpsertUserSettingParams struct {
	UserID           uuid.UUID `json:"user_id"`
	NotificationType string    `json:"notification_type"`
	Channel          string    `json:"channel"`
	Enabled          bool      `json:"enabled"`
}

func (q *Queries) UpsertUserSetting(ctx context.Context, arg UpsertUserSettingParams) error {
	_, err := q.db.Exec(ctx, upsertUserSetting,
		arg.UserID,
		arg.NotificationType,
		arg.Channel,
		arg.Enabled,
	)
	return err
}
