// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_email_block_presets.sql

package postgres

import (
	"context"

	"github.com/gofrs/uuid"
)

const createEmailBlockPreset = `-- name: CreateEmailBlockPreset :one
INSERT INTO notification_email_block_presets (id, name, description, blocks)
VALUES ($1, $2, $3, $4) RETURNING id, name, description, blocks, created_at, updated_at
`

type CreateEmailBlockPresetParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Blocks      []byte    `json:"blocks"`
}

func (q *Queries) CreateEmailBlockPreset(ctx context.Context, arg CreateEmailBlockPresetParams) (NotificationEmailBlockPreset, error) {
	row := q.db.QueryRow(ctx, createEmailBlockPreset,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Blocks,
	)
	var i NotificationEmailBlockPreset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmailBlockPreset = `-- name: DeleteEmailBlockPreset :exec
DELETE
FROM notification_email_block_presets
WHERE id = $1
`

func (q *Queries) DeleteEmailBlockPreset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailBlockPreset, id)
	return err
}

const getEmailBlockPreset = `-- name: GetEmailBlockPreset :one
SELECT id, name, description, blocks, created_at, updated_at
FROM notification_email_block_presets
WHERE id = $1
`

func (q *Queries) GetEmailBlockPreset(ctx context.Context, id uuid.UUID) (NotificationEmailBlockPreset, error) {
	row := q.db.QueryRow(ctx, getEmailBlockPreset, id)
	var i NotificationEmailBlockPreset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailBlockPresets = `-- name: ListEmailBlockPresets :many
SELECT id, name, description, blocks, created_at, updated_at
FROM notification_email_block_presets
ORDER BY name
`

func (q *Queries) ListEmailBlockPresets(ctx context.Context) ([]NotificationEmailBlockPreset, error) {
	rows, err := q.db.Query(ctx, listEmailBlockPresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationEmailBlockPreset{}
	for rows.Next() {
		var i NotificationEmailBlockPreset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailBlockPreset = `-- name: UpdateEmailBlockPreset :one
UPDATE notification_email_block_presets
SET name        = $2,
    description = $3,
    blocks      = $4,
    updated_at  = now()
WHERE id = $1 RETURNING id, name, description, blocks, created_at, updated_at
`

type UpdateEmailBlockPresetParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Blocks      []byte    `json:"blocks"`
}

func (q *Queries) UpdateEmailBlockPreset(ctx context.Context, arg UpdateEmailBlockPresetParams) (NotificationEmailBlockPreset, error) {
	row := q.db.QueryRow(ctx, updateEmailBlockPreset,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Blocks,
	)
	var i NotificationEmailBlockPreset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
