// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: platform_settings.sql

package postgres

import (
	"context"
)

const getEmailTemplateBody = `-- name: GetEmailTemplateBody :one
select value
from platform_settings
where type = 'email_template_body'
  and key = $1
`

func (q *Queries) GetEmailTemplateBody(ctx context.Context, key string) (string, error) {
	row := q.queryRow(ctx, q.getEmailTemplateBodyStmt, getEmailTemplateBody, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getEmailTemplateSubject = `-- name: GetEmailTemplateSubject :one
select value
from platform_settings
where type = 'email_template_subject'
  and key = $1
`

func (q *Queries) GetEmailTemplateSubject(ctx context.Context, key string) (string, error) {
	row := q.queryRow(ctx, q.getEmailTemplateSubjectStmt, getEmailTemplateSubject, key)
	var value string
	err := row.Scan(&value)
	return value, err
}
