// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_lab_capacity_observations.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const createPlatformLabCapacityObservation = `-- name: CreatePlatformLabCapacityObservation :one
INSERT INTO platform_lab_capacity_observations (
    id, agent_id, sequence, observed_at, received_at, schema_version, snapshot, payload
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
)
ON CONFLICT (agent_id, sequence) DO NOTHING
RETURNING id, agent_id, sequence, observed_at, received_at, schema_version, snapshot, payload
`

type CreatePlatformLabCapacityObservationParams struct {
	ID            uuid.UUID `json:"id"`
	AgentID       string    `json:"agent_id"`
	Sequence      int64     `json:"sequence"`
	ObservedAt    time.Time `json:"observed_at"`
	ReceivedAt    time.Time `json:"received_at"`
	SchemaVersion int32     `json:"schema_version"`
	Snapshot      bool      `json:"snapshot"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) CreatePlatformLabCapacityObservation(ctx context.Context, arg CreatePlatformLabCapacityObservationParams) (PlatformLabCapacityObservation, error) {
	row := q.db.QueryRow(ctx, createPlatformLabCapacityObservation,
		arg.ID,
		arg.AgentID,
		arg.Sequence,
		arg.ObservedAt,
		arg.ReceivedAt,
		arg.SchemaVersion,
		arg.Snapshot,
		arg.Payload,
	)
	var i PlatformLabCapacityObservation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Sequence,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.SchemaVersion,
		&i.Snapshot,
		&i.Payload,
	)
	return i, err
}

const getPlatformLabCapacityObservationByAgentSequence = `-- name: GetPlatformLabCapacityObservationByAgentSequence :one
SELECT id, agent_id, sequence, observed_at, received_at, schema_version, snapshot, payload
FROM platform_lab_capacity_observations
WHERE agent_id = $1
  AND sequence = $2
`

type GetPlatformLabCapacityObservationByAgentSequenceParams struct {
	AgentID  string `json:"agent_id"`
	Sequence int64  `json:"sequence"`
}

func (q *Queries) GetPlatformLabCapacityObservationByAgentSequence(ctx context.Context, arg GetPlatformLabCapacityObservationByAgentSequenceParams) (PlatformLabCapacityObservation, error) {
	row := q.db.QueryRow(ctx, getPlatformLabCapacityObservationByAgentSequence, arg.AgentID, arg.Sequence)
	var i PlatformLabCapacityObservation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Sequence,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.SchemaVersion,
		&i.Snapshot,
		&i.Payload,
	)
	return i, err
}

const getPlatformLabCapacityObservationCursor = `-- name: GetPlatformLabCapacityObservationCursor :one
SELECT observed_at, id
FROM platform_lab_capacity_observations
WHERE id = $1
`

type GetPlatformLabCapacityObservationCursorRow struct {
	ObservedAt time.Time `json:"observed_at"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetPlatformLabCapacityObservationCursor(ctx context.Context, id uuid.UUID) (GetPlatformLabCapacityObservationCursorRow, error) {
	row := q.db.QueryRow(ctx, getPlatformLabCapacityObservationCursor, id)
	var i GetPlatformLabCapacityObservationCursorRow
	err := row.Scan(&i.ObservedAt, &i.ID)
	return i, err
}

const listLatestPlatformLabCapacityObservations = `-- name: ListLatestPlatformLabCapacityObservations :many
SELECT DISTINCT ON (agent_id) id, agent_id, sequence, observed_at, received_at, schema_version, snapshot, payload
FROM platform_lab_capacity_observations
ORDER BY agent_id, observed_at DESC, id DESC
`

func (q *Queries) ListLatestPlatformLabCapacityObservations(ctx context.Context) ([]PlatformLabCapacityObservation, error) {
	rows, err := q.db.Query(ctx, listLatestPlatformLabCapacityObservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformLabCapacityObservation{}
	for rows.Next() {
		var i PlatformLabCapacityObservation
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Sequence,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.SchemaVersion,
			&i.Snapshot,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformLabCapacityObservations = `-- name: ListPlatformLabCapacityObservations :many
SELECT id, agent_id, sequence, observed_at, received_at, schema_version, snapshot, payload
FROM platform_lab_capacity_observations
WHERE observed_at >= $1
  AND observed_at <= $2
  AND (observed_at, id) < ($3, $4::uuid)
ORDER BY observed_at DESC, id DESC
LIMIT $5
`

type ListPlatformLabCapacityObservationsParams struct {
	FromAt   time.Time `json:"from_at"`
	ToAt     time.Time `json:"to_at"`
	CursorAt time.Time `json:"cursor_at"`
	CursorID uuid.UUID `json:"cursor_id"`
	LimitVal int32     `json:"limit_val"`
}

func (q *Queries) ListPlatformLabCapacityObservations(ctx context.Context, arg ListPlatformLabCapacityObservationsParams) ([]PlatformLabCapacityObservation, error) {
	rows, err := q.db.Query(ctx, listPlatformLabCapacityObservations,
		arg.FromAt,
		arg.ToAt,
		arg.CursorAt,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformLabCapacityObservation{}
	for rows.Next() {
		var i PlatformLabCapacityObservation
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Sequence,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.SchemaVersion,
			&i.Snapshot,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
