// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_analytics_infrastructure.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const listPlatformInfraCapacity = `-- name: ListPlatformInfraCapacity :many
WITH raw AS (
    SELECT to_timestamp(floor(extract(epoch FROM o.observed_at) / $1::float8) * $1::float8) AS bucket,
           o.agent_id,
           COALESCE(o.payload ->> 'cpuQuotaMillicores', o.payload ->> 'allocatableCpuMillicores')   AS alloc_cpu,
           COALESCE(o.payload ->> 'cpuReservedMillicores', o.payload ->> 'requestedCpuMillicores')  AS req_cpu,
           COALESCE(o.payload ->> 'memoryQuotaBytes', o.payload ->> 'allocatableMemoryBytes')       AS alloc_mem,
           COALESCE(o.payload ->> 'memoryReservedBytes', o.payload ->> 'requestedMemoryBytes')      AS req_mem
    FROM platform_lab_capacity_observations o
    WHERE o.observed_at >= $2::timestamptz
      AND o.observed_at < $3::timestamptz
), obs AS (
    SELECT bucket, agent_id,
           CASE WHEN alloc_cpu ~ '^[0-9]+(\.[0-9]+)?$' THEN alloc_cpu::numeric END AS alloc_cpu,
           CASE WHEN req_cpu ~ '^[0-9]+(\.[0-9]+)?$' THEN req_cpu::numeric END     AS req_cpu,
           CASE WHEN alloc_mem ~ '^[0-9]+(\.[0-9]+)?$' THEN alloc_mem::numeric END AS alloc_mem,
           CASE WHEN req_mem ~ '^[0-9]+(\.[0-9]+)?$' THEN req_mem::numeric END     AS req_mem
    FROM raw
), per_agent AS (
    SELECT bucket, agent_id,
           avg(alloc_cpu) AS alloc_cpu, avg(req_cpu) AS req_cpu,
           avg(alloc_mem) AS alloc_mem, avg(req_mem) AS req_mem
    FROM obs
    WHERE alloc_cpu IS NOT NULL OR alloc_mem IS NOT NULL
    GROUP BY bucket, agent_id
)
SELECT bucket::timestamptz                              AS bucket_at,
       COALESCE(round(sum(alloc_cpu)), 0)::bigint       AS allocatable_cpu_millicores,
       COALESCE(round(sum(req_cpu)), 0)::bigint         AS requested_cpu_millicores,
       COALESCE(round(sum(alloc_mem)), 0)::bigint       AS allocatable_memory_bytes,
       COALESCE(round(sum(req_mem)), 0)::bigint         AS requested_memory_bytes,
       count(*)::bigint                                 AS agents
FROM per_agent
GROUP BY bucket
ORDER BY bucket
`

type ListPlatformInfraCapacityParams struct {
	StepSeconds float64   `json:"step_seconds"`
	FromAt      time.Time `json:"from_at"`
	ToAt        time.Time `json:"to_at"`
}

type ListPlatformInfraCapacityRow struct {
	BucketAt                 time.Time `json:"bucket_at"`
	AllocatableCpuMillicores int64     `json:"allocatable_cpu_millicores"`
	RequestedCpuMillicores   int64     `json:"requested_cpu_millicores"`
	AllocatableMemoryBytes   int64     `json:"allocatable_memory_bytes"`
	RequestedMemoryBytes     int64     `json:"requested_memory_bytes"`
	Agents                   int64     `json:"agents"`
}

// Capacity over time from the agents' capacity observations, downsampled to buckets of
// step_seconds (the caller picks the step so a period has at most about 300 points). Inside a bucket
// every agent contributes its average; the agents are then summed. An agent reports the platform's
// own tenant view: the quota is the capacity and what its pods request is the reservation
// (cpuQuotaMillicores / cpuReservedMillicores, memoryQuotaBytes / memoryReservedBytes); samples
// recorded before tenancy carry allocatable* / requested* and are read as before. The payload
// carries int64 values as JSON numbers or numeric strings, both are read.
func (q *Queries) ListPlatformInfraCapacity(ctx context.Context, arg ListPlatformInfraCapacityParams) ([]ListPlatformInfraCapacityRow, error) {
	rows, err := q.db.Query(ctx, listPlatformInfraCapacity, arg.StepSeconds, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformInfraCapacityRow{}
	for rows.Next() {
		var i ListPlatformInfraCapacityRow
		if err := rows.Scan(
			&i.BucketAt,
			&i.AllocatableCpuMillicores,
			&i.RequestedCpuMillicores,
			&i.AllocatableMemoryBytes,
			&i.RequestedMemoryBytes,
			&i.Agents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformInfraFailures = `-- name: ListPlatformInfraFailures :many
WITH f AS (
    SELECT x.source, x.event_id, x.team_id, x.at,
           CASE
               WHEN x.reason LIKE 'ErrImagePull%' OR x.reason LIKE 'ImagePullBackOff%' OR x.reason LIKE 'InvalidImageName%' THEN 'image_pull'
               WHEN x.reason LIKE 'CrashLoopBackOff%' THEN 'crash_loop'
               WHEN x.reason LIKE 'CreateContainerConfigError%' THEN 'container_config'
               WHEN x.reason LIKE 'Laboratory reported phase%' THEN 'lab_phase_failed'
               WHEN x.reason LIKE 'Not ready after%' THEN 'deploy_timeout'
               WHEN x.reason LIKE 'Laboratory status unavailable%' THEN 'status_unavailable'
               WHEN x.reason LIKE 'Topology unavailable%' THEN 'topology_unavailable'
               WHEN x.reason LIKE 'Deploy failed%' THEN 'deploy_failed'
               WHEN COALESCE(x.reason, '') = '' THEN 'unknown'
               ELSE 'other'
           END AS code
    FROM event_stand_transitions x
    WHERE x.at >= $1::timestamptz
      AND x.at < $2::timestamptz
      AND ((x.source = 'lab' AND x.to_status = 2) OR (x.source = 'stand' AND x.to_status = 3))
)
SELECT f.code::text                                          AS code,
       count(*) FILTER (WHERE f.source = 'lab')::bigint      AS labs,
       count(*) FILTER (WHERE f.source = 'stand')::bigint    AS stands,
       count(DISTINCT f.event_id)::bigint                    AS events,
       max(f.at)::timestamptz                                AS last_at
FROM f
GROUP BY f.code
ORDER BY count(*) FILTER (WHERE f.source = 'lab') DESC, count(*) FILTER (WHERE f.source = 'stand') DESC, f.code
`

type ListPlatformInfraFailuresParams struct {
	FromAt time.Time `json:"from_at"`
	ToAt   time.Time `json:"to_at"`
}

type ListPlatformInfraFailuresRow struct {
	Code   string    `json:"code"`
	Labs   int64     `json:"labs"`
	Stands int64     `json:"stands"`
	Events int64     `json:"events"`
	LastAt time.Time `json:"last_at"`
}

// Failed laboratories and stands in the period grouped by a reason code. The
// code is derived from the stored failure text (eventStand.Classify and the
// deploy engine write a fixed set of prefixes); the raw text never leaves the
// database, so nothing team- or user-specific is returned. labs counts lab
// status transitions to failed (source 'lab'), stands counts stand transitions
// to failed (source 'stand').
func (q *Queries) ListPlatformInfraFailures(ctx context.Context, arg ListPlatformInfraFailuresParams) ([]ListPlatformInfraFailuresRow, error) {
	rows, err := q.db.Query(ctx, listPlatformInfraFailures, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformInfraFailuresRow{}
	for rows.Next() {
		var i ListPlatformInfraFailuresRow
		if err := rows.Scan(
			&i.Code,
			&i.Labs,
			&i.Stands,
			&i.Events,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformInfraPeaks = `-- name: ListPlatformInfraPeaks :many
WITH win AS (
    SELECT $2::timestamptz AS from_at,
           LEAST($3::timestamptz, $4::timestamptz) AS to_at
), seg AS (
    SELECT x.to_status, x.at AS start_at,
           COALESCE(lead(x.at) OVER (PARTITION BY x.event_id, x.team_id ORDER BY x.at, x.id), w.to_at) AS end_at
    FROM event_stand_transitions x
    CROSS JOIN win w
    WHERE x.source = 'stand'
      AND x.at < w.to_at
), active AS (
    SELECT GREATEST(s.start_at, w.from_at) AS s,
           LEAST(s.end_at, w.to_at)        AS e
    FROM seg s
    CROSS JOIN win w
    WHERE s.to_status IN (1, 2)
      AND s.end_at > w.from_at
      AND s.start_at < w.to_at
), buckets AS (
    SELECT g AS b
    FROM win w,
         generate_series(date_trunc($1::text, w.from_at AT TIME ZONE 'UTC'),
                         date_trunc($1::text, (w.to_at - interval '1 microsecond') AT TIME ZONE 'UTC'),
                         ('1 ' || $1::text)::interval) g
    WHERE w.from_at < w.to_at
), points AS (
    SELECT e AS ts, 0 AS ord, -1 AS delta FROM active
    UNION ALL
    SELECT b AT TIME ZONE 'UTC', 1, 0 FROM buckets
    UNION ALL
    SELECT s, 2, 1 FROM active
), running AS (
    SELECT ts, sum(delta) OVER (ORDER BY ts, ord ROWS UNBOUNDED PRECEDING) AS level
    FROM points
)
SELECT (date_trunc($1::text, ts AT TIME ZONE 'UTC') AT TIME ZONE 'UTC')::timestamptz AS bucket_at,
       GREATEST(max(level), 0)::bigint AS peak
FROM running
WHERE ts < (SELECT to_at FROM win)
GROUP BY 1
ORDER BY 1
`

type ListPlatformInfraPeaksParams struct {
	Bucket string    `json:"bucket"`
	FromAt time.Time `json:"from_at"`
	ToAt   time.Time `json:"to_at"`
	NowAt  time.Time `json:"now_at"`
}

type ListPlatformInfraPeaksRow struct {
	BucketAt time.Time `json:"bucket_at"`
	Peak     int64     `json:"peak"`
}

// Peak of concurrently active stands per bucket ("hour" or "day", UTC). The
// active intervals become +1 / -1 points; a running sum gives the level, and a
// zero point at every bucket start carries the level over from the previous
// bucket. At one instant the order is: ends, bucket start, starts.
func (q *Queries) ListPlatformInfraPeaks(ctx context.Context, arg ListPlatformInfraPeaksParams) ([]ListPlatformInfraPeaksRow, error) {
	rows, err := q.db.Query(ctx, listPlatformInfraPeaks,
		arg.Bucket,
		arg.FromAt,
		arg.ToAt,
		arg.NowAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformInfraPeaksRow{}
	for rows.Next() {
		var i ListPlatformInfraPeaksRow
		if err := rows.Scan(&i.BucketAt, &i.Peak); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformInfraStandHours = `-- name: ListPlatformInfraStandHours :many

WITH win AS (
    SELECT $2::timestamptz AS from_at,
           LEAST($3::timestamptz, $4::timestamptz) AS to_at
), seg AS (
    SELECT x.event_id, x.team_id, x.to_status, x.at AS start_at,
           COALESCE(lead(x.at) OVER (PARTITION BY x.event_id, x.team_id ORDER BY x.at, x.id), w.to_at) AS end_at
    FROM event_stand_transitions x
    CROSS JOIN win w
    WHERE x.source = 'stand'
      AND x.at < w.to_at
), active AS (
    SELECT s.event_id, s.team_id,
           GREATEST(s.start_at, w.from_at) AS s,
           LEAST(s.end_at, w.to_at)        AS e
    FROM seg s
    CROSS JOIN win w
    WHERE s.to_status IN (1, 2)
      AND s.end_at > w.from_at
      AND s.start_at < w.to_at
), per_event AS (
    SELECT a.event_id,
           sum(extract(epoch FROM a.e - a.s))::float8 / 3600.0 AS hours,
           count(DISTINCT a.team_id)::bigint                   AS stands
    FROM active a
    GROUP BY a.event_id
)
SELECT p.event_id,
       COALESCE(ev.name, '')::text                          AS event_name,
       p.hours::float8                                      AS hours,
       p.stands                                             AS stands,
       (sum(p.hours) OVER ())::float8                       AS total_hours,
       (count(*) OVER ())::bigint                           AS total_events
FROM per_event p
LEFT JOIN events ev ON ev.id = p.event_id
ORDER BY p.hours DESC, p.event_id
LIMIT $1
`

type ListPlatformInfraStandHoursParams struct {
	LimitVal int32     `json:"limit_val"`
	FromAt   time.Time `json:"from_at"`
	ToAt     time.Time `json:"to_at"`
	NowAt    time.Time `json:"now_at"`
}

type ListPlatformInfraStandHoursRow struct {
	EventID     uuid.UUID `json:"event_id"`
	EventName   string    `json:"event_name"`
	Hours       float64   `json:"hours"`
	Stands      int64     `json:"stands"`
	TotalHours  float64   `json:"total_hours"`
	TotalEvents int64     `json:"total_events"`
}

// Platform analytics, «Інфраструктура» (docs/EVENT-ANALYTICS.md §8). Aggregates
// only: no IP addresses, no VPN client addresses, no lab payloads.
//
// A stand is ACTIVE while its status is creating (1) or ready (2), the same
// definition as the infrastructure summary of the admin labs page. The moderators
// stand counts too: it takes cluster resources like any other. Every window is
// clipped to [from_at, least(to_at, now_at)) so an open stand does not run into
// the future.
// Stand-hours per event: the summed active time of the event's stands inside the
// period, in hours, top events first. total_hours / total_events cover every
// event, not only the returned top rows. The status log of a stand is walked
// with lead(): a transition lasts until the next one, the last one until the
// end of the window.
func (q *Queries) ListPlatformInfraStandHours(ctx context.Context, arg ListPlatformInfraStandHoursParams) ([]ListPlatformInfraStandHoursRow, error) {
	rows, err := q.db.Query(ctx, listPlatformInfraStandHours,
		arg.LimitVal,
		arg.FromAt,
		arg.ToAt,
		arg.NowAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformInfraStandHoursRow{}
	for rows.Next() {
		var i ListPlatformInfraStandHoursRow
		if err := rows.Scan(
			&i.EventID,
			&i.EventName,
			&i.Hours,
			&i.Stands,
			&i.TotalHours,
			&i.TotalEvents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
