// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_idempotency.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeRequestIdempotency = `-- name: CompleteRequestIdempotency :execrows
UPDATE request_idempotency
SET completed = TRUE,
    response_status = $1,
    response_body = $2
WHERE owner_id = $3
  AND scope = $4
  AND key = $5
  AND request_hash = $6
  AND NOT completed
`

type CompleteRequestIdempotencyParams struct {
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ResponseBody   []byte      `json:"response_body"`
	OwnerID        uuid.UUID   `json:"owner_id"`
	Scope          string      `json:"scope"`
	Key            uuid.UUID   `json:"key"`
	RequestHash    []byte      `json:"request_hash"`
}

func (q *Queries) CompleteRequestIdempotency(ctx context.Context, arg CompleteRequestIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRequestIdempotency,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.OwnerID,
		arg.Scope,
		arg.Key,
		arg.RequestHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredRequestIdempotency = `-- name: DeleteExpiredRequestIdempotency :execrows
DELETE FROM request_idempotency
WHERE completed
  AND expires_at <= $1
`

func (q *Queries) DeleteExpiredRequestIdempotency(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRequestIdempotency, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRequestIdempotency = `-- name: GetRequestIdempotency :one
SELECT owner_id, scope, key, request_hash, completed, response_status, response_body, created_at, expires_at
FROM request_idempotency
WHERE owner_id = $1
  AND scope = $2
  AND key = $3
`

type GetRequestIdempotencyParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Scope   string    `json:"scope"`
	Key     uuid.UUID `json:"key"`
}

func (q *Queries) GetRequestIdempotency(ctx context.Context, arg GetRequestIdempotencyParams) (RequestIdempotency, error) {
	row := q.db.QueryRow(ctx, getRequestIdempotency, arg.OwnerID, arg.Scope, arg.Key)
	var i RequestIdempotency
	err := row.Scan(
		&i.OwnerID,
		&i.Scope,
		&i.Key,
		&i.RequestHash,
		&i.Completed,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const reserveRequestIdempotency = `-- name: ReserveRequestIdempotency :many
INSERT INTO request_idempotency (owner_id, scope, key, request_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (owner_id, scope, key) DO NOTHING
RETURNING owner_id, scope, key, request_hash, completed, response_status, response_body, created_at, expires_at
`

type ReserveRequestIdempotencyParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Scope       string    `json:"scope"`
	Key         uuid.UUID `json:"key"`
	RequestHash []byte    `json:"request_hash"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) ReserveRequestIdempotency(ctx context.Context, arg ReserveRequestIdempotencyParams) ([]RequestIdempotency, error) {
	rows, err := q.db.Query(ctx, reserveRequestIdempotency,
		arg.OwnerID,
		arg.Scope,
		arg.Key,
		arg.RequestHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestIdempotency{}
	for rows.Next() {
		var i RequestIdempotency
		if err := rows.Scan(
			&i.OwnerID,
			&i.Scope,
			&i.Key,
			&i.RequestHash,
			&i.Completed,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
