// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_calendar.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingResourceChangeRequests = `-- name: CountPendingResourceChangeRequests :one
SELECT count(*)::bigint FROM resource_change_requests WHERE status = 0
`

func (q *Queries) CountPendingResourceChangeRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingResourceChangeRequests)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createResourceAlarm = `-- name: CreateResourceAlarm :exec
INSERT INTO resource_alarms (id, kind, reservation_id, event_id, agent_id, units, stage, shortage_cpu_millicores, shortage_memory_bytes, raised_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11)
`

type CreateResourceAlarmParams struct {
	ID                    uuid.UUID     `json:"id"`
	Kind                  string        `json:"kind"`
	ReservationID         uuid.UUID     `json:"reservation_id"`
	EventID               uuid.NullUUID `json:"event_id"`
	AgentID               uuid.NullUUID `json:"agent_id"`
	Units                 int32         `json:"units"`
	Stage                 int16         `json:"stage"`
	ShortageCpuMillicores int64         `json:"shortage_cpu_millicores"`
	ShortageMemoryBytes   int64         `json:"shortage_memory_bytes"`
	RaisedAt              time.Time     `json:"raised_at"`
	UpdatedAt             time.Time     `json:"updated_at"`
}

func (q *Queries) CreateResourceAlarm(ctx context.Context, arg CreateResourceAlarmParams) error {
	_, err := q.db.Exec(ctx, createResourceAlarm,
		arg.ID,
		arg.Kind,
		arg.ReservationID,
		arg.EventID,
		arg.AgentID,
		arg.Units,
		arg.Stage,
		arg.ShortageCpuMillicores,
		arg.ShortageMemoryBytes,
		arg.RaisedAt,
		arg.UpdatedAt,
	)
	return err
}

const createResourceChangeRequest = `-- name: CreateResourceChangeRequest :exec
INSERT INTO resource_change_requests (id, reservation_id, event_id, requested_by, requested_at,
                                      size_cpu_millicores, size_memory_bytes, dynamic_cpu_millicores, dynamic_memory_bytes,
                                      window_start, window_end, reason, status)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11, $12, 0)
`

type CreateResourceChangeRequestParams struct {
	ID                   uuid.UUID          `json:"id"`
	ReservationID        uuid.UUID          `json:"reservation_id"`
	EventID              uuid.UUID          `json:"event_id"`
	RequestedBy          uuid.NullUUID      `json:"requested_by"`
	RequestedAt          time.Time          `json:"requested_at"`
	SizeCpuMillicores    pgtype.Int8        `json:"size_cpu_millicores"`
	SizeMemoryBytes      pgtype.Int8        `json:"size_memory_bytes"`
	DynamicCpuMillicores pgtype.Int8        `json:"dynamic_cpu_millicores"`
	DynamicMemoryBytes   pgtype.Int8        `json:"dynamic_memory_bytes"`
	WindowStart          pgtype.Timestamptz `json:"window_start"`
	WindowEnd            pgtype.Timestamptz `json:"window_end"`
	Reason               string             `json:"reason"`
}

func (q *Queries) CreateResourceChangeRequest(ctx context.Context, arg CreateResourceChangeRequestParams) error {
	_, err := q.db.Exec(ctx, createResourceChangeRequest,
		arg.ID,
		arg.ReservationID,
		arg.EventID,
		arg.RequestedBy,
		arg.RequestedAt,
		arg.SizeCpuMillicores,
		arg.SizeMemoryBytes,
		arg.DynamicCpuMillicores,
		arg.DynamicMemoryBytes,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Reason,
	)
	return err
}

const createResourceReservation = `-- name: CreateResourceReservation :exec
INSERT INTO resource_reservations (id, kind, event_id, owner_id, starts_at, ends_at, teams,
                                   per_team_cpu_millicores, per_team_memory_bytes,
                                   largest_device_cpu_millicores, largest_device_memory_bytes,
                                   buffer_percent, dynamic_cpu_millicores, dynamic_memory_bytes, tail_gap_seconds,
                                   size_cpu_millicores, size_memory_bytes, placement, unplaced,
                                   created_by, created_at, updated_at, canceled_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9,
        $10, $11,
        $12, $13, $14, $15,
        $16, $17, $18, $19,
        $20, $21, $22, $23)
`

type CreateResourceReservationParams struct {
	ID                         uuid.UUID          `json:"id"`
	Kind                       string             `json:"kind"`
	EventID                    uuid.NullUUID      `json:"event_id"`
	OwnerID                    uuid.NullUUID      `json:"owner_id"`
	StartsAt                   time.Time          `json:"starts_at"`
	EndsAt                     time.Time          `json:"ends_at"`
	Teams                      int32              `json:"teams"`
	PerTeamCpuMillicores       int64              `json:"per_team_cpu_millicores"`
	PerTeamMemoryBytes         int64              `json:"per_team_memory_bytes"`
	LargestDeviceCpuMillicores int64              `json:"largest_device_cpu_millicores"`
	LargestDeviceMemoryBytes   int64              `json:"largest_device_memory_bytes"`
	BufferPercent              int32              `json:"buffer_percent"`
	DynamicCpuMillicores       int64              `json:"dynamic_cpu_millicores"`
	DynamicMemoryBytes         int64              `json:"dynamic_memory_bytes"`
	TailGapSeconds             int32              `json:"tail_gap_seconds"`
	SizeCpuMillicores          int64              `json:"size_cpu_millicores"`
	SizeMemoryBytes            int64              `json:"size_memory_bytes"`
	Placement                  []byte             `json:"placement"`
	Unplaced                   int32              `json:"unplaced"`
	CreatedBy                  uuid.NullUUID      `json:"created_by"`
	CreatedAt                  time.Time          `json:"created_at"`
	UpdatedAt                  time.Time          `json:"updated_at"`
	CanceledAt                 pgtype.Timestamptz `json:"canceled_at"`
}

func (q *Queries) CreateResourceReservation(ctx context.Context, arg CreateResourceReservationParams) error {
	_, err := q.db.Exec(ctx, createResourceReservation,
		arg.ID,
		arg.Kind,
		arg.EventID,
		arg.OwnerID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Teams,
		arg.PerTeamCpuMillicores,
		arg.PerTeamMemoryBytes,
		arg.LargestDeviceCpuMillicores,
		arg.LargestDeviceMemoryBytes,
		arg.BufferPercent,
		arg.DynamicCpuMillicores,
		arg.DynamicMemoryBytes,
		arg.TailGapSeconds,
		arg.SizeCpuMillicores,
		arg.SizeMemoryBytes,
		arg.Placement,
		arg.Unplaced,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CanceledAt,
	)
	return err
}

const createResourceTestLabHold = `-- name: CreateResourceTestLabHold :exec
INSERT INTO resource_test_lab_holds (id, owner_id, via, reservation_id, cpu_millicores, memory_bytes, starts_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET expires_at = EXCLUDED.expires_at
`

type CreateResourceTestLabHoldParams struct {
	ID            uuid.UUID     `json:"id"`
	OwnerID       uuid.UUID     `json:"owner_id"`
	Via           string        `json:"via"`
	ReservationID uuid.NullUUID `json:"reservation_id"`
	CpuMillicores int64         `json:"cpu_millicores"`
	MemoryBytes   int64         `json:"memory_bytes"`
	StartsAt      time.Time     `json:"starts_at"`
	ExpiresAt     time.Time     `json:"expires_at"`
}

func (q *Queries) CreateResourceTestLabHold(ctx context.Context, arg CreateResourceTestLabHoldParams) error {
	_, err := q.db.Exec(ctx, createResourceTestLabHold,
		arg.ID,
		arg.OwnerID,
		arg.Via,
		arg.ReservationID,
		arg.CpuMillicores,
		arg.MemoryBytes,
		arg.StartsAt,
		arg.ExpiresAt,
	)
	return err
}

const decideResourceChangeRequest = `-- name: DecideResourceChangeRequest :execrows
UPDATE resource_change_requests
SET status = $1, decided_by = $2, decided_at = $3, decision_note = $4
WHERE id = $5 AND status = 0
`

type DecideResourceChangeRequestParams struct {
	Status       int16              `json:"status"`
	DecidedBy    uuid.NullUUID      `json:"decided_by"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	DecisionNote string             `json:"decision_note"`
	ID           uuid.UUID          `json:"id"`
}

// Writes the decision of a pending request; 0 rows: it was decided meanwhile.
func (q *Queries) DecideResourceChangeRequest(ctx context.Context, arg DecideResourceChangeRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideResourceChangeRequest,
		arg.Status,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.DecisionNote,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredResourceTestLabHolds = `-- name: DeleteExpiredResourceTestLabHolds :execrows
DELETE FROM resource_test_lab_holds WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredResourceTestLabHolds(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredResourceTestLabHolds, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteResourceTestLabHold = `-- name: DeleteResourceTestLabHold :exec
DELETE FROM resource_test_lab_holds WHERE id = $1
`

func (q *Queries) DeleteResourceTestLabHold(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResourceTestLabHold, id)
	return err
}

const getEventResourceReservation = `-- name: GetEventResourceReservation :one
SELECT id, kind, event_id, owner_id, starts_at, ends_at, teams, per_team_cpu_millicores, per_team_memory_bytes, largest_device_cpu_millicores, largest_device_memory_bytes, buffer_percent, dynamic_cpu_millicores, dynamic_memory_bytes, tail_gap_seconds, size_cpu_millicores, size_memory_bytes, placement, unplaced, created_by, created_at, updated_at, canceled_at FROM resource_reservations WHERE event_id = $1 AND kind = 'event' AND canceled_at IS NULL
`

func (q *Queries) GetEventResourceReservation(ctx context.Context, eventID uuid.NullUUID) (ResourceReservation, error) {
	row := q.db.QueryRow(ctx, getEventResourceReservation, eventID)
	var i ResourceReservation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.EventID,
		&i.OwnerID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Teams,
		&i.PerTeamCpuMillicores,
		&i.PerTeamMemoryBytes,
		&i.LargestDeviceCpuMillicores,
		&i.LargestDeviceMemoryBytes,
		&i.BufferPercent,
		&i.DynamicCpuMillicores,
		&i.DynamicMemoryBytes,
		&i.TailGapSeconds,
		&i.SizeCpuMillicores,
		&i.SizeMemoryBytes,
		&i.Placement,
		&i.Unplaced,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanceledAt,
	)
	return i, err
}

const getOpenResourceAlarm = `-- name: GetOpenResourceAlarm :one
SELECT id, kind, reservation_id, event_id, agent_id, units, stage, shortage_cpu_millicores, shortage_memory_bytes, raised_at, updated_at, resolved_at, acked_by, acked_at FROM resource_alarms
WHERE kind = $1 AND reservation_id = $2
  AND COALESCE(agent_id, '00000000-0000-0000-0000-000000000000'::uuid) = COALESCE($3::uuid, '00000000-0000-0000-0000-000000000000'::uuid)
  AND resolved_at IS NULL
`

type GetOpenResourceAlarmParams struct {
	Kind          string        `json:"kind"`
	ReservationID uuid.UUID     `json:"reservation_id"`
	AgentID       uuid.NullUUID `json:"agent_id"`
}

func (q *Queries) GetOpenResourceAlarm(ctx context.Context, arg GetOpenResourceAlarmParams) (ResourceAlarm, error) {
	row := q.db.QueryRow(ctx, getOpenResourceAlarm, arg.Kind, arg.ReservationID, arg.AgentID)
	var i ResourceAlarm
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ReservationID,
		&i.EventID,
		&i.AgentID,
		&i.Units,
		&i.Stage,
		&i.ShortageCpuMillicores,
		&i.ShortageMemoryBytes,
		&i.RaisedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.AckedBy,
		&i.AckedAt,
	)
	return i, err
}

const getResourceAlarm = `-- name: GetResourceAlarm :one
SELECT id, kind, reservation_id, event_id, agent_id, units, stage, shortage_cpu_millicores, shortage_memory_bytes, raised_at, updated_at, resolved_at, acked_by, acked_at FROM resource_alarms WHERE id = $1
`

func (q *Queries) GetResourceAlarm(ctx context.Context, id uuid.UUID) (ResourceAlarm, error) {
	row := q.db.QueryRow(ctx, getResourceAlarm, id)
	var i ResourceAlarm
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ReservationID,
		&i.EventID,
		&i.AgentID,
		&i.Units,
		&i.Stage,
		&i.ShortageCpuMillicores,
		&i.ShortageMemoryBytes,
		&i.RaisedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.AckedBy,
		&i.AckedAt,
	)
	return i, err
}

const getResourceCalendarSettings = `-- name: GetResourceCalendarSettings :one
SELECT id, test_pool_cpu_millicores, test_pool_memory_bytes, updated_at FROM resource_calendar_settings WHERE id
`

func (q *Queries) GetResourceCalendarSettings(ctx context.Context) (ResourceCalendarSetting, error) {
	row := q.db.QueryRow(ctx, getResourceCalendarSettings)
	var i ResourceCalendarSetting
	err := row.Scan(
		&i.ID,
		&i.TestPoolCpuMillicores,
		&i.TestPoolMemoryBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceChangeRequest = `-- name: GetResourceChangeRequest :one
SELECT id, reservation_id, event_id, requested_by, requested_at, size_cpu_millicores, size_memory_bytes, dynamic_cpu_millicores, dynamic_memory_bytes, window_start, window_end, reason, status, decided_by, decided_at, decision_note FROM resource_change_requests WHERE id = $1
`

func (q *Queries) GetResourceChangeRequest(ctx context.Context, id uuid.UUID) (ResourceChangeRequest, error) {
	row := q.db.QueryRow(ctx, getResourceChangeRequest, id)
	var i ResourceChangeRequest
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.EventID,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.SizeCpuMillicores,
		&i.SizeMemoryBytes,
		&i.DynamicCpuMillicores,
		&i.DynamicMemoryBytes,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Reason,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
	)
	return i, err
}

const getResourceReservation = `-- name: GetResourceReservation :one
SELECT id, kind, event_id, owner_id, starts_at, ends_at, teams, per_team_cpu_millicores, per_team_memory_bytes, largest_device_cpu_millicores, largest_device_memory_bytes, buffer_percent, dynamic_cpu_millicores, dynamic_memory_bytes, tail_gap_seconds, size_cpu_millicores, size_memory_bytes, placement, unplaced, created_by, created_at, updated_at, canceled_at FROM resource_reservations WHERE id = $1
`

func (q *Queries) GetResourceReservation(ctx context.Context, id uuid.UUID) (ResourceReservation, error) {
	row := q.db.QueryRow(ctx, getResourceReservation, id)
	var i ResourceReservation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.EventID,
		&i.OwnerID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Teams,
		&i.PerTeamCpuMillicores,
		&i.PerTeamMemoryBytes,
		&i.LargestDeviceCpuMillicores,
		&i.LargestDeviceMemoryBytes,
		&i.BufferPercent,
		&i.DynamicCpuMillicores,
		&i.DynamicMemoryBytes,
		&i.TailGapSeconds,
		&i.SizeCpuMillicores,
		&i.SizeMemoryBytes,
		&i.Placement,
		&i.Unplaced,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanceledAt,
	)
	return i, err
}

const listActiveResourceTestLabHolds = `-- name: ListActiveResourceTestLabHolds :many
SELECT id, owner_id, via, reservation_id, cpu_millicores, memory_bytes, starts_at, expires_at FROM resource_test_lab_holds WHERE expires_at > $1 ORDER BY starts_at, id
`

func (q *Queries) ListActiveResourceTestLabHolds(ctx context.Context, now time.Time) ([]ResourceTestLabHold, error) {
	rows, err := q.db.Query(ctx, listActiveResourceTestLabHolds, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceTestLabHold{}
	for rows.Next() {
		var i ResourceTestLabHold
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Via,
			&i.ReservationID,
			&i.CpuMillicores,
			&i.MemoryBytes,
			&i.StartsAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenResourceAlarmsOfReservation = `-- name: ListOpenResourceAlarmsOfReservation :many
SELECT id, kind, reservation_id, event_id, agent_id, units, stage, shortage_cpu_millicores, shortage_memory_bytes, raised_at, updated_at, resolved_at, acked_by, acked_at FROM resource_alarms WHERE reservation_id = $1 AND resolved_at IS NULL
`

func (q *Queries) ListOpenResourceAlarmsOfReservation(ctx context.Context, reservationID uuid.UUID) ([]ResourceAlarm, error) {
	rows, err := q.db.Query(ctx, listOpenResourceAlarmsOfReservation, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceAlarm{}
	for rows.Next() {
		var i ResourceAlarm
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ReservationID,
			&i.EventID,
			&i.AgentID,
			&i.Units,
			&i.Stage,
			&i.ShortageCpuMillicores,
			&i.ShortageMemoryBytes,
			&i.RaisedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.AckedBy,
			&i.AckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedResourceBookings = `-- name: ListOwnedResourceBookings :many
SELECT id, kind, event_id, owner_id, starts_at, ends_at, teams, per_team_cpu_millicores, per_team_memory_bytes, largest_device_cpu_millicores, largest_device_memory_bytes, buffer_percent, dynamic_cpu_millicores, dynamic_memory_bytes, tail_gap_seconds, size_cpu_millicores, size_memory_bytes, placement, unplaced, created_by, created_at, updated_at, canceled_at FROM resource_reservations
WHERE kind = 'test_booking' AND owner_id = $1 AND canceled_at IS NULL AND ends_at > $2
ORDER BY starts_at, id
`

type ListOwnedResourceBookingsParams struct {
	OwnerID uuid.NullUUID `json:"owner_id"`
	AfterAt time.Time     `json:"after_at"`
}

func (q *Queries) ListOwnedResourceBookings(ctx context.Context, arg ListOwnedResourceBookingsParams) ([]ResourceReservation, error) {
	rows, err := q.db.Query(ctx, listOwnedResourceBookings, arg.OwnerID, arg.AfterAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceReservation{}
	for rows.Next() {
		var i ResourceReservation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EventID,
			&i.OwnerID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Teams,
			&i.PerTeamCpuMillicores,
			&i.PerTeamMemoryBytes,
			&i.LargestDeviceCpuMillicores,
			&i.LargestDeviceMemoryBytes,
			&i.BufferPercent,
			&i.DynamicCpuMillicores,
			&i.DynamicMemoryBytes,
			&i.TailGapSeconds,
			&i.SizeCpuMillicores,
			&i.SizeMemoryBytes,
			&i.Placement,
			&i.Unplaced,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceAlarms = `-- name: ListResourceAlarms :many
SELECT a.id, a.kind, a.reservation_id, a.event_id, a.agent_id, a.units, a.stage, a.shortage_cpu_millicores, a.shortage_memory_bytes, a.raised_at, a.updated_at, a.resolved_at, a.acked_by, a.acked_at, e.name AS event_name, e.tag AS event_tag
FROM resource_alarms a
LEFT JOIN events e ON e.id = a.event_id
WHERE (NOT $1::bool OR a.resolved_at IS NULL)
ORDER BY (a.resolved_at IS NULL) DESC, a.raised_at DESC, a.id
LIMIT $2
`

type ListResourceAlarmsParams struct {
	OnlyOpen bool  `json:"only_open"`
	LimitVal int32 `json:"limit_val"`
}

type ListResourceAlarmsRow struct {
	ID                    uuid.UUID          `json:"id"`
	Kind                  string             `json:"kind"`
	ReservationID         uuid.UUID          `json:"reservation_id"`
	EventID               uuid.NullUUID      `json:"event_id"`
	AgentID               uuid.NullUUID      `json:"agent_id"`
	Units                 int32              `json:"units"`
	Stage                 int16              `json:"stage"`
	ShortageCpuMillicores int64              `json:"shortage_cpu_millicores"`
	ShortageMemoryBytes   int64              `json:"shortage_memory_bytes"`
	RaisedAt              time.Time          `json:"raised_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	ResolvedAt            pgtype.Timestamptz `json:"resolved_at"`
	AckedBy               uuid.NullUUID      `json:"acked_by"`
	AckedAt               pgtype.Timestamptz `json:"acked_at"`
	EventName             pgtype.Text        `json:"event_name"`
	EventTag              pgtype.Text        `json:"event_tag"`
}

// Open alarms first, then the resolved ones, newest first; only_open leaves the resolved out.
func (q *Queries) ListResourceAlarms(ctx context.Context, arg ListResourceAlarmsParams) ([]ListResourceAlarmsRow, error) {
	rows, err := q.db.Query(ctx, listResourceAlarms, arg.OnlyOpen, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourceAlarmsRow{}
	for rows.Next() {
		var i ListResourceAlarmsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ReservationID,
			&i.EventID,
			&i.AgentID,
			&i.Units,
			&i.Stage,
			&i.ShortageCpuMillicores,
			&i.ShortageMemoryBytes,
			&i.RaisedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.AckedBy,
			&i.AckedAt,
			&i.EventName,
			&i.EventTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceChangeRequests = `-- name: ListResourceChangeRequests :many
SELECT c.id, c.reservation_id, c.event_id, c.requested_by, c.requested_at, c.size_cpu_millicores, c.size_memory_bytes, c.dynamic_cpu_millicores, c.dynamic_memory_bytes, c.window_start, c.window_end, c.reason, c.status, c.decided_by, c.decided_at, c.decision_note, e.name AS event_name, e.tag AS event_tag
FROM resource_change_requests c
JOIN events e ON e.id = c.event_id
WHERE ($1::smallint IS NULL OR c.status = $1::smallint)
  AND ($2::uuid IS NULL OR c.event_id = $2::uuid)
ORDER BY c.requested_at DESC, c.id
`

type ListResourceChangeRequestsParams struct {
	Status  pgtype.Int2   `json:"status"`
	EventID uuid.NullUUID `json:"event_id"`
}

type ListResourceChangeRequestsRow struct {
	ID                   uuid.UUID          `json:"id"`
	ReservationID        uuid.UUID          `json:"reservation_id"`
	EventID              uuid.UUID          `json:"event_id"`
	RequestedBy          uuid.NullUUID      `json:"requested_by"`
	RequestedAt          time.Time          `json:"requested_at"`
	SizeCpuMillicores    pgtype.Int8        `json:"size_cpu_millicores"`
	SizeMemoryBytes      pgtype.Int8        `json:"size_memory_bytes"`
	DynamicCpuMillicores pgtype.Int8        `json:"dynamic_cpu_millicores"`
	DynamicMemoryBytes   pgtype.Int8        `json:"dynamic_memory_bytes"`
	WindowStart          pgtype.Timestamptz `json:"window_start"`
	WindowEnd            pgtype.Timestamptz `json:"window_end"`
	Reason               string             `json:"reason"`
	Status               int16              `json:"status"`
	DecidedBy            uuid.NullUUID      `json:"decided_by"`
	DecidedAt            pgtype.Timestamptz `json:"decided_at"`
	DecisionNote         string             `json:"decision_note"`
	EventName            string             `json:"event_name"`
	EventTag             string             `json:"event_tag"`
}

// Newest first; status and event narrow it (a null argument matches everything).
func (q *Queries) ListResourceChangeRequests(ctx context.Context, arg ListResourceChangeRequestsParams) ([]ListResourceChangeRequestsRow, error) {
	rows, err := q.db.Query(ctx, listResourceChangeRequests, arg.Status, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourceChangeRequestsRow{}
	for rows.Next() {
		var i ListResourceChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.EventID,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.SizeCpuMillicores,
			&i.SizeMemoryBytes,
			&i.DynamicCpuMillicores,
			&i.DynamicMemoryBytes,
			&i.WindowStart,
			&i.WindowEnd,
			&i.Reason,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
			&i.EventName,
			&i.EventTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceReservationLabels = `-- name: ListResourceReservationLabels :many
SELECT r.id, e.name AS event_name, e.tag AS event_tag
FROM resource_reservations r
JOIN events e ON e.id = r.event_id
WHERE r.id = ANY($1::uuid[])
`

type ListResourceReservationLabelsRow struct {
	ID        uuid.UUID `json:"id"`
	EventName string    `json:"event_name"`
	EventTag  string    `json:"event_tag"`
}

// The event names of event reservations (for the admin timeline).
func (q *Queries) ListResourceReservationLabels(ctx context.Context, ids []uuid.UUID) ([]ListResourceReservationLabelsRow, error) {
	rows, err := q.db.Query(ctx, listResourceReservationLabels, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourceReservationLabelsRow{}
	for rows.Next() {
		var i ListResourceReservationLabelsRow
		if err := rows.Scan(&i.ID, &i.EventName, &i.EventTag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceReservationsEndingAfter = `-- name: ListResourceReservationsEndingAfter :many
SELECT id, kind, event_id, owner_id, starts_at, ends_at, teams, per_team_cpu_millicores, per_team_memory_bytes, largest_device_cpu_millicores, largest_device_memory_bytes, buffer_percent, dynamic_cpu_millicores, dynamic_memory_bytes, tail_gap_seconds, size_cpu_millicores, size_memory_bytes, placement, unplaced, created_by, created_at, updated_at, canceled_at FROM resource_reservations
WHERE canceled_at IS NULL AND ends_at > $1
ORDER BY starts_at, id
`

// Every active reservation that has not ended by the given time.
func (q *Queries) ListResourceReservationsEndingAfter(ctx context.Context, afterAt time.Time) ([]ResourceReservation, error) {
	rows, err := q.db.Query(ctx, listResourceReservationsEndingAfter, afterAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceReservation{}
	for rows.Next() {
		var i ResourceReservation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EventID,
			&i.OwnerID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Teams,
			&i.PerTeamCpuMillicores,
			&i.PerTeamMemoryBytes,
			&i.LargestDeviceCpuMillicores,
			&i.LargestDeviceMemoryBytes,
			&i.BufferPercent,
			&i.DynamicCpuMillicores,
			&i.DynamicMemoryBytes,
			&i.TailGapSeconds,
			&i.SizeCpuMillicores,
			&i.SizeMemoryBytes,
			&i.Placement,
			&i.Unplaced,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceReservationsInWindow = `-- name: ListResourceReservationsInWindow :many
SELECT id, kind, event_id, owner_id, starts_at, ends_at, teams, per_team_cpu_millicores, per_team_memory_bytes, largest_device_cpu_millicores, largest_device_memory_bytes, buffer_percent, dynamic_cpu_millicores, dynamic_memory_bytes, tail_gap_seconds, size_cpu_millicores, size_memory_bytes, placement, unplaced, created_by, created_at, updated_at, canceled_at FROM resource_reservations
WHERE canceled_at IS NULL AND starts_at < $1 AND ends_at > $2
ORDER BY starts_at, id
`

type ListResourceReservationsInWindowParams struct {
	ToAt   time.Time `json:"to_at"`
	FromAt time.Time `json:"from_at"`
}

// The active reservations that share a slot with [from, to).
func (q *Queries) ListResourceReservationsInWindow(ctx context.Context, arg ListResourceReservationsInWindowParams) ([]ResourceReservation, error) {
	rows, err := q.db.Query(ctx, listResourceReservationsInWindow, arg.ToAt, arg.FromAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceReservation{}
	for rows.Next() {
		var i ResourceReservation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EventID,
			&i.OwnerID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Teams,
			&i.PerTeamCpuMillicores,
			&i.PerTeamMemoryBytes,
			&i.LargestDeviceCpuMillicores,
			&i.LargestDeviceMemoryBytes,
			&i.BufferPercent,
			&i.DynamicCpuMillicores,
			&i.DynamicMemoryBytes,
			&i.TailGapSeconds,
			&i.SizeCpuMillicores,
			&i.SizeMemoryBytes,
			&i.Placement,
			&i.Unplaced,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockResourceCalendar = `-- name: LockResourceCalendar :exec

SELECT pg_advisory_xact_lock(hashtextextended('resource-calendar', 0))
`

// Resource calendar: reservations, change requests, readiness alarms, settings and test lab holds. See
// migration 0151. Reservations are one aggregate: every change is a whole-row UPDATE.
// Serializes everything that decides on the calendar (reservations, placement, test lab admission) until the
// transaction ends: no two admissions see the same free room.
func (q *Queries) LockResourceCalendar(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockResourceCalendar)
	return err
}

const setResourceCalendarSettings = `-- name: SetResourceCalendarSettings :exec
UPDATE resource_calendar_settings
SET test_pool_cpu_millicores = $1, test_pool_memory_bytes = $2, updated_at = $3
WHERE id
`

type SetResourceCalendarSettingsParams struct {
	TestPoolCpuMillicores int64     `json:"test_pool_cpu_millicores"`
	TestPoolMemoryBytes   int64     `json:"test_pool_memory_bytes"`
	UpdatedAt             time.Time `json:"updated_at"`
}

func (q *Queries) SetResourceCalendarSettings(ctx context.Context, arg SetResourceCalendarSettingsParams) error {
	_, err := q.db.Exec(ctx, setResourceCalendarSettings, arg.TestPoolCpuMillicores, arg.TestPoolMemoryBytes, arg.UpdatedAt)
	return err
}

const updateResourceAlarm = `-- name: UpdateResourceAlarm :execrows
UPDATE resource_alarms
SET units = $1, stage = $2, shortage_cpu_millicores = $3, shortage_memory_bytes = $4,
    updated_at = $5, resolved_at = $6, acked_by = $7, acked_at = $8
WHERE id = $9
`

type UpdateResourceAlarmParams struct {
	Units                 int32              `json:"units"`
	Stage                 int16              `json:"stage"`
	ShortageCpuMillicores int64              `json:"shortage_cpu_millicores"`
	ShortageMemoryBytes   int64              `json:"shortage_memory_bytes"`
	UpdatedAt             time.Time          `json:"updated_at"`
	ResolvedAt            pgtype.Timestamptz `json:"resolved_at"`
	AckedBy               uuid.NullUUID      `json:"acked_by"`
	AckedAt               pgtype.Timestamptz `json:"acked_at"`
	ID                    uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateResourceAlarm(ctx context.Context, arg UpdateResourceAlarmParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateResourceAlarm,
		arg.Units,
		arg.Stage,
		arg.ShortageCpuMillicores,
		arg.ShortageMemoryBytes,
		arg.UpdatedAt,
		arg.ResolvedAt,
		arg.AckedBy,
		arg.AckedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateResourceReservation = `-- name: UpdateResourceReservation :execrows
UPDATE resource_reservations
SET starts_at = $1, ends_at = $2, teams = $3,
    per_team_cpu_millicores = $4, per_team_memory_bytes = $5,
    largest_device_cpu_millicores = $6, largest_device_memory_bytes = $7,
    buffer_percent = $8, dynamic_cpu_millicores = $9,
    dynamic_memory_bytes = $10, tail_gap_seconds = $11,
    size_cpu_millicores = $12, size_memory_bytes = $13,
    placement = $14, unplaced = $15,
    updated_at = $16, canceled_at = $17
WHERE id = $18
`

type UpdateResourceReservationParams struct {
	StartsAt                   time.Time          `json:"starts_at"`
	EndsAt                     time.Time          `json:"ends_at"`
	Teams                      int32              `json:"teams"`
	PerTeamCpuMillicores       int64              `json:"per_team_cpu_millicores"`
	PerTeamMemoryBytes         int64              `json:"per_team_memory_bytes"`
	LargestDeviceCpuMillicores int64              `json:"largest_device_cpu_millicores"`
	LargestDeviceMemoryBytes   int64              `json:"largest_device_memory_bytes"`
	BufferPercent              int32              `json:"buffer_percent"`
	DynamicCpuMillicores       int64              `json:"dynamic_cpu_millicores"`
	DynamicMemoryBytes         int64              `json:"dynamic_memory_bytes"`
	TailGapSeconds             int32              `json:"tail_gap_seconds"`
	SizeCpuMillicores          int64              `json:"size_cpu_millicores"`
	SizeMemoryBytes            int64              `json:"size_memory_bytes"`
	Placement                  []byte             `json:"placement"`
	Unplaced                   int32              `json:"unplaced"`
	UpdatedAt                  time.Time          `json:"updated_at"`
	CanceledAt                 pgtype.Timestamptz `json:"canceled_at"`
	ID                         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateResourceReservation(ctx context.Context, arg UpdateResourceReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateResourceReservation,
		arg.StartsAt,
		arg.EndsAt,
		arg.Teams,
		arg.PerTeamCpuMillicores,
		arg.PerTeamMemoryBytes,
		arg.LargestDeviceCpuMillicores,
		arg.LargestDeviceMemoryBytes,
		arg.BufferPercent,
		arg.DynamicCpuMillicores,
		arg.DynamicMemoryBytes,
		arg.TailGapSeconds,
		arg.SizeCpuMillicores,
		arg.SizeMemoryBytes,
		arg.Placement,
		arg.Unplaced,
		arg.UpdatedAt,
		arg.CanceledAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
