// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scoreboard.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listEventScoreTimeline = `-- name: ListEventScoreTimeline :many
SELECT score.event_team_id::uuid AS event_team_id, score.event_challenge_id::uuid AS event_challenge_id,
       COALESCE(challenge.snapshot->>'name', '')::text AS challenge_name,
       score.points::integer AS points, score.solved_at::timestamptz AS solved_at,
       score.team_challenge_id::uuid AS team_challenge_id
FROM event_solved_scores_at($1::uuid, $2::timestamptz, $3::uuid) score
JOIN event_teams team ON team.id = score.event_team_id
LEFT JOIN event_challenges challenge ON challenge.id = score.event_challenge_id
WHERE event_team_visible(team.hidden, team.moderators, team.event_id, team.individual, team.admitted_manually, team.admission_locked, team.member_count)
ORDER BY 5 ASC, 6 ASC
`

type ListEventScoreTimelineParams struct {
	EventID     uuid.UUID          `json:"event_id"`
	Cutoff      pgtype.Timestamptz `json:"cutoff"`
	IncludeTeam uuid.NullUUID      `json:"include_team"`
}

type ListEventScoreTimelineRow struct {
	EventTeamID      uuid.UUID `json:"event_team_id"`
	EventChallengeID uuid.UUID `json:"event_challenge_id"`
	ChallengeName    string    `json:"challenge_name"`
	Points           int32     `json:"points"`
	SolvedAt         time.Time `json:"solved_at"`
	TeamChallengeID  uuid.UUID `json:"team_challenge_id"`
}

// Same cutoff rules as ListEventScoreboard.
func (q *Queries) ListEventScoreTimeline(ctx context.Context, arg ListEventScoreTimelineParams) ([]ListEventScoreTimelineRow, error) {
	rows, err := q.db.Query(ctx, listEventScoreTimeline, arg.EventID, arg.Cutoff, arg.IncludeTeam)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventScoreTimelineRow{}
	for rows.Next() {
		var i ListEventScoreTimelineRow
		if err := rows.Scan(
			&i.EventTeamID,
			&i.EventChallengeID,
			&i.ChallengeName,
			&i.Points,
			&i.SolvedAt,
			&i.TeamChallengeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventScoreboard = `-- name: ListEventScoreboard :many
SELECT t.id AS team_id,
       event_team_public_name(t.individual, t.event_id, t.captain_id, t.name)::text AS team_name,
       COALESCE(SUM(score.points), 0)::bigint AS points,
       count(score.team_challenge_id) FILTER (WHERE score.solve)::bigint AS solved,
       MAX(score.solved_at) FILTER (WHERE score.solve) AS last_solve_at
FROM event_teams t
LEFT JOIN event_solved_scores_at($1::uuid, $2::timestamptz, $3::uuid) score
       ON score.event_team_id = t.id
WHERE t.event_id = $1 AND event_team_visible(t.hidden, t.moderators, t.event_id, t.individual, t.admitted_manually, t.admission_locked, t.member_count)
GROUP BY t.id
ORDER BY points DESC, last_solve_at ASC NULLS LAST, t.id ASC
`

type ListEventScoreboardParams struct {
	EventID     uuid.UUID          `json:"event_id"`
	Cutoff      pgtype.Timestamptz `json:"cutoff"`
	IncludeTeam uuid.NullUUID      `json:"include_team"`
}

type ListEventScoreboardRow struct {
	TeamID      uuid.UUID   `json:"team_id"`
	TeamName    string      `json:"team_name"`
	Points      int64       `json:"points"`
	Solved      int64       `json:"solved"`
	LastSolveAt interface{} `json:"last_solve_at"`
}

// Ranked public teams. A NULL cutoff reads live scores; a cutoff reads the
// table as of that moment (freeze), plus every solve of include_team.
func (q *Queries) ListEventScoreboard(ctx context.Context, arg ListEventScoreboardParams) ([]ListEventScoreboardRow, error) {
	rows, err := q.db.Query(ctx, listEventScoreboard, arg.EventID, arg.Cutoff, arg.IncludeTeam)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventScoreboardRow{}
	for rows.Next() {
		var i ListEventScoreboardRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TeamName,
			&i.Points,
			&i.Solved,
			&i.LastSolveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManageHintTotals = `-- name: ListManageHintTotals :many
SELECT unlock.event_team_id::uuid AS event_team_id,
       count(*)::bigint AS hints,
       COALESCE(sum(unlock.cost) FILTER (
           WHERE COALESCE(config.hint_charge_mode, 0) = 1
              OR solved.solved_at >= unlock.unlocked_at), 0)::bigint AS charged
FROM team_challenge_hint_unlocks unlock
JOIN event_challenges ec ON ec.id = unlock.event_challenge_id
JOIN event_exercises ee ON ee.id = ec.event_exercise_id AND ee.status <> 2
LEFT JOIN event_configs config ON config.event_id = unlock.event_id
LEFT JOIN team_challenge_solves solved ON solved.team_challenge_id = unlock.team_challenge_id
WHERE unlock.event_id = $1::uuid
GROUP BY unlock.event_team_id
`

type ListManageHintTotalsRow struct {
	EventTeamID uuid.UUID `json:"event_team_id"`
	Hints       int64     `json:"hints"`
	Charged     int64     `json:"charged"`
}

// Hints opened per team and the points they cost. Without the balance mode a
// hint is charged only from the reward of a later solve of its challenge.
func (q *Queries) ListManageHintTotals(ctx context.Context, eventID uuid.UUID) ([]ListManageHintTotalsRow, error) {
	rows, err := q.db.Query(ctx, listManageHintTotals, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManageHintTotalsRow{}
	for rows.Next() {
		var i ListManageHintTotalsRow
		if err := rows.Scan(&i.EventTeamID, &i.Hints, &i.Charged); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManageScoreSolves = `-- name: ListManageScoreSolves :many
SELECT ranked.event_team_id, ranked.event_challenge_id,
       COALESCE(challenge.snapshot->>'name', '')::text AS challenge_name,
       ranked.points, ranked.solved_at,
       (ranked.counted AND ranked.place = 1)::boolean AS first_blood
FROM (
    SELECT s.event_team_id::uuid AS event_team_id, s.event_challenge_id::uuid AS event_challenge_id,
           s.team_challenge_id::uuid AS team_challenge_id,
           s.points::integer AS points, s.solved_at::timestamptz AS solved_at,
           (event_team_visible(team.hidden, team.moderators, team.event_id, team.individual, team.admitted_manually, team.admission_locked, team.member_count))::boolean AS counted,
           row_number() OVER (
               PARTITION BY s.event_challenge_id,
                   (event_team_visible(team.hidden, team.moderators, team.event_id, team.individual, team.admitted_manually, team.admission_locked, team.member_count))
               ORDER BY s.solved_at, s.team_challenge_id) AS place
    FROM event_solved_scores_at($1::uuid, NULL, NULL) s
    JOIN event_teams team ON team.id = s.event_team_id
    WHERE s.solve
) ranked
LEFT JOIN event_challenges challenge ON challenge.id = ranked.event_challenge_id
ORDER BY 5 ASC, ranked.team_challenge_id ASC
`

type ListManageScoreSolvesRow struct {
	EventTeamID      uuid.UUID `json:"event_team_id"`
	EventChallengeID uuid.UUID `json:"event_challenge_id"`
	ChallengeName    string    `json:"challenge_name"`
	Points           int32     `json:"points"`
	SolvedAt         time.Time `json:"solved_at"`
	FirstBlood       bool      `json:"first_blood"`
}

// The solves behind the moderators' table, live, for every team, the
// moderators team included. first_blood marks the first solve of a challenge among the
// ranked teams (not hidden, admitted).
func (q *Queries) ListManageScoreSolves(ctx context.Context, eventID uuid.UUID) ([]ListManageScoreSolvesRow, error) {
	rows, err := q.db.Query(ctx, listManageScoreSolves, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManageScoreSolvesRow{}
	for rows.Next() {
		var i ListManageScoreSolvesRow
		if err := rows.Scan(
			&i.EventTeamID,
			&i.EventChallengeID,
			&i.ChallengeName,
			&i.Points,
			&i.SolvedAt,
			&i.FirstBlood,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManageScoreboard = `-- name: ListManageScoreboard :many
SELECT t.id AS team_id,
       t.individual,
       t.hidden,
       t.moderators,
       event_team_admitted(t.event_id, t.individual, t.admitted_manually, t.admission_locked, t.member_count) AS admitted,
       event_team_public_name(t.individual, t.event_id, t.captain_id, t.name)::text AS public_name,
       (CASE WHEN t.individual
                 THEN COALESCE(NULLIF(btrim(concat_ws(' ', person.first_name, person.last_name)), ''), t.name)
             ELSE t.name END)::text AS real_name,
       (CASE WHEN t.individual THEN COALESCE(NULLIF(btrim(participant.pseudonym), ''), '') ELSE '' END)::text AS pseudonym,
       COALESCE(SUM(score.points), 0)::bigint AS points,
       count(score.team_challenge_id) FILTER (WHERE score.solve)::bigint AS solved,
       MAX(score.solved_at) FILTER (WHERE score.solve) AS last_solve_at
FROM event_teams t
LEFT JOIN users person ON person.id = t.captain_id
LEFT JOIN event_participants participant ON participant.event_id = t.event_id AND participant.user_id = t.captain_id
LEFT JOIN event_solved_scores_at($1::uuid, NULL, NULL) score ON score.event_team_id = t.id
WHERE t.event_id = $1::uuid
GROUP BY t.id, person.first_name, person.last_name, participant.pseudonym
ORDER BY points DESC, last_solve_at ASC NULLS LAST, t.id ASC
`

type ListManageScoreboardRow struct {
	TeamID      uuid.UUID   `json:"team_id"`
	Individual  bool        `json:"individual"`
	Hidden      bool        `json:"hidden"`
	Moderators  bool        `json:"moderators"`
	Admitted    bool        `json:"admitted"`
	PublicName  string      `json:"public_name"`
	RealName    string      `json:"real_name"`
	Pseudonym   string      `json:"pseudonym"`
	Points      int64       `json:"points"`
	Solved      int64       `json:"solved"`
	LastSolveAt interface{} `json:"last_solve_at"`
}

// Every team of the event, the moderators team included, live, with the marks a
// moderator needs: hidden, admitted, and for individual events the real name
// and pseudonym of the participant behind the solo team.
func (q *Queries) ListManageScoreboard(ctx context.Context, eventID uuid.UUID) ([]ListManageScoreboardRow, error) {
	rows, err := q.db.Query(ctx, listManageScoreboard, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManageScoreboardRow{}
	for rows.Next() {
		var i ListManageScoreboardRow
		if err := rows.Scan(
			&i.TeamID,
			&i.Individual,
			&i.Hidden,
			&i.Moderators,
			&i.Admitted,
			&i.PublicName,
			&i.RealName,
			&i.Pseudonym,
			&i.Points,
			&i.Solved,
			&i.LastSolveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamScoreTimeline = `-- name: ListTeamScoreTimeline :many
SELECT score.event_challenge_id::uuid AS event_challenge_id, score.points::integer AS points,
       score.solved_at::timestamptz AS solved_at, score.team_challenge_id::uuid AS team_challenge_id
FROM event_teams team
CROSS JOIN LATERAL event_solved_scores_at(team.event_id, NULL, NULL) score
WHERE team.id = $1
  AND score.event_team_id = team.id
ORDER BY 3 ASC, 4 ASC
`

type ListTeamScoreTimelineRow struct {
	EventChallengeID uuid.UUID `json:"event_challenge_id"`
	Points           int32     `json:"points"`
	SolvedAt         time.Time `json:"solved_at"`
	TeamChallengeID  uuid.UUID `json:"team_challenge_id"`
}

// Includes balance-mode hint penalties (negative points) so the running
// total matches the scoreboard.
func (q *Queries) ListTeamScoreTimeline(ctx context.Context, eventTeamID uuid.UUID) ([]ListTeamScoreTimelineRow, error) {
	rows, err := q.db.Query(ctx, listTeamScoreTimeline, eventTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamScoreTimelineRow{}
	for rows.Next() {
		var i ListTeamScoreTimelineRow
		if err := rows.Scan(
			&i.EventChallengeID,
			&i.Points,
			&i.SolvedAt,
			&i.TeamChallengeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
