// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: temporal_codes.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const createTemporalCode = `-- name: CreateTemporalCode :one
INSERT INTO temporal_codes (id, code, type, data, expires_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id, code, type, data, expires_at, created_at
`

type CreateTemporalCodeParams struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Type      int32     `json:"type"`
	Data      []byte    `json:"data"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateTemporalCode(ctx context.Context, arg CreateTemporalCodeParams) (TemporalCode, error) {
	row := q.db.QueryRow(ctx, createTemporalCode,
		arg.ID,
		arg.Code,
		arg.Type,
		arg.Data,
		arg.ExpiresAt,
	)
	var i TemporalCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Data,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTemporalCode = `-- name: DeleteTemporalCode :execrows
DELETE
FROM temporal_codes
WHERE id = $1
`

func (q *Queries) DeleteTemporalCode(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemporalCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTemporalCodesForUser = `-- name: DeleteTemporalCodesForUser :execrows
DELETE
FROM temporal_codes
WHERE type = $1
  AND data ->> 'UserID' = $2::text
`

type DeleteTemporalCodesForUserParams struct {
	Type   int32  `json:"type"`
	UserID string `json:"user_id"`
}

// Every code of the type issued to the user (the payload names the user): a
// password reset revokes the reset links still in the mailbox.
func (q *Queries) DeleteTemporalCodesForUser(ctx context.Context, arg DeleteTemporalCodesForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemporalCodesForUser, arg.Type, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTemporalCodeByCode = `-- name: GetTemporalCodeByCode :one
SELECT id, code, type, data, expires_at, created_at
FROM temporal_codes
WHERE code = $1
`

func (q *Queries) GetTemporalCodeByCode(ctx context.Context, code string) (TemporalCode, error) {
	row := q.db.QueryRow(ctx, getTemporalCodeByCode, code)
	var i TemporalCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Data,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
