// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const avgDailyActiveSince = `-- name: AvgDailyActiveSince :one
SELECT (COALESCE(count(*), 0)::float8 / 7.0) ::float8 AS avg_daily_active
FROM (SELECT date_trunc('day', created_at) AS d, user_id
      FROM sessions
      WHERE created_at >= $1
      GROUP BY 1, 2) x
`

func (q *Queries) AvgDailyActiveSince(ctx context.Context, createdAt time.Time) (float64, error) {
	row := q.db.QueryRow(ctx, avgDailyActiveSince, createdAt)
	var avg_daily_active float64
	err := row.Scan(&avg_daily_active)
	return avg_daily_active, err
}

const countUserLoginMethods = `-- name: CountUserLoginMethods :one
SELECT ((CASE WHEN hashed_password IS NOT NULL AND hashed_password <> '' THEN 1 ELSE 0 END)
    + (SELECT count(*) FROM user_providers WHERE user_id = users.id)) ::bigint
FROM users
WHERE users.id = $1
`

func (q *Queries) CountUserLoginMethods(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLoginMethods, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)
FROM users
WHERE deleted_at IS NULL
  AND ($1::text = '' OR email ILIKE '%' || $1::text || '%'
       OR first_name ILIKE '%' || $1::text || '%'
       OR last_name ILIKE '%' || $1::text || '%')
  AND (cardinality($2::text[]) = 0 OR role = ANY ($2::text[]))
  AND ($3::text = '' OR status = $3::text)
`

type CountUsersParams struct {
	Search string   `json:"search"`
	Roles  []string `json:"roles"`
	Status string   `json:"status"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Search, arg.Roles, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersActiveSince = `-- name: CountUsersActiveSince :one
SELECT count(*)
FROM users
WHERE deleted_at IS NULL
  AND last_seen >= $1
`

func (q *Queries) CountUsersActiveSince(ctx context.Context, lastSeen time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersActiveSince, lastSeen)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT count(*)
FROM users
WHERE role = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRoleAll = `-- name: CountUsersByRoleAll :many
SELECT role, count(*) ::bigint AS count
FROM users
WHERE deleted_at IS NULL
GROUP BY role
`

type CountUsersByRoleAllRow struct {
	Role  string `json:"role"`
	Count int64  `json:"count"`
}

func (q *Queries) CountUsersByRoleAll(ctx context.Context) ([]CountUsersByRoleAllRow, error) {
	rows, err := q.db.Query(ctx, countUsersByRoleAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountUsersByRoleAllRow{}
	for rows.Next() {
		var i CountUsersByRoleAllRow
		if err := rows.Scan(&i.Role, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUsersByStatus = `-- name: CountUsersByStatus :one
SELECT count(*)
FROM users
WHERE deleted_at IS NULL
  AND status = $1
`

func (q *Queries) CountUsersByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersCreatedSince = `-- name: CountUsersCreatedSince :one
SELECT count(*)
FROM users
WHERE deleted_at IS NULL
  AND created_at >= $1
`

func (q *Queries) CountUsersCreatedSince(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersCreatedSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, first_name, last_name, hashed_password, picture, role, status,
                   email_confirmed, last_seen, updated_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING id, email, first_name, last_name, hashed_password, picture, role, status, email_confirmed, last_seen, updated_at, updated_by, created_at, tos_accepted_at, tos_version, deleted_at, inactivity_warned_at, personal_data_purged_at, invitation_sent_at
`

type CreateUserParams struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	HashedPassword pgtype.Text        `json:"hashed_password"`
	Picture        string             `json:"picture"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	EmailConfirmed bool               `json:"email_confirmed"`
	LastSeen       time.Time          `json:"last_seen"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

// Timestamps come from the domain factory, not DB defaults — one source of
// truth for entity defaults.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.HashedPassword,
		arg.Picture,
		arg.Role,
		arg.Status,
		arg.EmailConfirmed,
		arg.LastSeen,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.Picture,
		&i.Role,
		&i.Status,
		&i.EmailConfirmed,
		&i.LastSeen,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.TosAcceptedAt,
		&i.TosVersion,
		&i.DeletedAt,
		&i.InactivityWarnedAt,
		&i.PersonalDataPurgedAt,
		&i.InvitationSentAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, hashed_password, picture, role, status, email_confirmed, last_seen, updated_at, updated_by, created_at, tos_accepted_at, tos_version, deleted_at, inactivity_warned_at, personal_data_purged_at, invitation_sent_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.Picture,
		&i.Role,
		&i.Status,
		&i.EmailConfirmed,
		&i.LastSeen,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.TosAcceptedAt,
		&i.TosVersion,
		&i.DeletedAt,
		&i.InactivityWarnedAt,
		&i.PersonalDataPurgedAt,
		&i.InvitationSentAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, first_name, last_name, hashed_password, picture, role, status, email_confirmed, last_seen, updated_at, updated_by, created_at, tos_accepted_at, tos_version, deleted_at, inactivity_warned_at, personal_data_purged_at, invitation_sent_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.Picture,
		&i.Role,
		&i.Status,
		&i.EmailConfirmed,
		&i.LastSeen,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.TosAcceptedAt,
		&i.TosVersion,
		&i.DeletedAt,
		&i.InactivityWarnedAt,
		&i.PersonalDataPurgedAt,
		&i.InvitationSentAt,
	)
	return i, err
}

const listUsersCursor = `-- name: ListUsersCursor :many
SELECT id, email, first_name, last_name, hashed_password, picture, role, status, email_confirmed, last_seen, updated_at, updated_by, created_at, tos_accepted_at, tos_version, deleted_at, inactivity_warned_at, personal_data_purged_at, invitation_sent_at
FROM users
WHERE deleted_at IS NULL
  AND ($1::text = '' OR email ILIKE '%' || $1::text || '%'
       OR first_name ILIKE '%' || $1::text || '%'
       OR last_name ILIKE '%' || $1::text || '%')
  AND (cardinality($2::text[]) = 0 OR role = ANY ($2::text[]))
  AND ($3::text = '' OR status = $3::text)
  AND (created_at, id) < ($4::timestamptz, $5::uuid)
ORDER BY created_at DESC, id DESC LIMIT $6
`

type ListUsersCursorParams struct {
	Search          string    `json:"search"`
	Roles           []string  `json:"roles"`
	Status          string    `json:"status"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	LimitVal        int32     `json:"limit_val"`
}

func (q *Queries) ListUsersCursor(ctx context.Context, arg ListUsersCursorParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersCursor,
		arg.Search,
		arg.Roles,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.HashedPassword,
			&i.Picture,
			&i.Role,
			&i.Status,
			&i.EmailConfirmed,
			&i.LastSeen,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.TosAcceptedAt,
			&i.TosVersion,
			&i.DeletedAt,
			&i.InactivityWarnedAt,
			&i.PersonalDataPurgedAt,
			&i.InvitationSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPage = `-- name: ListUsersPage :many
SELECT id, email, first_name, last_name, hashed_password, picture, role, status, email_confirmed, last_seen, updated_at, updated_by, created_at, tos_accepted_at, tos_version, deleted_at, inactivity_warned_at, personal_data_purged_at, invitation_sent_at
FROM users
WHERE deleted_at IS NULL
  AND ($1::text = '' OR email ILIKE '%' || $1::text || '%'
       OR first_name ILIKE '%' || $1::text || '%'
       OR last_name ILIKE '%' || $1::text || '%')
  AND (cardinality($2::text[]) = 0 OR role = ANY ($2::text[]))
  AND ($3::text = '' OR status = $3::text)
ORDER BY
  CASE WHEN $4::text = 'name' AND $5::text = 'asc' THEN lower(coalesce(nullif(btrim(first_name || ' ' || last_name), ''), email)) END ASC,
  CASE WHEN $4::text = 'name' AND $5::text = 'desc' THEN lower(coalesce(nullif(btrim(first_name || ' ' || last_name), ''), email)) END DESC,
  CASE WHEN $4::text = 'role' AND $5::text = 'asc' THEN role END ASC,
  CASE WHEN $4::text = 'role' AND $5::text = 'desc' THEN role END DESC,
  CASE WHEN $4::text = 'status' AND $5::text = 'asc' THEN status END ASC,
  CASE WHEN $4::text = 'status' AND $5::text = 'desc' THEN status END DESC,
  CASE WHEN $4::text = 'created' AND $5::text = 'asc' THEN created_at END ASC,
  CASE WHEN $4::text = 'created' AND $5::text = 'desc' THEN created_at END DESC,
  CASE WHEN $4::text = 'lastSeen' AND $5::text = 'asc' THEN last_seen END ASC,
  CASE WHEN $4::text = 'lastSeen' AND $5::text = 'desc' THEN last_seen END DESC,
  id DESC
LIMIT $7 OFFSET $6
`

type ListUsersPageParams struct {
	Search    string   `json:"search"`
	Roles     []string `json:"roles"`
	Status    string   `json:"status"`
	SortBy    string   `json:"sort_by"`
	SortDir   string   `json:"sort_dir"`
	OffsetVal int32    `json:"offset_val"`
	LimitVal  int32    `json:"limit_val"`
}

// Offset mode is used by the admin table: column sorting and a page count
// cannot be expressed by the legacy created_at cursor.
func (q *Queries) ListUsersPage(ctx context.Context, arg ListUsersPageParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersPage,
		arg.Search,
		arg.Roles,
		arg.Status,
		arg.SortBy,
		arg.SortDir,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.HashedPassword,
			&i.Picture,
			&i.Role,
			&i.Status,
			&i.EmailConfirmed,
			&i.LastSeen,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.TosAcceptedAt,
			&i.TosVersion,
			&i.DeletedAt,
			&i.InactivityWarnedAt,
			&i.PersonalDataPurgedAt,
			&i.InvitationSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserInvitationSent = `-- name: MarkUserInvitationSent :execrows
UPDATE users
SET invitation_sent_at = $1::timestamptz
WHERE id = $2
  AND status = 'incomplete'
`

type MarkUserInvitationSentParams struct {
	SentAt time.Time `json:"sent_at"`
	ID     uuid.UUID `json:"id"`
}

// Narrow write outside the aggregate UPDATE set (like last_seen): the last
// time an invitation email was queued for a still unconfirmed account; the
// retention clock of unconfirmed accounts runs from it.
func (q *Queries) MarkUserInvitationSent(ctx context.Context, arg MarkUserInvitationSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUserInvitationSent, arg.SentAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registrationsByDaySince = `-- name: RegistrationsByDaySince :many
SELECT date_trunc('day', created_at) ::timestamptz AS day, count(*)::bigint AS count
FROM users
WHERE deleted_at IS NULL
  AND created_at >= $1
GROUP BY 1
ORDER BY 1
`

type RegistrationsByDaySinceRow struct {
	Day   time.Time `json:"day"`
	Count int64     `json:"count"`
}

func (q *Queries) RegistrationsByDaySince(ctx context.Context, createdAt time.Time) ([]RegistrationsByDaySinceRow, error) {
	rows, err := q.db.Query(ctx, registrationsByDaySince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistrationsByDaySinceRow{}
	for rows.Next() {
		var i RegistrationsByDaySinceRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users
SET email           = $2,
    first_name      = $3,
    last_name       = $4,
    hashed_password = $5,
    picture         = $6,
    role            = $7,
    status          = $8,
    email_confirmed = $9,
    tos_accepted_at = $10,
    tos_version     = $11,
    updated_at      = $12,
    updated_by      = $13,
    deleted_at      = $14
WHERE id = $1
  -- Optimistic lock: the caller sends the updated_at it loaded; a concurrent
  -- write moved it, so 0 rows means "modified since read" (or gone).
  AND updated_at IS NOT DISTINCT FROM $15
`

type UpdateUserParams struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	HashedPassword    pgtype.Text        `json:"hashed_password"`
	Picture           string             `json:"picture"`
	Role              string             `json:"role"`
	Status            string             `json:"status"`
	EmailConfirmed    bool               `json:"email_confirmed"`
	TosAcceptedAt     pgtype.Timestamptz `json:"tos_accepted_at"`
	TosVersion        pgtype.Int4        `json:"tos_version"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         uuid.NullUUID      `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
}

// Whole-aggregate write for the User entity: the repository maps the full
// domain model here. Deliberately excludes last_seen (owned by the async
// touch hot path — including it would race and lose updates) and created_at
// (immutable). updated_at comes from the domain (touch), not now().
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.HashedPassword,
		arg.Picture,
		arg.Role,
		arg.Status,
		arg.EmailConfirmed,
		arg.TosAcceptedAt,
		arg.TosVersion,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserLastSeen = `-- name: UpdateUserLastSeen :execrows
UPDATE users
SET last_seen = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastSeen(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserLastSeen, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
